### ISSUE TITLE
Question about pretraining the meta networks of MEND

### ISSUE THREAD

**Issue by wending0417** [zjunlp/EasyEdit#10]
Hi, thanks for your great contributions! 
I'm trying to use MEND for editing. But when I pretained the meta networks of MEND under the guidance of the eaxmple of "Trainer" in README, the program exited with following information:

08/24/2023 12:07:07 - INFO - easyeditor.trainer.EditTrainer -   Step 19009/19009          edit: 0.00002      acc_pre: 0.00365      acc_post: 0.00034      acc_delta: 0.00330      it_time: 0.3682
08/24/2023 12:07:07 - INFO - easyeditor.trainer.BaseTrainer -   Step 0:
08/24/2023 12:07:07 - INFO - easyeditor.trainer.BaseTrainer -   loss/edit_val       :  nan
loss/loc_val        :  nan
edit/acc_val        :  0.00002
edit/log_prob_val   :  nan
edit/prob_val       :  nan
acc/pre_val         :  0.00365
acc/post_val        :  0.00034
nll/pre_val         :  11.29517
perplexity/pre_val  :  80432.48438
nll/post_val        :  nan
perplexity/post_val :  nan
n_tokens/pre_val    :  4.98143
n_tokens/post_val   :  4.98143
time/edit_val       :  0.25354
loss/total_val      :  nan
loss/total_edit_val :  nan
memory/alloc_max_val:  14272471495.30265
memory/res_max_val  :  14786047237.42732
eval_time/elapsed   :  6998.66469
eval_time/average   :  0.36818
08/24/2023 12:07:07 - INFO - easyeditor.trainer.BaseTrainer -   Wrote results to:
08/24/2023 12:07:07 - INFO - easyeditor.trainer.BaseTrainer -   ./results/results.json
GPTTokenizer Detected, Set pad token id and left padding!!!
GPTTokenizer Detected, Set pad token id and left padding!!!

I don't know why the program didn't save the model and how to fix the bug. Looking forward to your kind help!

**Comment by pengzju** [comment]
Hello, which dataset did you choose?

**Comment by wending0417** [comment]
zsre

**Comment by pengzju** [comment]
`nan` errors usually come from dividing by 0. I suggest you add a breakpoint [here](https://github.com/zjunlp/EasyEdit/blob/main/easyeditor/trainer/losses.py#L72) or
```python
import pdb
pdb.set_trace()
```
to see if `n_tokens` are 0. 

You need to check the input of the data, I can't repeat your error, may I ask what `base model` you chose?

**Comment by wending0417** [comment]
Thanks for your kind explanation. The base model I chose is gpt2-xl.

**Comment by pengzju** [comment]
I will confirm the result of gpt2-xl, please wait for a while

**Comment by wending0417** [comment]
I will try to test if n_tokens are 0. But it may be time-consuming so I will reply later. I just following the guidance in README and the dataset and base model I used all come from the source provided in README. Thanks for your patient help again!

**Comment by pengzju** [comment]
As shown, I tried to train MEND on gpt2-xl using the latest version of easyedit, and I couldn't replicate your results. It is recommended that you update the code to the latest version before trying.
<img width="1342" alt="image" src="https://github.com/zjunlp/EasyEdit/assets/63391142/a1b8ab31-b393-4936-8bef-724a02c54cd3">


- Make sure you use the yaml configuration file in the `TRAINING` directory during training

**Comment by pengzju** [comment]
If your problem has been resolved, please help close this issue.

**Comment by wending0417** [comment]
Thanks for your help. I will update the code to the latest version and try it again.
