### ISSUE TITLE
MEND编辑方法中未知的参数archive

### ISSUE THREAD

**Issue by How-Fun** [zjunlp/EasyEdit#102]
我注意到，在hparams/MEND文件夹下的yaml文件当中，都存在其它编辑方法所不具有的独特参数：
`archive: /mnt/peng/EasyEdit/results/models/MEND/llama-2-7b`
这个地址看起来像是llama-2-7b模型文件，但加载之后并不能很好的运行。我仔细阅读了你们的说明文档和课程ppt，但是并没有指明我该如何获取该“trained MEND model“。
期待您的解答，万分感谢！

**Comment by XeeKee** [comment]
mend方法是使用编辑器对模型进行编辑，archive参数就是您的编辑器地址，如果你想训练自己的编辑器，请使用test_MEND_Meta_Train_Llama函数

**Comment by XeeKee** [comment]
在edit.py文件中我们提供了一些编辑器训练函数def test_MEND_Meta_Train():
    training_hparams = MENDTrainingHparams.from_hparams('./hparams/TRAINING/MEND/llama-7b.yaml')
    train_ds = ZsreDataset('./data/zsre_mend_train.json', config=training_hparams)
    eval_ds = ZsreDataset('./data/zsre_mend_eval.json', config=training_hparams)
    trainer = EditTrainer(
        config=training_hparams,
        train_set=train_ds,
        val_set=eval_ds
    )

    trainer.run()

**Comment by XeeKee** [comment]
在edit.py文件中，我们有已经写好的编辑器训练函数，例如def test_MEND_Meta_Train():
    training_hparams = MENDTrainingHparams.from_hparams('./hparams/TRAINING/MEND/llama-7b.yaml')
    train_ds = ZsreDataset('./data/zsre_mend_train.json', config=training_hparams)
    eval_ds = ZsreDataset('./data/zsre_mend_eval.json', config=training_hparams)
    trainer = EditTrainer(
        config=training_hparams,
        train_set=train_ds,
        val_set=eval_ds
    )

    trainer.run()关于训练器超参可以在main/hparams/TRAINING/MEND中选择您需要的模型参数并修改，其结果会保存在results_dir中填写的地址。您也可以参考readme中的[Trainer](https://github.com/zjunlp/EasyEdit/tree/main#trainer)部分，对于训练器有详细介绍

**Comment by XeeKee** [comment]
在edit.py文件中，我们有已经写好的编辑器训练函数你可以参考，例如
def test_MEND_Meta_Train():
training_hparams = MENDTrainingHparams.from_hparams('./hparams/TRAINING/MEND/llama-7b.yaml')
train_ds = ZsreDataset('./data/zsre_mend_train.json', config=training_hparams)
eval_ds = ZsreDataset('./data/zsre_mend_eval.json', config=training_hparams)
trainer = EditTrainer(
config=training_hparams,
train_set=train_ds,
val_set=eval_ds
)
trainer.run()
关于训练器超参可以在main/hparams/TRAINING/MEND中选择您需要的模型参数并修改，其结果会保存在results_dir中填写的地址。
您也可以参考readme中的[Trainer](https://github.com/zjunlp/EasyEdit/tree/main#trainer)部分，对于训练器有详细介绍

**Comment by binflyfiled** [comment]
请问，easyedit中给出了MEND原文使用的编辑器了吗?

**Comment by XeeKee** [comment]
没有，我传过一个自己训的编辑器在谷歌网盘，您可以查阅readme。

**Comment by wheat-ops** [comment]
你好，没有在readme中看到您训好的编辑器网盘链接，可以发一下吗

**Comment by XeeKee** [comment]
https://drive.google.com/drive/folders/1WyqsN-O5bpzzRvbYrVDJdVHdOu1x6mSB
hello
这里有个人训练的ckpt，我后续会持续更新这个文件夹里面的ckpt来便于您复现
