### ISSUE TITLE
Worse performance

### ISSUE THREAD

**Issue by ssr123s** [zjunlp/EasyEdit#106]
I successfully ran your Rome project example and the results were good. However, when I switched to my own data, there was a problem. If I edit only one question and answer at a time, the results are good, but if I edit multiple questions and answers at the same time, the performance worsens. Is there a similar situation or explanation for this 
thanks for your answer ！！

**Comment by XeeKee** [comment]
Rome performs well only in single edits, but performs poorly in multi-edits. If you want to do multi-edits, please use Memit

**Comment by zxlzr** [comment]
Do you have any other questions?
