### ISSUE TITLE
Not enough disk space. 

### ISSUE THREAD

**Issue by ssr123s** [zjunlp/EasyEdit#107]
When I run MEMIT to edit LLAMA2 on AutoDL, the program reports an error: "Insufficient disk space. Required: 34.06 GiB (Download: 16.99 GiB, Generation: 17.07 GiB, Post-processing: unknown size)." However, I have tried expanding the data disk and it shows that there is still 100G of space remaining on the data disk. Are there other ways to operate, such as changing the download path? If so, can you tell me how to modify it?

**Comment by ssr123s** [comment]
Thanks for your answer。The model has already been downloaded locally, and editing Rome runs normally. However, when editing MEMIT and calling edit code, an error occurs.The specific error message is as follows:








could you please give some other advice


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjunlp/EasyEdit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月2日(星期六) 中午11:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zjunlp/EasyEdit] Not enough disk space.  (Issue #107)





 
I cannot know how you downloaded the model, but you can check the available disk space on your system. If your system's disk capacity is insufficient, you can firstly download the model locally and then load it.

**Comment by xzwyyd** [comment]
Please upload the error message image again, as it is not showing up on my end, and therefore I am unable to view it. Thank you very much for your understanding and cooperation!

**Comment by ssr123s** [comment]
I have already sent the complete code in an attachment nearby, and the specific error information is in the Traceback after editor.edit(). Thank you again for your response."







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjunlp/EasyEdit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月2日(星期六) 中午12:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zjunlp/EasyEdit] Not enough disk space.  (Issue #107)





 
Please upload the error message image again, as it is not showing up on my end, and therefore I am unable to view it. Thank you very much for your understanding and cooperation!

**Comment by xzwyyd** [comment]
You can try downloading the dataset to your local machine and using the commented code in lines 99-101 of `EasyEdit/easyeditor/models/rome/layer_stats.py` to replace lines 102-105 to load the local dataset. The code will be as shown in the screenshot:
![loa_data](https://github.com/zjunlp/EasyEdit/assets/96838434/6159a2fe-5f07-4837-bf2c-a5921e462bda)

**Comment by ssr123s** [comment]
thanks for your patience。I will try it and give your response



---Original---
From: "Ziwen ***@***.***&gt;
Date: Sat, Dec 2, 2023 13:32 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [zjunlp/EasyEdit] Not enough disk space.  (Issue #107)




 
You can try downloading the dataset to your local machine and using the commented code in lines 99-101 of EasyEdit/easyeditor/models/rome/layer_stats.py to replace lines 102-105 to load the local dataset. The code will be as shown in the screenshot:
 loa_data.png (view on web)

**Comment by ssr123s** [comment]
Thank you very much for your suggestion; I successfully fixed the bug related to memory operation. 
Although MEMIT can run successfully, when writing only to layer4, it shows over 1000 are need, which takes nearly an hour. I am running this on 3 4090s, and I have checked the memory usage; the GPUs are being utilized. Is this normal, or do you have any other suggestions?（I only edit three examples)
<img width="692" alt="4fa155697f6440dea8013f2277072e2" src="https://github.com/zjunlp/EasyEdit/assets/152489945/caed0a9a-140d-4c06-b1cc-3dfd930268bf">
）

**Comment by xzwyyd** [comment]
This is a normal phenomenon, and it is expected that the MEMIT method would take some time.

**Comment by ssr123s** [comment]
Thank you very much for your advice. I wish you success in your work and a happy life.
