### ISSUE TITLE
Readme doc about hparams

### ISSUE THREAD

**Issue by Gavintc** [zjunlp/EasyEdit#108]
Is there a documenation explaining the meaning of all the parameters used in "[hparams] (https://github.com/zjunlp/EasyEdit/tree/main/hparams)"?

**Comment by zxlzr** [comment]
Hi, do you have any further questions?

**Comment by Gavintc** [comment]
Thanks, the readme docs are very helpful. No other questions. Can close this issue.

**Comment by peixin-lin** [comment]
> I wrote a readme for each hparams,introduced the functions of some parameters that I find difficult to understand. If you have any questions, please contact me in time

Hi, I checked out the README in the repository page but I didn't find the part about hparams. So I am wandering that were you referring to another README in different directory? Can you specify the path or link for me?

**Comment by pengzju** [comment]
You can refer to here: https://github.com/zjunlp/EasyEdit/blob/main/hparams/FT/readme

**Comment by zxlzr** [comment]
Hi, do you have any further questions?
