### ISSUE TITLE
How much memory is required for editing Qwen-14B with ROME or MEMIT?

### ISSUE THREAD

**Issue by peixin-lin** [zjunlp/EasyEdit#109]
I checked out the memory requirement in the README but Qwen series models are not mentioned. I experimented with an H800 with 80G, which works fine with Qwen-7B but gets OOM with Qwen-14B (both ROME and MEMIT). Can you provide the memory requirements for Qwen-14B?

**Comment by XeeKee** [comment]
When running Rome and Memit locally, they respectively occupy 66GB and 74GB of VRAM. You can try modifying the hyperparameters to reduce VRAM usage.

**Comment by zxlzr** [comment]
Hi, do you have any further questions?

**Comment by peixin-lin** [comment]
I am confused about the function of hyperparameters. Is there any instruction that can help me tune the hyperparameters in order to reduce VRAM usage?
