### ISSUE TITLE
Please support deepspeed

### ISSUE THREAD

**Issue by Davidgzx** [zjunlp/EasyEdit#111]
The integration for deepspeed is supported by huggingface transformers, please support it when parsing config

**Comment by pengzju** [comment]
Thank you for your suggestions and we will consider supporting deepspeed

**Comment by zxlzr** [comment]
Hello, apologies, our in-depth research has found that some of the current editing methods involve modifying the internal parameters of LLMs, which is incompatible with DeepSpeed. We cannot resolve this issue in the short term. However, you can use the native fine-tuning (ft) of transformers in combination with DeepSpeed to implement editing.
