### ISSUE TITLE
Why ROME dose not support bf16 and fp16?

### ISSUE THREAD

**Issue by Davidgzx** [zjunlp/EasyEdit#112]
Flashattention is widely adopted, and it dose not support fp32. It is not convenient to train a model without bf16

**Comment by pengzju** [comment]
In theory, ROME only involves modifications to the FFN layer and can support the usage of Flash Attention.
Thank you for your suggestions, we will support bf16 or fp16 as soon as possible.😊

**Comment by pengzju** [comment]
Sorry for the late reply. I hope everything is going well with you recently.

Thanks for your sincere suggestion, the latest version of EasyEdit has supported editing the `fp16` model through ROME, and the actual test has saved 10G of GPU memory on LlaMA-7B, welcome you to actively try. 😊

**Comment by pengzju** [comment]
If this reply solves your problem, please help me close this issue. 😊
