### ISSUE TITLE
Editing non-QA knowledge, such as DUNE dataset.

### ISSUE THREAD

**Issue by quqxui** [zjunlp/EasyEdit#118]
Hi,

Thank you for your valuable open source contributions! I would like to inquire about how to utilize your toolkit for editing reasoning and non-QA knowledge.

For instance, in the paper titled "DUnE: Dataset for Unified Editing," there is an example that requires editing or injecting knowledge. The scenario is as follows:

- **Knowledge needed to edit or inject:**
In a tiger population, without any male tigers, the females will not be able to mate and produce offspring, making the population die out. 
- **Edit Query:**
Some animals are very rare. For example, there are very few Siberian tigers. If the only Siberian tigers left are female, what will most likely happen? A. The females will find another type of male animal to mate with and produce more Siberian tigers. B. The females will mate with each other and produce more Siberian tigers. C. The females will only be able to produce female Siberian tigers. D. The females will not be able to produce more Siberian tigers and they will die out. [Answer: D]

I eagerly await your response!

**Comment by XeeKee** [comment]
Thank you for your attention. We plan to support this method in February 2024.

**Comment by JizhanFang** [comment]
Hello, we now support this ICL-based editing method `PROMPT`. In simple terms, you only need to provide the **Knowledge needed to edit or inject** as the new fact field and use the **Edit Query** as the prompt, just as we do in the `PROMPT` method. You can find more details in the README document for the PROMPT method.
https://github.com/zjunlp/EasyEdit/blob/main/examples/PROMPT.md
