### ISSUE TITLE
Problem of run_zsre_llama2.py with MEMIT editing method

### ISSUE THREAD

**Issue by BonnieLuo** [zjunlp/EasyEdit#119]
Thanks for your interesting works! I have a problem about runing run_zsre_llama2.py code with MEMIT editing method. Here's the specific question: I can not get the wikitext-103-raw-v1 dataset online, thus I need to save it in local. However, I can not find the correct path to save, and the floder [dataset] in easyeditor lacks load_dataset.py, resulting in raw_ds = load_dataset(ds_name, dict(wikitext="wikitext-103-raw-v1", wikipedia="20200501.en")[ds_name]) in layer_stats.py(102 rows in floder easyeditor/rome/models/) error. Could you please help me sovle this probem? Looking forward to your reply~

**Comment by XeeKee** [comment]
You can try downloading the dataset to your local machine and using the commented code in lines 99-101 of EasyEdit/easyeditor/models/rome/layer_stats.py to replace lines 102-105 to load the local dataset.

**Comment by zxlzr** [comment]
hi, have you solved your issue?

**Comment by BonnieLuo** [comment]
> You can try downloading the dataset to your local machine and using the commented code in lines 99-101 of EasyEdit/easyeditor/models/rome/layer_stats.py to replace lines 102-105 to load the local dataset.

Thanks for your timely reply. I have solved this problem.

**Comment by BonnieLuo** [comment]
> hi, have you solved your issue?

Yes, thanks for your help. I will close this issue.
