### ISSUE TITLE
Multimodal editing

### ISSUE THREAD

**Issue by haohaodw** [zjunlp/EasyEdit#120]
Hi, I'm interested in your multimodal editing work, but I have two confusions about the dataset.
Question 1: What do "pred" and "alt" in the dataset refer to.
Question 2: Table 1 in the paper indicates that L-Locality and M-Locality have 4289 and 5046 entries respectively. Do I need so much data during the test phase of image caption and vqa? I don't seem to see so much data in the test data set.

**Comment by tbozhong** [comment]
Thanks for your attention!

1. `pred` refers to the result of BLIP2 prediction and `alt` represents the correct answer.
2. Regarding data usage, there's no need to test with all the data; using a portion of samples is sufficient. For this, we have already pre-selected samples within the multimodal framework of EasyEdit, which you can use directly. Additionally, you can download the original L-Locality/M-Locality dataset for custom sampling [here](https://drive.google.com/drive/folders/1jBdTJxUb9wEeHnvG-RY8dv5_I4QlDpUS?usp=drive_link).

**Comment by haohaodw** [comment]
So when I use the MMEdit dataset to compare with existing methods, for L-Locality/M-Locality I only need to use the locality issues contained in vqa_eval.json and caoption_eval_edit.json (2093 and 1000 respectively)

**Comment by tbozhong** [comment]
Yes, your understanding is correct.
