### ISSUE TITLE
issues when pretraining SERAC

### ISSUE THREAD

**Issue by wang-debug** [zjunlp/EasyEdit#123]
Thank you for your exciting work!

But I met a problem when I tried to pretraining for SERAC as follows while the training of MEND is normal. Is it because of the classifier and the small model?

Code:
`training_hparams = SERACTrainingHparams.from_hparams('./hparams/TRAINING/SERAC/llama-7b.yaml')
    train_ds = ZsreDataset('../data_construction/zsre/zsre_mend_train.json', config=training_hparams)
    eval_ds = ZsreDataset('../data_construction/zsre/zsre_mend_eval.json', config=training_hparams)
    trainer = EditTrainer(
        config=training_hparams,
        train_set=train_ds,
        val_set=eval_ds
    )
    trainer.run()`
    
Error:
 `Traceback (most recent call last):
  File "EasyEdit/edit.py", line 2334, in <module>
    main()
  File "EasyEdit/edit.py", line 2276, in main
    test_SERAC_Zsre_Train_Llama()
  File "EasyEdit/edit.py", line 373, in test_SERAC_Zsre_Train_Llama
    trainer.run()
  File "EasyEdit/easyeditor/trainer/BaseTrainer.py", line 167, in run
    train_info = self.train_step(batch)
  File "/asyEdit/easyeditor/trainer/EditTrainer.py", line 143, in train_step
    grad = torch.nn.utils.clip_grad_norm_(
  File "miniconda3/envs/EasyEdit/lib/python3.9/site-packages/torch/nn/utils/clip_grad.py", line 64, in clip_grad_norm_
    raise RuntimeError(
RuntimeError: The total norm of order 2.0 for gradients from `parameters` is non-finite, so it cannot be clipped. To disable this error and scale the gradients by the non-finite norm anyway, set error_if_nonfinite=False`

Looking forward to your help!

**Comment by pengzju** [comment]
This means that your gradient is `nan`. （https://pytorch.org/docs/stable/generated/torch.nn.utils.clip_grad_norm_.html）
Did you use `float16`? I think this is the reason.

**Comment by wang-debug** [comment]
I didn't change the codes and [config file](https://github.com/zjunlp/EasyEdit/blob/main/hparams/TRAINING/SERAC/llama-7b.yaml) from your repo.  It seems `half` is set to False.

**Comment by pengzju** [comment]
The small model you use is `https://huggingface.co/JackFram/llama-160m`?

**Comment by wang-debug** [comment]
Yes, I use `https://huggingface.co/JackFram/llama-160m`.

**Comment by pengzju** [comment]
> Note: Please ensure that the tokenizer of the large and small models are consistent, for example, both are llama2 or both are llama1.

I have two suggestions:
Tip 1: You should set `error_if_nonfinite` to `False` to bypass the `nan` limitation. (This may cause the training to fail to converge, you can observe the `acc` and other indicators, if it fails to converge please try tip 2.
Tip 2: Use another small model, such as `https://huggingface.co/Cheng98/llama-160m`.

**Comment by wang-debug** [comment]
Tip 2 worked for me. Thank you so much for your help. :)

**Comment by wang-debug** [comment]
Additionally, I would like to ask, was the additional model for MEND and SERAC trained on `zsre/zsre_mend_train.json`? If I want to edit on `counterfact`, do I need to change the additional model?

**Comment by pengzju** [comment]
Yes, you need to retrain the additional model, which is the limitation of `mend` and `serac`.

**Comment by wang-debug** [comment]
I would like to inquire about how you split the dataset. Was it done through random sampling? How much training data is ? Thank you for your reply.

**Comment by pengzju** [comment]
In this paper, we use the training set `counterfact-train.json`, `zsre_mend_train.json`, and the validation set is the corresponding `val` file. 
You can get the data here: https://drive.google.com/file/d/1WRo2SqqgNtZF11Vq0sF5nL_-bHi18Wi4

**Comment by wang-debug** [comment]
So, did you randomly sample `counterfact-train.json` and `zsre_mend_train.json` from the complete `counterfact`/`zsre` dataset?

**Comment by pengzju** [comment]
You don't need to sample it, just use it as the train set.

**Comment by zxlzr** [comment]
hi buddy, do you have further questions?

**Comment by wang-debug** [comment]
> You don't need to sample it, just use it as the train set.

I have a few more questions:

- The original `counterfact` dataset didn't have divisions like `train`, `edit`, and `val`. How did you split?
- Are the samples in `counterfact_portability_gpt4.json` from `counterfact-edit.json`?

**Comment by pengzju** [comment]
Q1: We modified the original counterfact dataset to some extent. Resplit the data set at a ratio of 10:10:2. 
Q2: Yes, `counterfact_portability_gpt4.json` is sampled from `counterfact-edit.json`. Limited by resources, we cannot provide `portability` data for every data point.

**Comment by wang-debug** [comment]
Thank you for your response!
