### ISSUE TITLE
"RecursionError: maximum recursion depth exceeded" for GRACE

### ISSUE THREAD

**Issue by sev777** [zjunlp/EasyEdit#129]
https://github.com/zjunlp/EasyEdit/blob/c6a746367907f75d83b0e7a971b206480c6c2edd/easyeditor/models/grace/GRACE.py#L144

When  I  test GRACE on Zsre, after edit 242 cases,  I get the "RecursionError: maximum recursion depth exceeded".

I debug the  code and find " layer_out = self.layer(*args)" make this issue, and at this time, the self.layer is the GRACEAdapter itself, so the code will recursion without stop.

But I didn't find why  self.layer is the GRACEAdapter itself, could you help to figure this problems?

Thanks!

**Comment by XeeKee** [comment]
We haven't encountered this issue in our local environment.Can you provide me with the name of your model and the contents of your hyperparameters?

**Comment by sev777** [comment]
> We haven't encountered this issue in our local environment.Can you provide me with the name of your model and the contents of your hyperparameters?

I run the "run_zsre_llama2.py" with llama-7B and use GRACE as the editor on the "zsre_mend_eval_portability_gpt4.json" dataset. 

After edit 242 edtis, I will meet this issue.

the following figure shows that the self.layer is GRACEAdapter  and  the code will recursion.

![图片](https://github.com/zjunlp/EasyEdit/assets/38484725/7431e9e0-35c6-478d-91f3-b03976487ea9)

![图片](https://github.com/zjunlp/EasyEdit/assets/38484725/83a30e36-4ebb-461d-877e-ae49b8fe53ed)


And I find the GRACE will initial every time when I call self.apply_algo(...), does it necessory?

![图片](https://github.com/zjunlp/EasyEdit/assets/38484725/40fabd16-029c-498a-ae28-81d0a964295c)

**Comment by XeeKee** [comment]
Hello, Grace will generate a new GRACE layer to store the result of each edit you make, and as you continue to edit, the GRACE layers will become larger, potentially causing a memory overflow. I recommend that you do not exceed 100 edits per session.

**Comment by XeeKee** [comment]
These days, we will optimize the code of Grace once again. Please keep an eye on our latest updates.

**Comment by XeeKee** [comment]
We have optimized the GRACE code. If you choose "copy" as "true," it will only edit one piece of knowledge at a time. However, please note that this may result in increased GPU memory usage.

**Comment by XeeKee** [comment]
you can push the new code

**Comment by sev777** [comment]
> We have optimized the GRACE code. If you choose "copy" as "true," it will only edit one piece of knowledge at a time. However, please note that this may result in increased GPU memory usage.

Thanks ！
And if it is possible to remove the GRACE layer after edit current edits, that can keep GPU memory  unchange.

**Comment by XeeKee** [comment]
This should be quite unlikely to achieve. Multiple edits in GRACE are implemented through recursion in the GRACE layer. Deleting the GRACE layer not only prevents further editing but also erases the existing editing effects.

**Comment by pengzju** [comment]
I have fixed this bug, you can update your code and try again
