### ISSUE TITLE
Knowledge editing with lower VRAM

### ISSUE THREAD

**Issue by whitepapercg** [zjunlp/EasyEdit#130]
Hi and Merry Christmas! Any chance we will see an implementations of techniques for consumer PCs (12/24gb VRAM req)?
I tried modifying your code to load llama models in float16 and 4-bit (bitsandbytes), but neither method ran successfully for various reasons.

**Comment by zxlzr** [comment]
We will try to fix you issue asap.

**Comment by pengzju** [comment]
[Here](https://github.com/zjunlp/EasyEdit/blob/main/easyeditor/editors/editor.py#L61), you can try loading a model of type `fp16`. You only need to change `torch_dtype` to `torch.float32`.

> Tips: Some editing methods may not support fp16, such as MEMIT, depending on the editing success rate.
