### ISSUE TITLE
How to try it on new train and test datasets?

### ISSUE THREAD

**Issue by StarrySeas1** [zjunlp/EasyEdit#131]
If there are 1,000 training examples and 100 test examples, how to conduct the MEND experiment? After training on the train dataset through Trainer, do you test on the test dataset? Or edit the model directly with the test dataset?

**Comment by pengzju** [comment]
For 1,000 training examples and 100 test examples:
- You can split 1000 examples according to the ratio of `9:1`, corresponding to `train.json` and `val.json` respectively.
- 100 test examples can be used as edit set, namely `edit.json`

**Comment by StarrySeas1** [comment]
What are the three files train.json, val.json, edit.json used for? Do you edit the test dataset directly?
What do train.json and val.json do if you edit directly on the test dataset?

**Comment by pengzju** [comment]
Q2: You can see in our [paper](https://arxiv.org/abs/2305.13172) that some editing methods such as `MEND`, `SERAC` need to train additional editing network structures in advance, so `train.json` and `val.json` are required to perform standard deep learning paradigms.


Q1: As described in Q2, `train.json` and `val.json` are for model training (partial editing method required). Importantly, all editing methods require an `edit.json` dataset to test edit performance, a bit like the test set in traditional machine learning

**Comment by zxlzr** [comment]
Hi buddy, do you have any further questions?
