### ISSUE TITLE
will support chatglm3-6b-base or chatglm3-6b-chat and what's the required GPU size?

### ISSUE THREAD

**Issue by kevindany** [zjunlp/EasyEdit#133]
I would like to try on chatglm3, thanks in advanced!

**Comment by pengzju** [comment]
You can refer to the configuration of `chatglm2` to try to edit `chatglm3`. If you have any questions, please contact me in time. Thank you for your attention.

**Comment by kevindany** [comment]
Great, thanks a lot!
