### ISSUE TITLE
How to compute Portability and Locality?

### ISSUE THREAD

**Issue by YJiangcm** [zjunlp/EasyEdit#134]
Thanks for your great work!

I have a question related to the computation of the evaluation metric. How to calculate Portability since it has three parts including Alias, Compositionality and Reasoning, and Logical Generalization?

Besides, for a single sample in the test dataset, it may only have one attribution such as `Reasoning`, and the `Logical_Generalization` and `Subject_Aliasing` are missing. Then how to calculate Portability?

From line 517 to line 523 of [easyeditor/editors/editor.py](https://github.com/zjunlp/EasyEdit/blob/e4e3999a2295785d40558cefc1b59d011aac217c/easyeditor/editors/editor.py), it seems that each edit sample must have a `Reasoning` input if we want to calculate the metric of `Reasoning`. Ohterwise, it will raise the Assertion error "One Edit instance needs one locality input.....".  

I ran the following script:
```
python run_knowedit_llama2.py \
    --editing_method=ROME \
    --hparams_dir=../hparams/ROME/llama-7b \
    --data_dir=./data \
    --datatype='counterfact'
```
and it has the above Assertion error.

**Comment by XeeKee** [comment]
Regarding Reasoning, Logical Generalization, and Subject Aliasing, our current computational metrics only assess the model's ability to correctly predict answers. Currently, each edit can only support one data point. We will continue to optimize this in the future.

**Comment by YJiangcm** [comment]
Thanks for your answering! In Table 4 of your paper, do you report the Portability by taking average of the Reasoning score, Logical Generalization score, and Subject Aliasing score?

**Comment by littlefive5** [comment]
Yeah, here we take the average of the scores.

**Comment by YJiangcm** [comment]
Thanks for the reply.
