### ISSUE TITLE
GRACE Loss Not Change

### ISSUE THREAD

**Issue by Yzk1114** [zjunlp/EasyEdit#135]
https://github.com/zjunlp/EasyEdit/blob/c6a746367907f75d83b0e7a971b206480c6c2edd/easyeditor/models/grace/GRACE.py#L79
I run edit.py GRACE demo on llama-7b. During the optimization process, I print the loss value and I find that the Optimization loss not change. It means that your code may have a significant bug. If I haven't made any mistakes, I hope you can fix this problem as soon as possible.

**Comment by zxlzr** [comment]
Sorry, we will check the code and try to reproduce your issue. We will try to fix it asap.

**Comment by XeeKee** [comment]
You can try changing the "replacement" parameter to "replace_all," perhaps because the structural differences between llama and GPT series models are causing this situation.

**Comment by Yzk1114** [comment]
> You can try changing the "replacement" parameter to "replace_all," perhaps because the structural differences between llama and GPT series models are causing this situation.

Amazing! This method has indeed solved this problem. But can you explain in detail why this is happening? I feel very confused.

**Comment by XeeKee** [comment]
Sorry,I am also confuse about this.Maybe it is just a trick.
If I have the time, I will research the underlying reasons, and then I will notify you promptly.
