### ISSUE TITLE
Error when running MEND on Llama-7b using ZsreDataset

### ISSUE THREAD

**Issue by yaohui120** [zjunlp/EasyEdit#136]
It appears that input and module are not in the same device when running MEND on Llama-7b using ZsreDataset. This error occurs in the calculation of GradientTransform. But it doesn't occur when running MEND on minigpt4(multimodal edit). 
 The error is:
(Pdb) self.mlp(torch.cat((u_input, v_input), -1), mode=param_idx)
*** RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:3 and cuda:0! (when checking argument for argument mat2 in method wrapper_CUDA_mm)

**Comment by cheng-siyuan** [comment]
Thanks for your attention. MEND does not support model parallelism, so you need to edit the LLaMA-7b model on a single GPU. Ensure the `model_parallel` in the config file is set to `false`.

**Comment by yaohui120** [comment]
OK, I will try to implement that. Besides, which function and method support model parallelism? I think it's great and convenient if you release a statistical table about that. Or just the methods with model_parallel appears in the corresponding config file are supported? I see that  model_parallel is true in llama-7b.yaml.

**Comment by cheng-siyuan** [comment]
Thank you for your suggestion. We will update and clarify in the README file: MEND alone does not support model parallelism, whereas the other methods do.
