### ISSUE TITLE
About the Trainer

### ISSUE THREAD

**Issue by yaohui120** [zjunlp/EasyEdit#138]
From the folder easyeditor/trainer/algs, it appears that only three or four methods can be used to train model(single model edit)? That means, if I want to use ROME to train the model, I should achieve a trainer of ROME just like MEND.py in easyeditor/trainer/algs?

**Comment by zxlzr** [comment]
Hi, do you have further questions?

**Comment by yaohui120** [comment]
No, thank you for your answer.
