### ISSUE TITLE
Support Mistral-7b

### ISSUE THREAD

**Issue by cmnfriend** [zjunlp/EasyEdit#139]
Hi, will you support ROME for Mistral-7b-v1.0? Or can you give some suggestions for hparams? Thank you! :)

**Comment by PrakharSaxena24** [comment]
Haha! Thanks, I was also wondering about the same issue

**Comment by littlefive5** [comment]
Hello, thanks for the advice and we will support Mistral.

**Comment by xzwyyd** [comment]
Hello! Currently, we have preliminary support for Mistral. As the model is relatively new, we recommend updating your `transformers` version to version 4.34.0. You can do this by using the following code: `pip install transformers==4.34.0`. Please feel free to give it a try, and if you encounter any issues, don't hesitate to reach out to us. We are here to assist you at any time.

**Comment by XeeKee** [comment]
We will consider adding this before February.

**Comment by PrakharSaxena24** [comment]
Thank you for your work again. 
Can you also please add support for MEMIT for Mistral-7b? 
I tried ROME, it works nicely, now I want to do the same using MEMIT?

**Comment by xzwyyd** [comment]
Hello, we appreciate your interest! We've made some initial progress in supporting MEMIT. Please feel free to give it a try, and don't hesitate to reach out if you have any questions. We're here to assist you at any time.

**Comment by PrakharSaxena24** [comment]
Thank you very much!!

I have  a question, If I have a Mistral model, fine tuned on another language(Japanese) and I want to use it to Edit Knowledge in that language, should I change the second_order_momentum database to  wiki.jp ?

**Comment by PrakharSaxena24** [comment]
Thank you for the quick response, very helpful! :)
