### ISSUE TITLE
pydantic.error_wrappers.ValidationError: 1 validation error for Utterance text   str type expected (type=type_error.str) when doing SFT of Mistral 7b

### ISSUE THREAD

**Issue by tamanna-mostafa** [zjunlp/EasyEdit#140]
I'm running supervised fine tuning of Mistral 7b model. The input data is a json file including a list of dictionaries, each formatted like this:
{"prefix": [<question>, <answer>], "system": null}

I'm running the sft commands in an EC2 env. First, I ran the sft with ~500 data, and it went fine, though the model apparently didn't learn anything.
Then, I added 10k more training data in the same format. The training started and completed for 10% and then it failed with this error:

```
. . .
File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Utterance
text
   str type expected (type=type_error.str)
. . .
```

I tried with different data files of different lengths (1k-16k), but all the time, am getting the same error.
Things I've already tried:

1. I prepare the data in csv (with 2 columns: 'question' and 'answer') on pandas and then convert the csv to json. I ensured that the values for each column is str by both running: `df['pref_answer'] = df['pref_answer'].astype("string")`
and adding` dtype='string'` to the pd.read_csv function.

2. I checked that my csv file has no NaN value, empty string, or float.
3. Since there are special character in the data file, I saved the csv in UTF-8 format.

I'm still getting the above error. Can anyone please help?

I did another exp:
- I ran the training on the first 500 data. It ran successfully.
- I ran another training on another set of 500 data (index 500-1000). It also ran successfully.
- Then I combined 500+500 and ran another training on this 1k data. And the training failed with the same pydanctic validation error message: 
`pydantic.error_wrappers.ValidationError: 1 validation error for Utterance text str type expected (type=type_error.str)`

I find it bizarre that it's a size issue. Any insight?

**Comment by zxlzr** [comment]
Sorry, I am confused with your questions. Could your please detail your running script in EasyEdit? This tool is used for knowledge editing for LLMs rather than SFT.

**Comment by zxlzr** [comment]
hi, could you please detail your issue?

**Comment by zxlzr** [comment]
Hi, have you solved your issue?

**Comment by tamanna-mostafa** [comment]
I bypassed the issue by disabling pydantic validation in the config file to unblock myself, but could not actually solve the issue.

**Comment by pengzju** [comment]
This tool is used for model editing in LLM and is dedicated to correcting misperceptions within the model. Is your issue message for another repository?

**Comment by zxlzr** [comment]
hi buddy, have your issue solved?

**Comment by tamanna-mostafa** [comment]
Not yet solved

**Comment by littlefive5** [comment]
Could you please detail your issue?
