### ISSUE TITLE
About the data format of WikiBio

### ISSUE THREAD

**Issue by YJiangcm** [zjunlp/EasyEdit#141]
Hi, I downloaded the WikiBio dataset from https://huggingface.co/datasets/zjunlp/KnowEdit and found that the data format is different from other datasets such as ZsRE, as the following shows.

```
[
    {
        "text": "This is a Wikipedia passage about tim finchem. ",
        "labels": "Timothy W. Finchem (born April 19, 1947) is the current Commissioner of Golf's PGA Tour.",
        "concept": "tim finchem",
        "locality": {
            "Relation_Specificity": [
                {
                    "prompt": "The educated at of tim finchem is",
                    "ground_truth": [
                        "University of Richmond"
                    ]
                },
                {
                    "prompt": "tim finchem educated at",
                    "ground_truth": [
                        "University of Richmond"
                    ]
                }
            ]
        }
    },
]
```

Therefore, I cannot run [run_knowedit_llama2.py](https://github.com/zjunlp/EasyEdit/blob/main/examples/run_knowedit_llama2.py) with WikiBio correctly. May I know what are the "text" and "label" mean? Thanks a lot.

**Comment by XeeKee** [comment]
In KnowEditDataset class, we have already translate the format.Did you choose the  'wikibio' as your datatype?
 you can think 'text' as prompt , 'label' as 'ground_truth'

**Comment by YJiangcm** [comment]
Thank you for your answer.
