### ISSUE TITLE
SanitizationTrainDataset class missed

### ISSUE THREAD

**Issue by wutaiqiang** [zjunlp/EasyEdit#142]
> from easyeditor import SanitizationTrainDataset
> ImportError: cannot import name 'SanitizationTrainDataset' from 'easyeditor'

Seems that the SanitizationTrainDataset class is not defined.

**Comment by XeeKee** [comment]
I'm very sorry that we forgot to upload the SanitizationTrainDataset class earlier. You can now pull the code again.

**Comment by zxlzr** [comment]
hi buddy, we are very busy for the DDL, the reply to the issue may not be timely enough, I'm very sorry.

**Comment by XeeKee** [comment]
Please let me know if you have any other questions.

**Comment by zxlzr** [comment]
Hi, do you have any further questions?
