### ISSUE TITLE
About running IKE on Llama2

### ISSUE THREAD

**Issue by yaohui120** [zjunlp/EasyEdit#143]
Does the function editor.edit_dataset() support the IKE method? I found it'll be changed a lot to run.

**Comment by XeeKee** [comment]
Sorry we do not support editor.edit_dataset() for IKE. But after parsing the data, you can pass it into the corresponding parameters for editor.edit(), it is also simple.

**Comment by XeeKee** [comment]
We plan to have editor.edit_dataset() support IKE before February.

**Comment by yaohui120** [comment]
OK,I'll use function edit() instead. Thanks.
