### ISSUE TITLE
bug in run_convsent_llama2

### ISSUE THREAD

**Issue by wutaiqiang** [zjunlp/EasyEdit#144]
When running run_convsent_llama2 on convsent dataset, there is an error:

 Traceback (most recent call last):
    es = [metric["es"] for metric in metrics]
KeyError: 'es'

seems that there are no "es" "dd" and  "fluency" in metrics.

**Comment by XeeKee** [comment]
You can directly delete those lines of code. They were debugging code that we used for further analysis earlier, and I apologize for any inconvenience they may have caused you.

**Comment by wutaiqiang** [comment]
If I add "test_generation = True" in editor.edit() function in  run_convsent_llama2, It works but seems to be very slow as the decode process is slow.

**Comment by wutaiqiang** [comment]
Thanks~
