### ISSUE TITLE
Confusion about arguments of FT-L

### ISSUE THREAD

**Issue by wang-debug** [zjunlp/EasyEdit#145]
Hi, thank you for your excellent work. I have a question regarding the specifics of layer fine-tuning (FT-L). How is the number of layers to be fine-tuned determined? I noticed it was mentioned in your[ survey](https://arxiv.org/pdf/2305.13172.pdf) as `we employed methodology proposed by Meng et al. (2022), fine-tuning layers identified by ROME and we denoted it as FT-L.`,  but could you please clarify how exactly this is ascertained?

**Comment by littlefive5** [comment]
Hello,  ROME's paper has already elaborated on their methods for selecting layers for FT in Appendix E. 
They conducted a hyperparameter search based on randomly-sampled subsets of data. I recommend you resort to the original paper.

**Comment by wang-debug** [comment]
Ok, thank you for your response!
