### ISSUE TITLE
About the locality metric in Run_convsent_llama2

### ISSUE THREAD

**Issue by wutaiqiang** [zjunlp/EasyEdit#147]
Hello, after running the code, I found that in Run_convsent_llama2, the locality is always None.

Such as:

 > "pre": {
            "rewrite_acc": [
                0.3333333333333333
            ],
            "portability": {}
        },
        "case_id": 0,
        "requested_rewrite": {
            "prompt": "From the sentiment dataset, answer What is your sentiment of Estero? negatively.",
            "target_new": " Well, it has some bad reviews on Glass Door. ",
            "ground_truth": "<|endoftext|>",
            "portability": {},
            "locality": {},
            "subject": "Estero"
        },
        "time": 2.6119914054870605,
        "post": {
            "rewrite_acc": [
                0.4
            ],
            "locality": {},
            "portability": {}
        }

Only ACC is calculated. 

After reading the code, 

https://github.com/zjunlp/EasyEdit/blob/e5397ef4a062dbf36ee521537f4e8a8401e88681/examples/run_convsent_llama2.py#L159

shows that the locality data is not used.

**Comment by zxlzr** [comment]
Sorry, we will review the code and fix your issue ASAP.  ps. recently we are running DDLs, apologies for any delayed responses.

**Comment by wutaiqiang** [comment]
Thanks for your effort~. BTW, the paper reports the locality as 0. It might not be accurate.

<img width="818" alt="image" src="https://github.com/zjunlp/EasyEdit/assets/28387419/6dea6a24-b358-4d2d-a6e7-2f34723376e7">

Anyway, nice work and a great framework~

**Comment by zxlzr** [comment]
> Thanks for your effort~. BTW, the paper reports the locality as 0. It might not be accurate.
> 
> <img alt="image" width="818" src="https://private-user-images.githubusercontent.com/28387419/297236800-6dea6a24-b358-4d2d-a6e7-2f34723376e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NTcxMjAsIm5iZiI6MTcwNTQ1NjgyMCwicGF0aCI6Ii8yODM4NzQxOS8yOTcyMzY4MDAtNmRlYTZhMjQtYjM1OC00ZDJkLWE2ZTctMmYzNDcyMzM3NmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAyMDAyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjYzY2MTJiZjhlMmM0NWExNDQwMGYxOTJhOWViZDlkNjIwNzk0NmIwZmQ5YzE0NTI0NTFiNjYyYmZhMzBlYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9xebKcDQ1QJuP-qJbwWG2yMJ8tWhIFWnsa6kLuSUxRM">
> Anyway, nice work and a great framework~

Thanks, we will re-run and check the results asap.

**Comment by wutaiqiang** [comment]
I see, the locality and acc are defined in https://github.com/zjunlp/EasyEdit/blob/32c9b71ef2a47b3b03ac655be6b7a7cd90d37c18/easyeditor/evaluate/evaluate.py#L585

Just add the metric in mhttps://github.com/zjunlp/EasyEdit/blob/32c9b71ef2a47b3b03ac655be6b7a7cd90d37c18/easyeditor/editors/editor.py#L272 would work

**Comment by littlefive5** [comment]
Thanks for pointing out the problem again.
