### ISSUE TITLE
One bug for “examples/run_knowedit_llama2.py”

### ISSUE THREAD

**Issue by wutaiqiang** [zjunlp/EasyEdit#151]
locality_inputs and portability_inputs only load the data for the first sample while prompts and target_new are the data of dataset.

**Comment by XeeKee** [comment]
This is not a bug. EasyEdit was originally designed to accept only one input at a time. We will optimize EasyEdit as a whole when we have time in the future.

**Comment by wutaiqiang** [comment]
Thanks~
