### ISSUE TITLE
Question about the function edit_dataset in EasyEdit-main/easyeditor/editors/editor.py

### ISSUE THREAD

**Issue by yaohui120** [zjunlp/EasyEdit#152]
I found that the function always return the result of last batch data. I don't know if it's a bug or something I misunderstand.
```
        for record_chunks in tqdm(self._chunks(ds, num_edits), desc='Editing dataset', total=len(ds)/num_edits):
            ...

            all_metrics = [] # Here
            for i, request in enumerate(record_chunks):

                metrics = {...}
                all_metrics.append(metrics)

            ...

            for i, request in enumerate(record_chunks):
                all_metrics[i]["pre"] = compute_edit_quality(...)

            ...
        return all_metrics, edited_model, weights_copy
```

**Comment by littlefive5** [comment]
Hello, thanks for point out the bug here, we would fix it as soon as possible.

**Comment by XeeKee** [comment]
Hello, the standard setting for model editing usually starts from the same model each time. If editing is done sequentially from a model that has already been edited, you may want to carefully review the papers or overview introductions for more details. If you wish to perform sequential editing, you can set copy to false. This way, each time self.model is passed in, it will be the model that has been edited, and the modifications will be applied directly to the reference of self.model.

**Comment by littlefive5** [comment]
I have fixed this bug, thanks again.
