### ISSUE TITLE
Error when Running IKE for Wiki Counterfactual dataset

### ISSUE THREAD

**Issue by msumitaml** [zjunlp/EasyEdit#157]
Hello,

When running 
python run_knowedit_llama2.py \
    --editing_method=IKE \
    --hparams_dir=../hparams/IKE/llama-7b \
    --data_dir=./data/test_cf.json \
    --datatype='counterfact'

I am getting the error 

File "/EasyEdit-main/examples/easyeditor/models/ike/util.py", line 15, in encode_ike_facts
    neighbors = train_data['locality_prompt']
KeyError: 'locality_prompt'

Should this part of the code be changed for the WikiCounterfactual data?

def encode_ike_facts(sentence_model: SentenceTransformer, ds: Dataset, hparams: IKEHyperParams):

    sentences = []
    for i, train_data in enumerate(ds):
        new_fact = train_data['prompt'] + ' ' + train_data['target_new']
        target_new = train_data['target_new']
        paraphrases = train_data['rephrase_prompt']
        neighbors = train_data['locality_prompt']
        neighbors_ans = train_data['locality_ground_truth']
        sentences.append(f"New Fact: {new_fact}\nPrompt: {new_fact}\n\n")
        sentences.append(f"New Fact: {new_fact}\nPrompt: {paraphrases} {target_new}\n\n")
        sentences.append(f"New Fact: {new_fact}\nPrompt: {neighbors} {neighbors_ans}\n\n")

    embeddings = sentence_model.encode(sentences)
    base_path = f'{hparams.results_dir}/{hparams.alg_name}/embedding'
    os.makedirs(base_path, exist_ok=True)
    safe_model_name = hparams.sentence_model_name.rsplit('/', 1)[-1]
    with open(f'{base_path}/{safe_model_name}_{type(ds).__name__}_{len(ds)}.pkl', "wb") as fOut:
        pickle.dump({'sentences': sentences, 'embeddings': embeddings}, fOut,
                    protocol=pickle.HIGHEST_PROTOCOL)

Please let me know how should we correct this error.

**Comment by littlefive5** [comment]
Hello, IKE currently does not support Wiki counterfact and Wiki recent datasets; we will update the code in the future.
Provisionally, I recommend you change the data format to build the train data memory for easy usage.

**Comment by XeeKee** [comment]
Just in your edit() function add one line code:

    metrics, edited_model, _ = editor.edit(
        prompts=prompts,
        target_new=target_new,
        subject=subjects,
        locality_inputs=locality_inputs,
        portability_inputs=portability_inputs,
        train_ds=datas,
        keep_original_weight=True
    )
you can also push newest code, we also fix it.

**Comment by msumitaml** [comment]
Hi, thank you for the guidance, but even if I add train_ds=datas, it gives the following error:
1) Is it because encode_ike_facts() is not called which actually writes the .pkl file (Error 1 shown below)? and 
2) should train_ds take the training data (train_cf.json) as input (datas is the test_cf.json file right since we are using 
python run_knowedit_llama2.py \
    --editing_method=IKE \
    --hparams_dir=../hparams/IKE/llama-7b \
    --data_dir=./data/test_cf.json \
    --datatype='counterfact'

Error 1
Traceback (most recent call last):
  File "EasyEdit-main/examples/run_knowedit_llama2.py", line 301, in <module>
    metrics, edited_model, _ = editor.edit(
  File "EasyEdit-main/examples/../easyeditor/editors/editor.py", line 221, in edit
    edited_model, weights_copy, icl_examples = self.model, {}, self.apply_algo(
  File "EasyEdit-main/examples/../easyeditor/models/ike/ike_main.py", line 31, in apply_ike_to_model
    with open(f'{hparams.results_dir}/{hparams.alg_name}/embedding/'
FileNotFoundError: [Errno 2] No such file or directory: 'EasyEdit-main/examples/results/IKE/embedding/all-MiniLM-L6-v2_KnowEditDataset_2.pkl'

**Comment by XeeKee** [comment]
1. Yes,you should call encode_ike_facts() to get **all-MiniLM-L6-v2_KnowEditDataset_2.pkl**
2. encode_ike_facts() stores the knowledge you previously edited, while the editor inputs the knowledge you currently need to edit.

**Comment by msumitaml** [comment]
So how do we solve this error? Since run_knowedit_llama2.py does not call encode_ike_facts(). Is this a bug?

**Error** 
Traceback (most recent call last):
File "EasyEdit-main/examples/run_knowedit_llama2.py", line 301, in
metrics, edited_model, _ = editor.edit(
File "EasyEdit-main/examples/../easyeditor/editors/editor.py", line 221, in edit
edited_model, weights_copy, icl_examples = self.model, {}, self.apply_algo(
File "EasyEdit-main/examples/../easyeditor/models/ike/ike_main.py", line 31, in apply_ike_to_model
with open(f'{hparams.results_dir}/{hparams.alg_name}/embedding/'
FileNotFoundError: [Errno 2] No such file or directory: 'EasyEdit-main/examples/results/IKE/embedding/all-MiniLM-L6-v2_KnowEditDataset_2.pkl'

**Comment by littlefive5** [comment]
We haven't tested wiki_counterfact in IKE in our previous experiments, so it has some problems.
I am working to improve this part and will let you know when it's up!
Provisionally, you can refer to run_zsre_llama.py and try to add encode_ike_facts(), good luck!

**Comment by XeeKee** [comment]
Now we have support IKE method for KnowEdit.Just pull the newest code, and use the code below for generate your own all-MiniLM-L6-v2_KnowEditDataset_2.pkl,and do not forget change your hparam about  'sentence_model_name' to load right all-MiniLM-L6-v2_KnowEditDataset_2.pkl
```
from easyeditor import  IKEHyperParams
from easyeditor import KnowEditDataset
from easyeditor.models.ike import encode_ike_facts
from sentence_transformers import SentenceTransformer  
    

hparams = IKEHyperParams.from_hparams('./hparams/IKE/llama-7b.yaml')
train_ds = KnowEditDataset('/mnt/16t/xzk/EasyEdit/data/wiki_counterfact/test_cf.json')
sentence_model = SentenceTransformer(hparams.sentence_model_name).to(f'cuda:{hparams.device}')
encode_ike_facts(sentence_model, train_ds, hparams)
```

**Comment by msumitaml** [comment]
Hi thank you for the update. IKE is now working for Llama2-7b on Wiki Counterfactual dataset but it does not work with GPT2-XL and GPTJ-6B. It produces the following error:

File "/EasyEdit-main/examples/run_knowedit_llama2.py", line 192, in <module>
    metrics, edited_model, _ = editor.edit(
  File "/EasyEdit-main/examples/../easyeditor/editors/editor.py", line 207, in edit
    "pre": compute_icl_edit_quality(self.model, self.model_name, self.hparams, self.tok, [''],
  File "/EasyEdit-main/examples/../easyeditor/evaluate/evaluate.py", line 190, in compute_icl_edit_quality
    pre_neighbor = icl_lm_eval(model, model_name, hparams, tok, [''], record['locality'][locality_key]['ground_truth'],
  File "/EasyEdit-main/examples/../easyeditor/evaluate/evaluate.py", line 249, in icl_lm_eval
    target_ids = tokenizer(' ' + target + '\n', return_tensors='pt')['input_ids'].to(device)
TypeError: can only concatenate str (not "list") to str

**Comment by littlefive5** [comment]
Now it supports IKE to edit WikiCounterFact, pull the latest code, and try again.
You need to use the training data (train_cf.json) to build the store and I added a new argument train_data_path here.

**Comment by msumitaml** [comment]
Thank you, it's working now.
