### ISSUE TITLE
[Feature Request] Support InternLM

### ISSUE THREAD

**Issue by vansinhu** [zjunlp/EasyEdit#16]
Dear EasyEdit developer,

Greetings! I am vansinhu, a community developer and volunteer at InternLM. Your work has been immensely beneficial to me, and I believe it can be effectively utilized in InternLM as well. Welcome to add Discord https://discord.gg/gF9ezcmtM3 . I hope to get in touch with you.

Best regards,
vansinhu

**Comment by pengzju** [comment]
> Dear EasyEdit developer,
> 
> Greetings! I am vansinhu, a community developer and volunteer at InternLM. Your work has been immensely beneficial to me, and I believe it can be effectively utilized in InternLM as well. Welcome to add Discord https://discord.gg/gF9ezcmtM3 . I hope to get in touch with you.
> 
> Best regards, vansinhu

  Dear vansinhu,
  
  I'm glad to hear that you find our work beneficial, and I appreciate your interest in integrating EasyEdit into InternLM. I will 
  add your WeChat soon and talk to you

**Comment by pengzju** [comment]
If your problem has been resolved, please help close this issue.

**Comment by invisifire** [comment]
俩中国人，我的建议是用英文交流

**Comment by zxlzr** [comment]
Hi, EasyEdit now has supported InternLM. If you have any problems, please contact us.
