### ISSUE TITLE
Full datasets loading fix

### ISSUE THREAD

**Issue by whitepapercg** [zjunlp/EasyEdit#161]
Regards, can you exclude downloading datasets of 18+gb if only small parts of them are used (as I understood about 300mb). Wikipedia and other datasets that are downloaded, not sure if they are all needed in full.

**Comment by littlefive5** [comment]
Hello, here we just download the Wikipedia datasets and sample some data, but you need to download the whole datasets to conduct the sampling.
I currently have no idea how to optimize it and if you have any concrete suggestions, I am happy to do it.
