### ISSUE TITLE
There is a question about 'edited_model' in easyeditor/editor.py, why edit() function always return the last edited_model only?

### ISSUE THREAD

**Issue by How-Fun** [zjunlp/EasyEdit#162]
`        在[EasyEdit](https://github.com/zjunlp/EasyEdit/tree/main)/[easyeditor](https://github.com/zjunlp/EasyEdit/tree/main/easyeditor)/[editors](https://github.com/zjunlp/EasyEdit/tree/main/easyeditor/editors)/editor.py文件的edit()函数中（具体为252行代码），进行了一次迭代，在迭代过程中对原模型self.model进行了一次编辑，将返回赋给了edited_model。但是，edit()函数最后的返回'edited_model'仅仅包含了最后一次模型编辑的结果。我认为迭代的过程中，模型编辑应当以上一次编辑的结果edited_model为目标再次进行编辑，但是代码似乎不是这样。
我不明白编辑算法是否对self.model进行了修改，这段关键代码是bug还是自有道理？万分疑惑，感谢解答。

        def edit(**args):
            ...

            for i, request in tqdm(enumerate(requests)):
                ...
                edited_model, weights_copy = self.apply_algo(
                    ...,
                    self.model,                     # here
                    ...,
                )
            ...
        return all_metrics, edited_model, weights_copy`

**Comment by How-Fun** [comment]
之前有人提过类似的问题 https://github.com/zjunlp/EasyEdit/issues/152 ，如果真是bug可能会导致非常严重的错误。

**Comment by zxlzr** [comment]
您好，模型编辑常规设定每次都是从同一个模型开始编辑的，如果从编辑好的模型再次编辑是sequential设定，您可以仔细看下论文或综述介绍。

**Comment by XeeKee** [comment]
如果您想做sequential编辑，您可以将copy设置为false，这样每次传入的self.model就是编辑后的模型，修改的是self.model的引用

**Comment by zxlzr** [comment]
Do you have any other questions?

**Comment by littlefive5** [comment]
如果您想做sequential编辑，您需要将keep_original_weight的参数设置为False，
https://github.com/zjunlp/EasyEdit/blob/main/easyeditor/editors/editor.py#L123

如果keep_original_weight为True的话，我们在每次编辑之后，会根据weights_copy恢复成original的model：
https://github.com/zjunlp/EasyEdit/blob/main/easyeditor/editors/editor.py#L274C16-L283C108
而当keep_original_weight为False时，apply_algo返回的weights_copy是空值，则会保留上一次编辑的模型。

在我们默认的copy=False (https://github.com/zjunlp/EasyEdit/blob/main/easyeditor/editors/editor.py#L227)的情况下，edited_model是self.model的引用，两个地方指向的位置是同一个。
如果你不希望self.model被修改的话，你需要将copy设置为True，我们暂时不推荐这种做法，因为这需要额外开辟内存空间，这会使得您的计算开销增加。
