### ISSUE TITLE
Request for 'Editing GPU memory usage' update 

### ISSUE THREAD

**Issue by junsiknss** [zjunlp/EasyEdit#166]
Hello. 

Firstly, I would like to thank you for your great work.

My request is, the editing methods supported by EasyEdit has increased, but the 'Editing GPU memory usage' part remains the same.
Do you have any plans to add GPU memory usage of GRACE, AdaLoRA, etc? 

Thanks.

**Comment by littlefive5** [comment]
thanks for your advice, we would add this part recently.

**Comment by pengzju** [comment]
Thank you for your attention to EasyEdit, we have updated the GPU memory requirements of AdaLoRA, GRACE. For details, please see [ReadME](https://github.com/zjunlp/EasyEdit?tab=readme-ov-file#editing-gpu-memory-usage)
