### ISSUE TITLE
MEMIT方法是否能使每次的权重更新相同（在代码完全一致的情况下）

### ISSUE THREAD

**Issue by cmnfriend** [zjunlp/EasyEdit#168]
第一遍跑的log：
`MEMIT request sample: [What are the ways to create malware?] -> [ Stop doing that]
Computing right vector (v)
Lookup index found: 8 | Sentence: What are the ways to create malware?Stop doing | Token: ware
Rewrite layer is 8
Tying optimization objective to 31
Recording initial value of v*
loss 5.722 = 5.722 + 0.0 + 0.0 avg prob of [ Stop doing that] 0.0036612343974411488
loss 3.214 = 2.934 + 0.281 + 0.0 avg prob of [ Stop doing that] 0.05542665347456932
loss 1.149 = 0.898 + 0.251 + 0.0 avg prob of [ Stop doing that] 0.41335150599479675
loss 0.48 = 0.304 + 0.176 + 0.0 avg prob of [ Stop doing that] 0.7390558123588562
loss 0.324 = 0.039 + 0.285 + 0.0 avg prob of [ Stop doing that] 0.9621119499206543
loss 0.317 = 0.025 + 0.291 + 0.0 avg prob of [ Stop doing that] 0.974921703338623
loss 0.311 = 0.021 + 0.29 + 0.0 avg prob of [ Stop doing that] 0.9794000387191772
loss 0.302 = 0.007 + 0.296 + 0.0 avg prob of [ Stop doing that] 0.9933974742889404
loss 0.299 = 0.004 + 0.294 + 0.0 avg prob of [ Stop doing that] 0.9957550764083862
loss 0.291 = 0.007 + 0.284 + 0.0 avg prob of [ Stop doing that] 0.992832362651825
loss 0.289 = 0.007 + 0.282 + 0.0 avg prob of [ Stop doing that] 0.9931871891021729
loss 0.289 = 0.002 + 0.286 + 0.0 avg prob of [ Stop doing that] 0.9976776838302612
loss 0.279 = 0.003 + 0.276 + 0.0 avg prob of [ Stop doing that] 0.996989905834198
loss 0.289 = 0.009 + 0.281 + 0.0 avg prob of [ Stop doing that] 0.9914276003837585
loss 0.308 = 0.001 + 0.307 + 0.0 avg prob of [ Stop doing that] 0.9993019104003906
loss 0.315 = 0.0 + 0.314 + 0.0 avg prob of [ Stop doing that] 0.9995386600494385
loss 0.316 = 0.0 + 0.315 + 0.0 avg prob of [ Stop doing that] 0.9995665550231934
loss 0.316 = 0.0 + 0.315 + 0.0 avg prob of [ Stop doing that] 0.9995471835136414
loss 0.316 = 0.0 + 0.315 + 0.0 avg prob of [ Stop doing that] 0.9995115995407104
loss 0.316 = 0.001 + 0.315 + 0.0 avg prob of [ Stop doing that] 0.9994749426841736
loss 0.316 = 0.001 + 0.315 + 0.0 avg prob of [ Stop doing that] 0.9994462728500366
loss 0.316 = 0.001 + 0.315 + 0.0 avg prob of [ Stop doing that] 0.9994303584098816
loss 0.316 = 0.001 + 0.315 + 0.0 avg prob of [ Stop doing that] 0.9994286894798279
loss 0.316 = 0.001 + 0.315 + 0.0 avg prob of [ Stop doing that] 0.99944007396698
loss 0.316 = 0.001 + 0.315 + 0.0 avg prob of [ Stop doing that] 0.9994620680809021
Init norm 16.91368293762207 | Delta norm 67.65473175048828 | Target norm 71.54158020019531`

第二遍log：
`MEMIT request sample: [What are the ways to create malware?] -> [ Stop doing that]
Computing right vector (v)
Lookup index found: 8 | Sentence: What are the ways to create malware?Stop doing | Token: ware
Rewrite layer is 8
Tying optimization objective to 31
Recording initial value of v*
loss 5.789 = 5.789 + 0.0 + 0.0 avg prob of [ Stop doing that] 0.003556783776730299
loss 3.504 = 3.265 + 0.239 + 0.0 avg prob of [ Stop doing that] 0.039322733879089355
loss 1.289 = 1.026 + 0.263 + 0.0 avg prob of [ Stop doing that] 0.36120301485061646
loss 2.028 = 1.752 + 0.275 + 0.0 avg prob of [ Stop doing that] 0.18723516166210175
loss 0.381 = 0.047 + 0.334 + 0.0 avg prob of [ Stop doing that] 0.9544105529785156
loss 0.332 = 0.024 + 0.308 + 0.0 avg prob of [ Stop doing that] 0.9765142202377319
loss 0.344 = 0.036 + 0.309 + 0.0 avg prob of [ Stop doing that] 0.9650608897209167
loss 0.347 = 0.043 + 0.304 + 0.0 avg prob of [ Stop doing that] 0.9580222368240356
loss 0.338 = 0.041 + 0.297 + 0.0 avg prob of [ Stop doing that] 0.960117757320404
loss 0.32 = 0.033 + 0.287 + 0.0 avg prob of [ Stop doing that] 0.9672554731369019
loss 0.298 = 0.026 + 0.272 + 0.0 avg prob of [ Stop doing that] 0.9740294218063354
loss 0.27 = 0.021 + 0.249 + 0.0 avg prob of [ Stop doing that] 0.9795193672180176
loss 0.237 = 0.019 + 0.218 + 0.0 avg prob of [ Stop doing that] 0.981377124786377
loss 0.206 = 0.022 + 0.183 + 0.0 avg prob of [ Stop doing that] 0.9781100749969482
loss 0.183 = 0.023 + 0.16 + 0.0 avg prob of [ Stop doing that] 0.9769653081893921
loss 0.158 = 0.01 + 0.148 + 0.0 avg prob of [ Stop doing that] 0.989719569683075
loss 0.138 = 0.003 + 0.135 + 0.0 avg prob of [ Stop doing that] 0.9966888427734375
loss 0.128 = 0.002 + 0.126 + 0.0 avg prob of [ Stop doing that] 0.9976390600204468
loss 0.122 = 0.002 + 0.119 + 0.0 avg prob of [ Stop doing that] 0.9976732134819031
loss 0.114 = 0.002 + 0.111 + 0.0 avg prob of [ Stop doing that] 0.9979567527770996
loss 0.105 = 0.002 + 0.103 + 0.0 avg prob of [ Stop doing that] 0.998188853263855
loss 0.097 = 0.002 + 0.095 + 0.0 avg prob of [ Stop doing that] 0.9982585906982422
loss 0.092 = 0.002 + 0.09 + 0.0 avg prob of [ Stop doing that] 0.9982713460922241
loss 0.087 = 0.002 + 0.085 + 0.0 avg prob of [ Stop doing that] 0.9982983469963074
loss 0.084 = 0.002 + 0.082 + 0.0 avg prob of [ Stop doing that] 0.9983716011047363
Init norm 16.817096710205078 | Delta norm 67.26838684082031 | Target norm 72.25553131103516`

代码：
`hparams = MEMITHyperParams.from_hparams('xxx')
editor = BaseEditor.from_hparams(hparams)

prompts = [
    'xxx',
    'xxx',
    'xxx',
]

target_new = [
    'xxx, 
    'xxx', 
    'xxx'
]

subject = [
    'xxx',
    'xxx',
    'xxx'
]

metrics, edited_model, _ = editor.edit(
    prompts=prompts,
    target_new=target_new,
    subject=subject,
    keep_original_weight=False
)`

想知道在代码不变、初始模型也不变的情况下，每次编辑更新的权重是否有可能能够完全相同？

**Comment by littlefive5** [comment]
I tried again, and it's true that the current code generates different outputs.
You can set the seed and try again.
I will update the code and add the seed setting.

**Comment by cmnfriend** [comment]
Thank you very much:)

**Comment by cmnfriend** [comment]
Sorry, but may I ask where I should set the seed?😂 It doesn't seem to work if I add a `random.seed()` directly to the code I've showed.

**Comment by littlefive5** [comment]
Sorry for the late reply. I have added the seed in editor.py , you can try again.

**Comment by zxlzr** [comment]
Hi, do you have any further questions?

**Comment by cmnfriend** [comment]
No, thank you!
