### ISSUE TITLE
Pre-training for MEND

### ISSUE THREAD

**Issue by KechenQin** [zjunlp/EasyEdit#17]
Hello,

Thanks for the putting different model editing methods together. I have a question about the MEND pre-training.

I followed the Trainer tutorial to do pre-training for MEND, but I got stuck at step4. In step 4, when the program initializes the trainer, it calls:

`archive, config.archive = load_archive(str(config.archive))`

Based on step6, it seems that **archive** should be set to the path of the meta-network. However, when I am at step4, I am going to train the meta-network and I don't have the model yet. Then what should be the **archive** in the hparams file?

The Trainer tutorial jumps from step4 to step6 directly. I am wondering if step5 is missing? Besides, in step6, it says CHECKPOINT will be saved to RESULTS_DIR in global.yml. Can you please point me to the path of the global.yml file?

It would be very helpful if you can provide a notebook tutorial for MEND, including both pre-training and model editing!

Thanks!

**Comment by pengzju** [comment]
- Problem 1: If you want to utilize MEND to edit, you should follow the steps [here](https://github.com/zjunlp/EasyEdit#trainer)
    - It's a two-stage process, first training(get archive) and then editing(use archive).
    - During the TRAINING phase, you should use the yaml configuration in the TRAINING directory(such as [here](https://github.com/zjunlp/EasyEdit/blob/main/hparams/TRAINING/MEND/gpt-j-6B.yaml#L14)). The archive is set to `null`, it will skip the processing of `load_archive`
- Problem 2: Thanks for your correction, I will revise Step 6 to Step 5
- Problem 3: Thanks for your correction, in one update, I deleted global.yml. `checkpoint` is currently saved in the `results_dir` in the yaml configuration (like https://github.com/zjunlp/EasyEdit/blob/main/hparams/TRAINING/MEND/gpt-j-6B.yaml#L68)

**Comment by pengzju** [comment]
Thanks for reminding me, I'll provide sample scripts in README that utilize the Trainer

**Comment by pengzju** [comment]
I have updated the README. If this response resolves your problems, please help close this issue.

**Comment by KechenQin** [comment]
Thanks for the prompt reply! That solved the issue.
