### ISSUE TITLE
请问一下论文中提到的opencompass在评估时要用到吗

### ISSUE THREAD

**Issue by exxaid** [zjunlp/EasyEdit#170]
easyedit不是可以输出评估结果吗，为什么论文里说用opencompass做的评估？我是新手，不太懂，不好意思

**Comment by littlefive5** [comment]
我们采用opencompass是衡量编辑后的模型是否会影响其在其他task上的表现，比如MMLU，AGIeval。easyedit衡量的是模型在编辑特定知识下edit  success,locality,portability的表现，并不是特定的下游任务。

**Comment by exxaid** [comment]
明白了，感谢
