### ISSUE TITLE
T-Patcher support

### ISSUE THREAD

**Issue by YuJu0819** [zjunlp/EasyEdit#171]
I'm just curious where to find the T-Patcher implementation at here. It seems that it hasn't been done. Yet, the document says it is supported.

**Comment by pengzju** [comment]
Sorry, during our actual implementation process, we found that T-Patcher integration is difficult, so EasyEdit does not support T-Patcher. There are also relevant instructions in [ReadME](https://github.com/zjunlp/EasyEdit?tab=readme-ov-file#current-implementation)

**Comment by pengzju** [comment]
At the same time, we also welcome you to explore adding T-Patcher to EasyEdit and provide corresponding PR, etc. Thank you again for your attention.
