### ISSUE TITLE
Question about E-VQA

### ISSUE THREAD

**Issue by yaohui120** [zjunlp/EasyEdit#172]
In paper 《Can We Edit Multimodal Large Language Models?》, E-VQA is proposed as benchmark. I found that the nq questions of each training sample from E-VQA are either "mexican leader who was supported by..." or "where is the pause key on a dell laptop". Is this a bug? Or two questions are enough for quantifying the model’s stability?

**Comment by yaohui120** [comment]
Besides, what is batch['cond'] in MultimodalTrainer.py used for? I saw function edit in EasyEdit-main/easyeditor/trainer/algs/MEND.py and SERAC.py, the batch['cond'] is also not used.

**Comment by tbozhong** [comment]
Thanks for your attention to our work!

It's clarified that the `batch['cond']` in the source code of `MEND` is intended for Knowledge Editor (KE). Still, this part is not utilized since KE is not supported in EasyEdit's current implementation.

**Comment by tbozhong** [comment]
> In paper 《Can We Edit Multimodal Large Language Models?》, E-VQA is proposed as benchmark. I found that the nq questions of each training sample from E-VQA are either "mexican leader who was supported by..." or "where is the pause key on a dell laptop". Is this a bug? Or two questions are enough for quantifying the model’s stability?

This is a bug in the process of regenerating the dataset. Thank you for pointing it out, and it has now been updated.

**Comment by yaohui120** [comment]
OK, I will check the nq questions of VQA later.

**Comment by zxlzr** [comment]
Hi, do you have any further questions?

**Comment by yaohui120** [comment]
When I loaded pre-trained weight of bert-base-uncased, it said
'''
Some weights of the model checkpoint at hugging_cache/bert-base-uncased were not used when initializing BertLMHeadModel: ['bert.embeddings.token_type_embeddings.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias']

Some weights of BertLMHeadModel were not initialized from the model checkpoint at hugging_cache/bert-base-uncased and are newly initialized: ['bert.encoder.layer.10.crossattention.output.dense.weight...
'''
The weight I used is downloaded from 'https://huggingface.co/bert-base-uncased/tree/main'. Is it the same weight as you used?

**Comment by tbozhong** [comment]
Yes, we follow the steps outlined in LAVIS, utilizing Hugging Face's `bert-base-uncased`, and encounter the same warning.

**Comment by yaohui120** [comment]
Fine, thank you.
