### ISSUE TITLE
MELO fails to edit gpt2-xl

### ISSUE THREAD

**Issue by nrosen1** [zjunlp/EasyEdit#174]
![image](https://github.com/zjunlp/EasyEdit/assets/80773628/795f0a76-5e08-4546-b720-a8550a2047e6)
![image](https://github.com/zjunlp/EasyEdit/assets/80773628/a71afe9b-516c-4736-8a3a-8813a05bd5c8)

**Comment by nrosen1** [comment]
I saw that MELO repo uses t5-small-ssm-nq for zsre data, do you provide T5-small hparams as well?

**Comment by XeeKee** [comment]
you can try to set the Hparams :num_iter to 50

**Comment by XeeKee** [comment]
I do not support T5 model in EasyEdit.I will support it asap

**Comment by XeeKee** [comment]
In my local environment, melo performance well. I will debug to know what is going wrong asap.

**Comment by zxlzr** [comment]
Hi, have you solved your issue yet?

**Comment by zxlzr** [comment]
hi, do you have any further questions?
