### ISSUE TITLE
it seems there is an import bug

### ISSUE THREAD

**Issue by haoyuwangwhy** [zjunlp/EasyEdit#175]
I tried to run the script:
**python run_zsre_llama2.py    
     --editing_method=MEMIT    
     --hparams_dir=../hparams/MEMIT/llama-7b     
     --data_dir=./data**
I got the following error:
**ImportError: cannot import name 'MeloConfig' from 'peft'**

**Comment by XeeKee** [comment]
Recently, EasyEdit has added support for a new method called "melo," which requires a completely new package named peft_egg. If you don't need to conduct experiments related to melo, you can directly comment out this line of code: https://github.com/zjunlp/EasyEdit/blob/9d108f7fa766f68ad5a1cb152978c667fd4ebe6b/easyeditor/models/__init__.py#L9C1-L9C20

**Comment by XeeKee** [comment]
I've been testing the impact of peft_egg on other methods recently, so I suggest you comment out this section of code until I confirm it's error-free, then update the environment.

**Comment by XeeKee** [comment]
Hello, we have fixed this bug. Could you please pull the code again?

**Comment by zxlzr** [comment]
Hi, have you solved your issue yet?

**Comment by haoyuwangwhy** [comment]
> Hi, have you solved your issue yet?

It works now. Thanks for your help!
