### ISSUE TITLE
error when runing knowedit

### ISSUE THREAD

**Issue by haoyuwangwhy** [zjunlp/EasyEdit#176]
script used:
**python run_knowedit_llama2.py     
--editing_method=LoRA     
--hparams_dir=../hparams/LoRA/llama-7b     
--data_dir=./KnowEdit/benchmark_wiki_recent_recent_train.json 
--datatype='recent'**

error:
Traceback (most recent call last):
  File "***/run_knowedit_llama2.py", line 116, in <module>
    an = an[0]
IndexError: list index out of range

**Comment by zxlzr** [comment]
Sorry, we will check and help you asap.

**Comment by haoyuwangwhy** [comment]
> Sorry, we will check and help you asap.

Thanks! By the way, I find when I use benchmark_wiki_counterfact_train_cf.json dataset, I got the following error:
Traceback (most recent call last):
  File "/EasyEdit/examples/run_knowedit_llama2.py", line 211, in <module>
    metrics, edited_model, _ = editor.edit(
  File "/EasyEdit/examples/../easyeditor/editors/editor.py", line 233, in edit
    "pre": compute_edit_quality(self.model, self.model_name, self.hparams, self.tok, request,
  File "/EasyEdit/examples/../easyeditor/evaluate/evaluate.py", line 81, in compute_edit_quality
    compute_portability_quality(model, model_name, hparams, tok, portability_key,
  File "/EasyEdit/examples/../easyeditor/evaluate/portability_evaluate.py", line 24, in compute_portability_quality
    portability_correct = test_prediction_acc(model, tok, hparams, prompt, ground_truth, device)
  File "/EasyEdit/examples/../easyeditor/evaluate/evaluate_utils.py", line 85, in test_prediction_acc
    max_prompt_len = max([len(tok.encode(_)) for _ in prompt_target]) + 1
ValueError: max() arg is an empty sequence

**Comment by XeeKee** [comment]
if you are emergent，i suggest that you can just delete that data.I will fix this bug tonight.

**Comment by XeeKee** [comment]
：）Can you tell me where you get the data? I download the data from huggingface. I do not get any bug.
Can you provide more precise information so that I can assist you better?

**Comment by haoyuwangwhy** [comment]
> ：）Can you tell me where you get the data? I download the data from huggingface. I do not get any bug. Can you provide more precise information so that I can assist you better?

Thanks for your help! I find if I use datasets from Huggingface, it does not have bugs. However, the data from modelscope has this bug.

**Comment by XeeKee** [comment]
Yes, you need to use the script provided at https://github.com/zjunlp/EasyEdit/blob/main/examples/KnowEdit.md for evaluation.

**Comment by zxlzr** [comment]
Hi，do you have any further questions?
