### ISSUE TITLE
Where is the dataset `MMEDIT`?

### ISSUE THREAD

**Issue by smurf-1119** [zjunlp/EasyEdit#180]
Where is the dataset `MMEDIT` introduced by the paper "Can We Edit Multimodal Large Language Models?" ? Can you support some examples about it?

**Comment by zxlzr** [comment]
Sorry, MMEdit is here, we have updated the README.  If you have any issues please contact us.

<img width="858" alt="image" src="https://github.com/zjunlp/EasyEdit/assets/1264492/1333e384-b6b4-4a21-aeb0-87572d0f713c">

**Comment by smurf-1119** [comment]
Could you provide specific links for the following model weights? I’ve noticed that the models I downloaded don’t match the code you provided.

```
qformer_checkpoint: hugging_cache/blip2_pretrained_flant5xxl.pth
qformer_name_or_path: bert-base-uncased
state_dict_file: hugging_cache/eva_vit_g.pth
pretrained_ckpt: hugging_cache/pretrained_minigpt4_7b.pth
```

**Comment by tbozhong** [comment]
As for specific links of models, you can refer to issue #167 for details. And I will update README soon.
The link to images can be viewed at [here](https://github.com/zjunlp/EasyEdit#datasets-for-multimodal-knowledge-mmedit).

**Comment by zxlzr** [comment]
Hi, do you have any further questions?
