### ISSUE TITLE
error training LoRa

### ISSUE THREAD

**Issue by nrosen1** [zjunlp/EasyEdit#181]
after 70 epochs i get error:
```
outputs.loss += orth_reg_weight * regu_loss
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'Tensor'

```
![image](https://github.com/zjunlp/EasyEdit/assets/80773628/2db28512-a90f-4a61-b49e-7e1de3babb7b)
![image](https://github.com/zjunlp/EasyEdit/assets/80773628/59d0bb28-6ebe-4bec-8287-5d438dcf83e5)

**Comment by littlefive5** [comment]
We haven't ever met this problem; we would try to reproduce it and see what happened.

**Comment by nrosen1** [comment]
@littlefive5 thank you, did this error reproduced?

**Comment by nrosen1** [comment]
update: after reinstalling the environment (python=3.9.7 + requirements.txt) train was completed successfully
![image](https://github.com/zjunlp/EasyEdit/assets/80773628/1f09293e-40dd-4b80-8d0a-d9a753665623)
