### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by ssr123s** [zjunlp/EasyEdit#183]
Hello, I was using memit for editing, and while the editing part worked fine on 3 4090 GPUs, I encountered an out-of-memory error during the final validation process. I tried setting the parameters to device='auto', model_name=base_model_name, stats_dir='./data/stats', max_length=40, batch_size=1, model_parallel=True, but it was still ineffective. Is there any other solution?
<img width="771" alt="af0e332d922897b143f7418e2eafcbf" src="https://github.com/zjunlp/EasyEdit/assets/152489945/1cd8d5e8-4333-4578-9d97-2dfe16ef5bd6">

**Comment by pengzju** [comment]
This line of your code is incorrect:

- `model = LlaMAForCausalLM.from_pretrained(base_model_name).to('cuda')`
- You can replace it with `model = LlaMAForCausalLM.from_pretrained(base_model_name, device_map='auto')`

And make sure that the GPU where the **batch** is located is the same as the GPU where **model layer0** is located.

**Comment by zxlzr** [comment]
hi, have you solved your issue?

**Comment by ssr123s** [comment]
Thank you very much for your advice and concern. Currently, I don't have computational resources. I will provide feedback as soon as there are any results.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月29日(星期四) 上午10:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zjunlp/EasyEdit] out of memory (Issue #183)





 
hi, have you solved your issue?

**Comment by zxlzr** [comment]
Hi, have you solved your issue?

**Comment by ssr123s** [comment]
&nbsp;I'm very sorry, but I currently still lack computing resources. However, there's another issue that bothers me. In the notebook example you provided, after editing one entry, I need to restart the kernel by hand to edit a second one. Is there a way to use a for loop to automatically edit multiple entries?I'm extremely grateful for your answer.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月2日(星期六) 晚上10:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zjunlp/EasyEdit] out of memory (Issue #183)





 
Hi, have you solved your issue?
