### ISSUE TITLE
KN out of memory

### ISSUE THREAD

**Issue by wpwpwpyo** [zjunlp/EasyEdit#184]
您好，使用该框架时我遇到一些问题：使用A100 82GB，在examples下运行run_zsre_llama2.py的KN方法，加载的模型是llama-2-7b-chat-hf，在Getting coarse neurons for each prompt...阶段会出现out of memory错误，如下所示：
![image](https://github.com/zjunlp/EasyEdit/assets/49509792/8819782b-08bb-422c-ac18-24f961871362)
运行指令：
![image](https://github.com/zjunlp/EasyEdit/assets/49509792/a701da34-e69e-4cc5-884d-2d73b8e0e715)
请问为什么会出现out of memory？

**Comment by pengzju** [comment]
If you encounter other problems, you can leave a message at any time, thank you for your attention

**Comment by zxlzr** [comment]
hi, have you solved your issue?
