### ISSUE TITLE
question about sequential edit using SERAC

### ISSUE THREAD

**Issue by qitianyuu** [zjunlp/EasyEdit#185]
Hi, I have some questions about sequential edit using SERAC

I set `keep_original_weight` to `False` for sequential editing, but I noticed that `self.alg.cache_inputs` always has one item during editing.

https://github.com/zjunlp/EasyEdit/issues/32#issuecomment-1734778867

for code,
https://github.com/zjunlp/EasyEdit/blob/13dd1e07812d6ad55578bed0510a67e4b2e594a2/easyeditor/models/serac/serac_main.py#L165
line 165 return `new_model` and `new_model.cache_inputs` add new edit item and keep edited items
but `new_model.cache_inputs`  didn't update to `self.alg.cache_inputs`

i try to add some code here
https://github.com/zjunlp/EasyEdit/blob/13dd1e07812d6ad55578bed0510a67e4b2e594a2/easyeditor/models/serac/serac_main.py#L196

```
  if keep_original_weight:
      self.alg.cache_labels = self.alg.cache_labels[-1:]
      self.alg.cache_inputs = self.alg.cache_inputs[-1:]
  else:
      self.alg = new_model
      self.alg.replacement.to(torch.device(f'cuda:{self.params.device}'))
      self.alg.classifier.to(torch.device(f'cuda:{self.params.device}'))
      gc.collect()
      torch.cuda.empty_cache()
```
After adding the code, I found that sequential editing works fine.

btw, someone in the issue encountered an OOM problem. I found that adding the following code after editing can solve the OOM problem.
```
gc.collect()
torch.cuda.empty_cache()
```

Please check if this is a problem

looking forward to your reply, thank you!

**Comment by pengzju** [comment]
- Thank you for your attention, what you mentioned is indeed a current defect. An your code is correct.

> 
```python
      self.alg = new_model
      self.alg.replacement.to(torch.device(f'cuda:{self.params.device}'))
      self.alg.classifier.to(torch.device(f'cuda:{self.params.device}'))
      gc.collect()
      torch.cuda.empty_cache()
```

- OOM comes from when [calculating embedding similarity](https://github.com/zjunlp/EasyEdit/blob/main/easyeditor/trainer/algs/SERAC.py#L178), serac calculates all embeddings in one batch, so it will cause OOM after nearly a hundred edits. This is a problem with serac's original code. We will improve this part as soon as possible, thank you for your attention
- At the same time, I also recommend that you explore this feature. You are welcome to provide the corresponding PR.

**Comment by zxlzr** [comment]
hi, have you solved your issue？
