### ISSUE TITLE
About the implement of MEMIT

### ISSUE THREAD

**Issue by Luoyang144** [zjunlp/EasyEdit#190]
Hi, I'm using easyedit to edit LLM. But the implement of MEMIT may not be batched? Here is the [code](https://github.com/zjunlp/EasyEdit/blob/d994bb90502727dea99ea5a12ba8b4173870950a/easyeditor/models/memit/memit_main.py#L115).
<img width="707" alt="image" src="https://github.com/zjunlp/EasyEdit/assets/63402979/2e9a438e-f3bd-4b78-a8db-df22c436c346">
One of the advantages of MEMIT is that it can update knowledge in batches. Are there any problems with this implementation?

**Comment by pengzju** [comment]
The concept of batch in MEMIT should be equivalent to the accumulation of edits. You can refer to it [here](https://github.com/kmeng01/memit/blob/main/memit/memit_main.py#L104). We follow the original settings of memit.

**Comment by pengzju** [comment]
If you encounter other problems, you can leave a message at any time, thank you for your attention

**Comment by zxlzr** [comment]
Hi, do you have any further questions?
