### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by waltonfuture** [zjunlp/EasyEdit#191]
作者您好！我想问一下，比如我要基于一个预训练模型做一个垂直领域大模型。我构造了一个领域知识数据集。用领域知识对模型进行知识编辑与用领域知识直接监督微调模型有什么差别吗？两种方法更推荐哪个呢？

**Comment by zxlzr** [comment]
您好，知识编辑和领域大模型本质上是2个概念，领域大模型需要的是对通用大模型做领域知识增强；知识编辑的目的是通过轻量的修改大模型知识的支持实现缓解大模型的知识缺失、谬误或擦除不安全及隐式知识等信息。知识编辑可以做知识增强，但仅限于小批量，因为编辑是细粒度精细化操作。领域知识增强更建议直接领域预训练或检索增强。
