### ISSUE TITLE
can't edit using for cycle

### ISSUE THREAD

**Issue by ssr123s** [zjunlp/EasyEdit#192]
When I was using the notebook example provided by EasyEdit for a simple edit, Rome showed good performance. However, when I used deep copy to copy the model to the GPU in each cycle, performed edits, and then deleted the model after editing, the performance was very poor. This is the source code. Could you please tell me the reason?
[easyedit.txt](https://github.com/zjunlp/EasyEdit/files/14472349/easyedit.txt)

**Comment by littlefive5** [comment]
Seems weird. 
```
editor=BaseEditor.from_hparams(hparams, model=model_for_edit, tokenizer=tokenizer)
```

How do you initialize the model in the editor, since our code does not send the model directly. 
Maybe you can share it.

**Comment by ssr123s** [comment]
I made only one change, which is to comment out the 'from pretrain' operation in editor.py and instead pass the model through parameters.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yunzhi ***@***.***&gt;; 
发送时间: 2024年3月4日(星期一) 上午10:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zjunlp/EasyEdit] can&#39;t edit using for cycle (Issue #192)





 
Seems weird.
 editor=BaseEditor.from_hparams(hparams, model=model_for_edit, tokenizer=tokenizer)  
How do you initialize the model in the editor, since our code does not send the model directly.
 Maybe you can share it.

**Comment by ssr123s** [comment]
a good advice
