### ISSUE TITLE
Text and Image locality in Multimodal Edit

### ISSUE THREAD

**Issue by hanhuang22** [zjunlp/EasyEdit#195]
Hi, i've noticed a difference in text and image locality: the topk takes k=1 for text but k=10 for image. 
https://github.com/zjunlp/EasyEdit/blob/e877591117e482116482d0a7966e2b9211af117c/easyeditor/trainer/MultimodalTrainer.py#L156-L162
Then in the following, image loc calculates if top 10 indices match one by one, which is not easy.
https://github.com/zjunlp/EasyEdit/blob/e877591117e482116482d0a7966e2b9211af117c/easyeditor/trainer/MultimodalTrainer.py#L174-L175

Why do you use this setting (differece in k=1or10)?

**Comment by tbozhong** [comment]
Our focus is on multimodality, and we are editing language models, so we relax the constraints on the locality of the text.

**Comment by hanhuang22** [comment]
Thanks for your timely reply.

**Comment by tbozhong** [comment]
You are welcome!
