### ISSUE TITLE
 Couldn't find child module transfor

### ISSUE THREAD

**Issue by ssr123s** [zjunlp/EasyEdit#200]
Hello, may I ask，When I use grace, I encounter an error: Couldn't find child module transformer. Below is the original code; what could be the issue?

**Comment by ssr123s** [comment]
![image](https://github.com/zjunlp/EasyEdit/assets/152489945/5616dfbd-cfb1-41d2-b9ec-8b8a6c377d5d)

**Comment by XeeKee** [comment]
It's strange, I'm unable to reproduce your bug. Could you provide me with more detailed code information? Additionally, you can try updating to the latest code and environment."

**Comment by ssr123s** [comment]
I've resolved a previous bug but encountered new issues running Grace on three 4090 GPUs. When I set `model_parallel` to True, I get a "tensor must be on the same GPU" error. With `model_parallel` set to False and specifying a single GPU, I get a "CUDA call failed lazily at initialization with error: device &gt;= 0 &amp;&amp; device < num_gpus INTERNAL ASSERT FAILED at '../aten/src/ATen/cuda/CUDAContext.cpp':50" error. My PyTorch and Transformers versions are 2.0.0+cu118 and 4.30.1, respectively. Any advice would be greatly appreciated.
I've sent the full code as an attachment ,could you please give me some advice?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjunlp/EasyEdit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月10日(星期天) 下午2:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zjunlp/EasyEdit]  Couldn't find child module transfor (Issue #200)





 
It's strange, I'm unable to reproduce your bug. Could you provide me with more detailed code information? Additionally, you can try updating to the latest code and environment."

**Comment by XeeKee** [comment]
I didn't receive your attachment. Could you please resend it to this email address: 1786594371@qq.com?

**Comment by ssr123s** [comment]
Of course, I have already sent it ***@***.*** I sincerely appreciate your willingness to take the time.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zekun ***@***.***&gt;; 
发送时间: 2024年3月11日(星期一) 下午2:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zjunlp/EasyEdit]  Couldn&#39;t find child module transfor (Issue #200)





 
I didn't receive your attachment. Could you please resend it to this email address: ***@***.***?

**Comment by XeeKee** [comment]
Grace supports only single GPU, not multiple GPUs. 
Also, do not include this code in the script; 
```
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
```
input it directly into the terminal.
