### ISSUE TITLE
Suggestions for code modifications

### ISSUE THREAD

**Issue by SH9959** [zjunlp/EasyEdit#201]
In _evaluate.py_ :  The parameter type can be modified to support the scenario where a sample contains multiple locality prompts for calculation.

The origin code is as following:

```
def compute_locality_quality(
    model,
    model_name,
    hparams: HyperParams,
    tok: AutoTokenizer,
    locality_key: str,
    prompt:  str,
    locality_ground_truth: str,
    device,
) -> typing.Dict:
```

Here's the updated code：

```
def compute_locality_quality(
    model,
    model_name,
    hparams: HyperParams,
    tok: AutoTokenizer,
    locality_key: str,
    prompt: typing.Union[str, List[str]], # str,
    locality_ground_truth: typing.Union[str, List[str]], #str,
    device,
) -> typing.Dict:
```

and as well as portability_evaluate.py:

```
def compute_portability_quality(
    model,
    model_name,
    hparams: HyperParams,
    tok: AutoTokenizer,
    portability_key: str,
    prompt: typing.Union[str, List[str]], # str,
    ground_truth: typing.Union[str, List[str]], # str,
    device,
) -> typing.Dict:
```

**Comment by pengzju** [comment]
Thank you for your suggestion, I will update the corresponding code as soon as possible to support multiple locality inputs. 😊

**Comment by pengzju** [comment]
Hi, we have updated the code. You can pass in parameters in the form of `list` or `str`. Single edit can correspond to multiple `locality_inputs` and `portability_inputs`. Please update to the latest version of the code and welcome to try it.

The input form for single editing is as follows:

```python
locality_inputs = {
    'neighborhood':{
        'prompt': [['loc_input_1_for_editing_1', 'loc_input_2_for_editing_1']],
        'ground_truth': [['loc_input_1_ans', 'loc_input_2_ans']]
    }
}
```

**Comment by pengzju** [comment]
If it helps you solve the related problem, please help close this issue. 😊

**Comment by SH9959** [comment]
Yes it works! Thanks! 😄
