### ISSUE TITLE
How to reproduce the multi-modal results using IKE on VQA?

### ISSUE THREAD

**Issue by yaohui120** [zjunlp/EasyEdit#203]
I test the IKE on VQA, using minigpt4 with bfloat16, the results are:
```
rewrite_acc: 0.4946053219214794
rephrase_acc: 0.37861520355392825
rephrase_image_acc: 0.5003752597459872
locality_acc: 0.20157714974469937
locality_image_acc: 0.056616459320518356
```
Then I running code again using minigpt4 with float16, the results are:
```
rewrite_acc: 0.09096731988438912
rephrase_acc: 0.06836493557628892
rephrase_image_acc: 0.34857120541552966
locality_acc: 0.20192411835670443
locality_image_acc: 0.8300476496038428
```
But when I testing the SERAC using minigpt4, the results are normal.

**Comment by tbozhong** [comment]
![image](https://github.com/zjunlp/EasyEdit/assets/50789998/55a7d1ac-44d6-406a-acb5-41c7b4b6bc91)
I am currently executing the `test_IKE_MiniGPT4_VQA_debug()` function with a size of 20, and the results are normal, as described above. Please make sure that you generate the correct context embedding using the `Generate_Embedding_for_IKE()` function with the appropriate task. I apologize for any confusion caused by my unclear description; I will update the README as soon as possible to clarify this.

**Comment by yaohui120** [comment]
I running the same experiment as yours(same function and size=20), but the results are
```
rewrite_acc: 0.1
rephrase_acc: 0.05
rephrase_image_acc: 0.3875
locality_acc: 0.15189881045371295
multimodal_locality_acc: 0.9017322404310107
```
The model I used is vicuna-7b-v1.5.

**Comment by tbozhong** [comment]
You can consider experimenting with the [Vision-CAIR/vicuna-7b](https://huggingface.co/Vision-CAIR/vicuna-7b/tree/main).

**Comment by yaohui120** [comment]
I downloaded the weights mentioned before. And test on VQA with size=20. Now the results seem normal
```
rewrite_acc: 1.0
rephrase_acc: 1.0
rephrase_image_acc: 1.0
locality_acc: 0.11026352364569902
multimodal_locality_acc: 0.03247604505158961
```
Next I will test the total test samples.

**Comment by tbozhong** [comment]
> You can consider experimenting with the [Vision-CAIR/vicuna-7b](https://huggingface.co/Vision-CAIR/vicuna-7b/tree/main).

I have successfully replicated your issue, and the above method can resolve it. It seems that the checkpoint of MiniGPT-4 aligns with vicuna-v0 rather than vicuna-v1.5, which is why it failed.
![image](https://github.com/zjunlp/EasyEdit/assets/50789998/634b6659-6798-43a8-a5b7-30b16f4a5a1f)

**Comment by yaohui120** [comment]
Thank you!
