### ISSUE TITLE
Which methods support batch editing, except MEMIT and PMET?

### ISSUE THREAD

**Issue by XZhang00** [zjunlp/EasyEdit#206]
Hello! Which methods can be chosen if I want to conduct batch editing for LLaMA2-7B, except MEMIT and PMET? 

Thanks for your contributions to the research of model editing!
Looking forward to your reply!

**Comment by XeeKee** [comment]
https://github.com/zjunlp/EasyEdit/blob/main/easyeditor/editors/batch_editor.py 
Perhaps this document can help you.

**Comment by XZhang00** [comment]
OK! Thanks!
