### ISSUE TITLE
Error when trying to run test_InstructEdit.py

### ISSUE THREAD

**Issue by Preethi-IITH** [zjunlp/EasyEdit#207]
OSError: Can't load the configuration of './hugging_cache/gpt2-xl'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure './hugging_cache/gpt2-xl' is the correct path to a directory containing a config.json file

I am not only facing this for gpt2-xl. I am unable to run any of the tutorial notebooks as well due to this error. 
I am a beginner so kindly help me out.

**Comment by pengzju** [comment]
Thanks for your attention! You need to download the model file of `gpt2-xl` and place it in the `hugging_cache` folder.

- https://huggingface.co/openai-community/gpt2-xl

**Comment by Preethi-IITH** [comment]
> Thanks for your attention! You need to download the model file of `gpt2-xl` and place it in the `hugging_cache` folder.
> 
> * https://huggingface.co/openai-community/gpt2-xl

Thank you for the reply.
When I do that I am facing another error "safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge"
Does this mean the model is too large? I have 2 NVIDIA GeForce RTX 2080 Ti in my server. Is that not enough to run GPT2-XL?

**Comment by tbozhong** [comment]
You can attempt to resolve this issue by re-downloading the model. Please ensure that both the base model and safetensor are correctly downloaded. If the file size appears too small, it may indicate a problem.

**Comment by Preethi-IITH** [comment]
> You can attempt to resolve this issue by re-downloading the model. Please ensure that both the base model and safetensor are correctly downloaded. If the file size appears too small, it may indicate a problem.

Thank you for your assistance. I am able to run the code now.
