### ISSUE TITLE
Is there any demos for multimodal editing using KE and FT Methods？

### ISSUE THREAD

**Issue by asdfo123** [zjunlp/EasyEdit#208]
Thanks for the outstanding work! I am now reproducing your results, but I encountered a little problem when trying to edit multi-modal LLM with FT and KE. Is there a demo for the KE and FT methods?

**Comment by tbozhong** [comment]
Thank you for your interest in our work!

In our original code, we implemented FT and KE (referred to as EFK in MEND) based on the [MEND repository](https://github.com/eric-mitchell/mend). We plan to integrate both FT and KE into our project in the future.

**Comment by asdfo123** [comment]
> Hi, do you have any further questions?

No, Thanks a lot!
