### ISSUE TITLE
Accumulation of the results from X_results.json

### ISSUE THREAD

**Issue by Wonder1905** [zjunlp/EasyEdit#209]
Hi, thanks for your wonderfull work, Ive ran your example:
`python run_zsre_llama2.py --editing_method=ROME --hparams_dir=../hparams/ROME/mistral-7b.yaml --data_dir=../../data`
This runs perfectly, and Im getting a results file :ROME_results.json.
This is a pretty long file, and Im wondering is there a script that I missed, that helps to extract the accumulated results out of this file.

Ill be happy for your help.
Thanks

**Comment by XeeKee** [comment]
Sorry, we currently don't have such a script. You can write your own script to read and process the JSON file. If we have time, we will update and provide a script to help you handle the results.

**Comment by Wonder1905** [comment]
Ok , so just to make sure, I need to accumulate the 4 types of results |( "rewrite_acc","locality","portability","rephrase_acc") under the "post" dict, right ?

**Comment by XeeKee** [comment]
yes
