### ISSUE TITLE
How to summarize the metric?

### ISSUE THREAD

**Issue by Luoyang144** [zjunlp/EasyEdit#214]
Hi, I find all metrics are at per data level, can you provide a script to summarize the metric?

**Comment by pengzju** [comment]
Thank you for your attention. 😊

- This is a very good suggestion, we will update the code for printing statistical metrics in the `editor.py` as soon as possible and save the metric `results.json` in the logs folder.

**Comment by xzwyyd** [comment]
Thank you for your feedback! We have updated the code in `editor.py` to print statistical metrics and save metric `results.json` in the `logs` folder. You can set `summary_metrics = True` when using `edit()`. The specific code can be found [here](https://github.com/zjunlp/EasyEdit/blob/main/easyeditor/editors/editor.py#L335). If the current code still does not meet your requirements, you are welcome to make appropriate modifications or feel free to ask any questions at any time.
