### ISSUE TITLE
Test Method IKE on Multi-model

### ISSUE THREAD

**Issue by yaohui120** [zjunlp/EasyEdit#215]
In function compute_icl_multimodal_edit_quality of the EasyEdit-main/easyeditor/evaluate/evaluate.py, the rewrite accuracy is got by running
```
new_fact = f'New Fact: {prompt} {target}\nPrompt: {prompt}'
# pre_edit=False
edit_acc, _ = icl_multimodal_lm_eval(model, model_name, hparams, tok, icl_examples,
                                              target, new_fact, image)
```
I found new_fact involved the answer of the question. It seems there is a problem about information leakage. It's something wrong or I misunderstand the code?

**Comment by tbozhong** [comment]
Your understanding is correct. This is the setting of IKE that we have followed.

**Comment by yaohui120** [comment]
Thank you, I've figure it out. There is a little misunderstanding about IKE.
