### ISSUE TITLE
bugs when evaluate trivia_qa with parameter "all"

### ISSUE THREAD

**Issue by haoyuwangwhy** [zjunlp/EasyEdit#219]
<img width="734" alt="3569d8a59d5bcb7f0b84b792ad687b8" src="https://github.com/zjunlp/EasyEdit/assets/146220694/8076cb38-7338-4fbf-b9f7-d7076cf1a78c">

**Comment by XeeKee** [comment]
We have now fixed this bug, and you can pull the latest code.

**Comment by zxlzr** [comment]
If you have any other issues, please contact us.
