### ISSUE TITLE
The data for run_zsre_llama2.py seems to be invalid

### ISSUE THREAD

**Issue by wending0417** [zjunlp/EasyEdit#22]
Hello, the data you provided in EasyEdit/example

> The datasets used can be downloaded from [here](https://drive.google.com/file/d/1IVcf5ikpfKuuuYeedUGomH01i1zaWuI6). Unzip the file and put it to ./data, and the final directory structure is as follows:

seems to be invalid.

![image](https://github.com/zjunlp/EasyEdit/assets/108311377/91f22260-d0e3-4b40-88b8-342f29c179a8)

**Comment by pengzju** [comment]
I have modified the link and you can now get the dataset

**Comment by wending0417** [comment]
The new link works, thank you very much!
