### ISSUE TITLE
Sanitation results reproducibility issue

### ISSUE THREAD

**Issue by AmitRozner** [zjunlp/EasyEdit#221]
I tried running: 
`python run_santinization_llama2.py --editing_method ROME \
    --hparams_dir ./hparams/ROME/llama-7b.yaml \
    --data_dir ./data \
    --specify_answer cheese`

I am not getting the same results as mentioned in this github and in the paper. Can you elaborate how to recreate the sanitation results?
The results I am getting are:
`{'success': 0.125, 'locality': 0.16898454746136912, 'fluency': {'ngram_entropy': 4.162906924495765}}`

**Comment by XeeKee** [comment]
This may be due to different hyperparameters. Could you please provide your hyperparameters? I suspect it might be because you have `fp16: true`, which I didn't have in my experiment.

**Comment by XeeKee** [comment]
Hello, I recently reran experiments with the hyperparameter settings of `fp16: true` and `fp16: false`, and indeed, there are significant differences in the results. Therefore, I believe that the discrepancies are caused by setting `fp16: true`.

**Comment by zxlzr** [comment]
Hi, do you have any further issues?
