### ISSUE TITLE
How to get the origin result?

### ISSUE THREAD

**Issue by BUGLI27** [zjunlp/EasyEdit#222]
How can I get the LLM origin output of each prompt before and after edit instead of the acc between 0~1?

**Comment by XeeKee** [comment]
EasyEdit is primarily for research on model editing, so we do not provide intuitive editing results, as this would consume more computational resources. You can directly use the edited model's model.generate() to produce results.

**Comment by BUGLI27** [comment]
Since the EasyEdit does not provide intuitive editing results, how the acc results are calculated?

**Comment by XeeKee** [comment]
You can take a look at this place, our generate's max_new_tokens is merely the len(target_new_tokens).
https://github.com/zjunlp/EasyEdit/blob/eb833c233098c38744077c5ffb4c313355a8d99a/easyeditor/evaluate/evaluate_utils.py#L82

**Comment by XeeKee** [comment]
Our accuracy calculation process involves having the model generate tokens of the length of target_new_tokens, and then comparing the generated tokens with target_new_tokens to find the proportion of matches. This gives us the final accuracy.
