### ISSUE TITLE
Get low result when using SERAC to edit GPT-J-6B model (eval bug, under fixing)

### ISSUE THREAD

**Issue by Luoyang144** [zjunlp/EasyEdit#223]
Hi, I'm tring to use SEARC to edit GPT-J-6B, after summarize the score I get follow result:
```
{
    "pre": {
        "rewrite_acc": 0.2153846821697388,
        "portability": {
            "Subject_Aliasing_acc": 0.00033785398646853174,
            "reasoning_acc": 0.0005996302293378747
        }
    },
    "post": {
        "rewrite_acc": 0.2153846821697388,
        "locality": {
            "Relation_Specificity_acc": 0.00120627261761158,
            "Forgetfulness_acc": 1.0
        },
        "portability": {
            "Subject_Aliasing_acc": 0.00033785398646853174,
            "reasoning_acc": 0.0005996302293378747
        }
    },
    "time": 0.011246368626445638
}
```
Here is my config:
```
# Model
alg_name: "SERAC"
archive: archive/gpt-j-6B_bak
device: 0
model_name: EleutherAI/gpt-j-6b

model_class: GPTJForCausalLM
small_name: anton-l/gpt-j-tiny-random
tokenizer_class: GPT2Tokenizer
tokenizer_name: EleutherAI/gpt-j-6b
cls_name: distilbert/distilbert-base-cased
cls_class: AutoModel
inner_params: []
model_parallel: false

# Method
alg: SERAC
lr: 1e-5
edit_lr: 1e-2
seed: 0
lr_lr: 0.0
cedit: 0.1
cloc: 1.0
cbase: 1.0
dropout: 0.0
final_eval: True
supervised: False
train_base: False
no_grad_layers: null
soft_weighting: False
checkpoint_grad: False
cross_attend: False
cos: False
freeze: null
square: True
bound_embeds: False
use_all_negatives: False
freeze_cntr: False
dist_heads: 1
lora: null

batch_size: 1
model_save_pt: 1000
edit_bs: 1
silent: False
#max_epochs: 1
max_iters: 100000
log_interval: 1000
val_interval: 1000
early_stop_patience: 40000
early_stop_key: "loss/total_edit_val"
eval_only: False
half: False
save: False
debug: False
log_errors: False
unlikelihood: True


val_batch_size: 1
accumulate_bs: 10
val_steps: 1000
opt: Adam
grad_clip: 100.

# Output
results_dir: ./results

```
My archive file is provide by this [link](https://drive.google.com/drive/folders/1rVWN7z05CHkIwbOJ5Cy3E0seWSpU6SeT). I check all item in result file and find all results in `pre` and `post` are same, how to slove this problem?

**Comment by XeeKee** [comment]
Sorry, the ckpt file might have been slightly damaged during the upload. I will re-upload a new ckpt file shortly, or you can train it yourself.

**Comment by XeeKee** [comment]
We have uploaded the new ckpt, and you can download it. However, we only provide the training weights for the counterfact dataset.

**Comment by zxlzr** [comment]
Hi, if you have further issues, feel free to contact us.

**Comment by Luoyang144** [comment]
@XeeKee Hi, can you provide the download link?

**Comment by XeeKee** [comment]
I'm sorry, I forgot to provide you with the link. It's actually the same Google Drive link as before: https://drive.google.com/drive/folders/1rVWN7z05CHkIwbOJ5Cy3E0seWSpU6SeT
My training log results are as follows:
loss/edit_train:  2.00917; loss/loc_train:  0.00361; edit/acc_train:  0.79856; edit/log_prob_train: -2.00917; edit/prob_train:  0.37761; acc/pre_train:  0.00000; acc/post_train:  0.00000; nll/pre_train:  14.37212; perplexity/pre_train:  1744740.87500; nll/post_train:  13.62768; perplexity/post_train:  828757.87500; n_tokens/pre_train:  17.64700; n_tokens/post_train:  17.64700; time/edit_train:  0.00669; loss/total_train:  0.20453; loss/total_edit_train:  0.20453; memory/alloc_max_train:  0.00000; memory/res_max_train:  0.00000; grad_train:  0.42909

**Comment by Luoyang144** [comment]
Hi @XeeKee , I guess you mean gpt2-xl in this link? Is it trained from openai-community/gpt2-xl?
![image](https://github.com/zjunlp/EasyEdit/assets/63402979/e789aec2-80ed-4d57-a8ab-601827a4ece3)

**Comment by XeeKee** [comment]
No, what I uploaded are the weights for GPT-J. There might be a slight delay. If the weights I uploaded do not appear after 1 hour, I will upload them again.

**Comment by zxlzr** [comment]
Hi, have you solved your issue yet? can you download the checkpoint?

**Comment by Luoyang144** [comment]
@zxlzr Hi, I have successfully download the checkpoint, but SEARC experiments on this checkpoint both get lower result after edit(compare with pre). Here is summary:
```
# counterfact
{
    "pre": {
        "rewrite_acc": 0.2153846821697388,
        "portability": {
            "Subject_Aliasing_acc": 0.00033785398646853174,
            "reasoning_acc": 0.0005996302293378747
        }
    },
    "post": {
        "rewrite_acc": 0.16631071109275666,
        "locality": {
            "Relation_Specificity_acc": 0.0011760432062114553,
            "Forgetfulness_acc": 0.903258547008547
        },
        "portability": {
            "Subject_Aliasing_acc": 0.00033752326771433833,
            "reasoning_acc": 0.0005950694469356537
        }
    },
    "time": 0.014602932230934625
}
# zsre
{
    "pre": {
        "rewrite_acc": 0.28060724398157144,
        "rephrase_acc": 0.2711843946471156,
        "portability": {
            "reasoning_acc": 0.49394760772274
        }
    },
    "post": {
        "rewrite_acc": 0.228677096240509,
        "rephrase_acc": 0.268447183954486,
        "locality": {
            "Relation_Specificity_acc": 0.993462317424654
        },
        "portability": {
            "reasoning_acc": 0.4937044170612614
        }
    },
    "time": 0.01073820090678726
}
```

**Comment by Luoyang144** [comment]
I will try train it myself this week, can you check this problem when you free?

**Comment by XeeKee** [comment]
I recently checked the code and found that there seems to be a bug in the recent code regarding the evaluation of serac's results. When I use the model I uploaded to generate, it can correctly predict 'target_new', but the evaluation module shows it as incorrect. You can roll back to the previous evaluation code, and I will take some time to fix this bug soon.
![image](https://github.com/zjunlp/EasyEdit/assets/70566607/89eac53b-9df1-44cd-8e5f-5fe67869f09d)

**Comment by zxlzr** [comment]
Sorry, this bug will be fixed as soon as possible. We apologize for any inconvenience caused.

**Comment by Luoyang144** [comment]
Thanks for reply, this may explain why I always get low result.🙌

**Comment by XeeKee** [comment]
Hello, I have identified the reason for the poor performance of the SERAC effect in the GPT series models. It is due to the different sensitivities to spaces of the tokenizers in the GPT series and LLaMA series models. In the data set loading section, I modified the method of adding spaces to the target. However, due to the recent shortage of computational resources in our group, I have not tested the entire dataset but only the first ten entries, all of which could be edited successfully. You can update the file at easyeditor/dataset/counterfact.py and then retrain SERAC.

**Comment by Luoyang144** [comment]
@XeeKee Thanks for reply, I will retrain replacement models and try SERAC in few days.

**Comment by DavideVendittii** [comment]
Sorry @Luoyang144 , could you share the code you used to generate the files you uploaded to Google Drive? I'm trying to do the same thing with other models. 
Thanks!
