### ISSUE TITLE
关于综述论文更新

### ISSUE THREAD

**Issue by YuGuangYa** [zjunlp/EasyEdit#224]
您好，非常感谢你们团队的工作！我注意到《A Comprehensive Study of Knowledge Editing for Large Language Models》在arxiv上有多次版本的更新，不知道能否为这些更新内容做出一定的说明？

**Comment by zxlzr** [comment]
您好，感谢对论文的关注：

v2 版本优化了图表，新增若干参考文献
v3 更正了一些typo
v4 新增了FT-M，一种简单的基于微调的知识编辑方法，在EasyEdit有支持，效果较好并新增了分析

我们计划在未来更新v5 新增近期的知识编辑工作参考文献和补充应用

**Comment by zxlzr** [comment]
我们会在下一次更新的arxiv上新增更新说明

**Comment by YuGuangYa** [comment]
非常感谢！
