### ISSUE TITLE
val2014_image_rephrase for multimodal edit

### ISSUE THREAD

**Issue by pkulium** [zjunlp/EasyEdit#228]
great work!
can we get val2014_image_rephrase for multimodal edit?

**Comment by tbozhong** [comment]
Thank you for your interest in our work!

Please refer to our [README](https://github.com/zjunlp/EasyEdit/blob/1093810534c69d2a81958dcf7cb52ea32a914738/examples/MMEdit.md#118) to download **all images** used in our experiments. Upon extracting the archive, you will find the **val2014_image_rephrase** directory.

**Comment by pkulium** [comment]
Thanks for reply. There is another issue 

> EasyEdit/easyeditor/trainer/utils.py", line 146, in load_archive
>     search = os.path.join(wd, d)
> NameError: name 'wd' is not defined

**Comment by tbozhong** [comment]
It appears that you might use an incorrect configuration file. Kindly refer to the following instructions in the README to ensure proper setup.
![image](https://github.com/zjunlp/EasyEdit/assets/50789998/7366b976-41db-4379-a6d2-f42a78aaba32)

**Comment by zxlzr** [comment]
Hi, have you solved your issue?
