### ISSUE TITLE
About the input of multimodal editing

### ISSUE THREAD

**Issue by yaohui120** [zjunlp/EasyEdit#234]
My understanding is that the input of the modal is the combination of the question text embedding and image embedding. But I found the text input actually contains the answer. Such as function forward in EasyEdit-main/easyeditor/trainer/blip2_models/mini_gpt4.py

```
            text = [t + self.end_sym for t in samples["text_input"]]
            to_regress_tokens = self.llama_tokenizer(...).to(image.device)
            ...
            to_regress_embeds = self.llama_model.model.embed_tokens(to_regress_tokens.input_ids)
            inputs_embeds = torch.cat([bos_embeds, img_embeds, to_regress_embeds], dim=1)
            attention_mask = torch.cat([atts_bos, atts_img, to_regress_tokens.attention_mask], dim=1)
            ...
            with self.maybe_autocast():
                   outputs = self.llama_model(inputs_embeds=inputs_embeds, attention_mask=attention_mask, ...)
```
I use tokenize decode the to_regress_tokens.input_ids, and it has the answer:
```
(Pdb) self.llama_tokenizer.batch_decode(to_regress_tokens.input_ids, skip_special_tokens=True)[0]
(Pdb) 'Question: What sport can you use this for? Short answer: riding'
```
I thought it should be 'Question: What sport can you use this for?' or 'Question: What sport can you use this for? Short answer:'.

**Comment by tbozhong** [comment]
Thanks for your attention to our work!

For the reason of this setting, please refer to issue #115.

**Comment by zxlzr** [comment]
Hi, do you have any further questions?
