### ISSUE TITLE
Multimodal_IKE Edit

### ISSUE THREAD

**Issue by ksasi** [zjunlp/EasyEdit#238]
Hi,

Can you please let me know if Multimodal_IKE performs model editing for Captioning and VQA datasets ? Appears this area is still  work in progress for this library.

Thanks and Regards,
Sasikanth

**Comment by tbozhong** [comment]
Hello, thanks for your attention to our work!
You can refer to [here](https://github.com/zjunlp/EasyEdit/blob/main/examples/MMEdit.md#multimodaleditor) for using `IKE` in multimodal setting.

**Comment by zxlzr** [comment]
hi, do you have any further questions?
