### ISSUE TITLE
Can I use EasyEdit to evaluate the local model which is edited?

### ISSUE THREAD

**Issue by CuSO4-Chen** [zjunlp/EasyEdit#24]
Dear EasyEdit research team:
      Sincerely, thank you for your outstanding work in the field of model editing which is very helpful and inspiring to me. To this end I would like to ask you a question: Can I use EasyEdit to evaluate the local model which is edited by myself? If the answer is yes, how can I do that? Cause it seems like I do not have a yaml file after editing a model(such as llama 7b). Looking forward to your response.

**Comment by pengzju** [comment]
Thank you for your interest in EasyEdit, if you want to edit the llama-7b model, you can directly reuse the yaml configuration file of LLAMA-7B-2. If you want to edit the local model by yourself, perhaps you need to change the editing method manually.
- What type is your local model?

**Comment by CuSO4-Chen** [comment]
Thank for your reply! My local model will be a LLM such as LLAMA-7B but which is alreday edited by myself with other method, so my desire is that can I use the EasyEdit to evaluate the editing effect of my method on this model directly ? (such as by providing the edited model file to the EasyEdit, and choose the dataset like zsRE, can EasyEdit evalutate?)

**Comment by pengzju** [comment]
- The current design of EasyEdit is to evaluate each edit case. You will have the corresponding metrics in the editing process.
- If you have edited the model using another public repository, my recommendation is to test metric against the vanilla model and your edited model output. EasyEdit does not yet support your requirements.
    - You can refer here: https://github.com/zjunlp/EasyEdit/blob/main/easyeditor/evaluate/evaluate.py

**Comment by pengzju** [comment]
If your problem has been resolved, please help close this issue.

**Comment by CuSO4-Chen** [comment]
OK，thank you a lot

**Comment by CuSO4-Chen** [comment]
OK，thank you a lot
