### ISSUE TITLE
npz files in MEMIT

### ISSUE THREAD

**Issue by BUGLI27** [zjunlp/EasyEdit#240]
<img width="1081" alt="image" src="https://github.com/zjunlp/EasyEdit/assets/87059873/72ea5021-65c4-4c85-b65a-7322923c7d61">
It seems that `npz` files are needed when using MEMIT method, how can I get these files when editing the Qwen model.

**Comment by xzwyyd** [comment]
Thank you for your interest. 😊Here, we provide `npz` files for only a few selected models as examples. However, the `npz` files will be automatically generated during the code execution process. If you have any further questions or need more assistance, please feel free to let me know.

**Comment by xzwyyd** [comment]
And if you're interested in the generation process of `npz` files, you can find it [here](https://github.com/zjunlp/EasyEdit/blob/main/easyeditor/models/rome/layer_stats.py).

**Comment by xzwyyd** [comment]
And if you're interested in the generation process of these files, you can find it [here](https://github.com/zjunlp/EasyEdit/blob/main/easyeditor/models/rome/layer_stats.py#L77).

**Comment by xzwyyd** [comment]
You can try downloading wikipedia dataset to your local machine and using the commented code in lines 99-101 of EasyEdit/easyeditor/models/rome/layer_stats.py to replace lines 102-105 to load the local dataset. The code is [here](https://github.com/zjunlp/EasyEdit/blob/main/easyeditor/models/rome/layer_stats.py#L98).

**Comment by BUGLI27** [comment]
Thanks, when i run code
```python
for item in test_data:
        prompts.append(item['requested_rewrite']['prompt'].format(item['requested_rewrite']['subject']))
        target_new.append(item['requested_rewrite']['target_new']['str'])
        subject.append(item['requested_rewrite']['subject'])

    hparams = editing_hparams.from_hparams(args.hparams_dir)

    editor = BaseEditor.from_hparams(hparams)
    metrics, edited_model, _ = editor.edit(
        prompts=prompts,
        target_new=target_new,
        subject=subject,
        keep_original_weight=False
    )
```

Is it to edit all the knowledge at once, and is the edited model file saved in my original location of model?

**Comment by xzwyyd** [comment]
Our `edit()` method only supports editing one example at a time. Additionally, we do not save the edited model by default. If you wish to save the edited model, you can set `keep_original_weight` to `False` in the `edit()` method and then manually save the edited model. You can use the following code: `edited_model.save_pretrained("your output path")`. If you have any further questions or need assistance, please feel free to let me know.

**Comment by BUGLI27** [comment]
So if i want to test the model's **Complete answer** about every question of the edit_facts after edit, i need to 
```python
for item in edit_facts:
  edited_model = editor.edit(item)
  edited_model.generate(question_of_item)
```
If I want to test model's **Complete answer** after edit all edit_facts, like batch edit in the paper, how can i Implement it?
<img width="1084" alt="image" src="https://github.com/zjunlp/EasyEdit/assets/87059873/049205dc-16c1-4019-80c0-19fb1e48f085">
Finally, since i need to manually save the edited model, what's the usage of setting `keep_original_weight` to `False`?
