### ISSUE TITLE
About selecting demonstration when testing IKE

### ISSUE THREAD

**Issue by yaohui120** [zjunlp/EasyEdit#244]
In function apply_ike_to_multimodal_model in EasyEdit-main/easyeditor/models/ike/ike_main.py, the last line is
```
icl_examples.append(f'New Fact: {new_fact}\nPrompt: {new_fact}\n\n')
```
I'm a little confused. Why adding the question and answer of a testing sample when applying ike? My understanding is that the input of model should not contain the true answer of the testing question.

**Comment by tbozhong** [comment]
Thanks for your attention to our work.

It seems that you have mentioned this question before in #215, we just follow the setting of [IKE](https://github.com/Zce1112zslx/IKE/blob/6ffd87232f626baf8d5c24c2ed4a1d21cc896935/icl.py#L129C1-L129C99). I'd suggest direct contact with the authors to seek further clarification. They may be better poised to assist you in your inquiry.

**Comment by yaohui120** [comment]
Thank you for your help. I'll do experiments to explore the influence.
