### ISSUE TITLE
How to perform Batch Editing using Easyedit?

### ISSUE THREAD

**Issue by henryoung217** [zjunlp/EasyEdit#25]
Thanks for your contribution !
I have a problem with Easyedit framework, when I edit multiple facts on the base model using the editor.edit(), the run still looks like performing sequential edit, how to perform batch edit on the base model? Does batch edit using MEND and MEMIT take less time than sequential edit?
Looking forward to your reply ! It's really a great project

**Comment by pengzju** [comment]
- Yep. `editor.edit()` edits the sample pairs sequentially
- Batch editing can be done using the` editor.batch_edit` function
- Batch editing is less time-consuming than single editing, but may not ensure editing performance and require more VRAM. Both MEMIT and MEND can perform batch editing

**Comment by pengzju** [comment]
If your problem has been resolved, please help close this issue.

**Comment by henryoung217** [comment]
Thanks for your reply !
