### ISSUE TITLE
Maybe a little bug in evaluate_utils.py

### ISSUE THREAD

**Issue by Luoyang144** [zjunlp/EasyEdit#253]
Hi, I find this line: https://github.com/zjunlp/EasyEdit/blob/73a1efbd3d92c270fed4044e62a3b269ffcabe2f/easyeditor/evaluate/evaluate_utils.py#L90
In this loop, I think it should be: ` target_new_tokens = tok.encode(target_new)`.
By the way, this is a bug that occurred when running the editor, so I discovered this problem. If there is any problem with my modification, please point it out.

**Comment by XeeKee** [comment]
Thank you very much for your correction; we have updated the code. Previously, EasyEdit mainly handled single edits, which is why we had not noticed this bug. Wishing you a pleasant life!

**Comment by Luoyang144** [comment]
Thanks for reply, I will close this issue.
