### ISSUE TITLE
MultimodalEditor Question

### ISSUE THREAD

**Issue by wxz2002** [zjunlp/EasyEdit#257]
Thank you for your outstanding work on multimodal knowledge editing. However, when I was trying to test your work, I found the following line of code in the **Edit** method of **MultimodalEditor**: 
`**assert self.alg_name == 'IKE' or print('Only IKE supported for MultimodalEditor')**`.
 Could you please explain why multimodal knowledge editing currently only supports the IKE method? Are other methods temporarily untestable?

**Comment by tbozhong** [comment]
Thanks for your interest in our work, and I apologize for any inconvenience.

At present, `MultimodalEditor` only supports `IKE`. For other methods, please utilize `MultimodalTrainer` for both training and evaluation, as detailed in the **Evaluating Example** section found [here](https://github.com/zjunlp/EasyEdit/blob/main/examples/MMEdit.md#multimodaltrainer).

I will support additional methods within `MultimodalEditor` as soon as possible.

**Comment by tbozhong** [comment]
We appreciate your interest in our work!

I have addressed this issue in the [commit](https://github.com/zjunlp/EasyEdit/commit/f2726425ba439a75a490e6ec8bd3180152330db8). If you have any further questions, please don’t hesitate to reach out.

**Comment by zxlzr** [comment]
Hi, if you have any further issues, feel free to contact us.
