### ISSUE TITLE
Cannot run IKE on counterfact

### ISSUE THREAD

**Issue by AmitRozner** [zjunlp/EasyEdit#258]
Hi, 
I am trying to run IKE on counterfact dataset using the following command:
`python run_knowedit_llama2.py \
    --editing_method=IKE \
    --hparams_dir=../hparams/IKE/llama-7b \
    --data_dir=./data \
    --datatype='counterfact'`
Since `train_data_path` is not set it is breaking at:
`train_ds = KnowEditDataset(args.train_data_path)`
The error is due to `train_data_path` being `None`:
`TypeError: expected str, bytes or os.PathLike object, not NoneType`

Any advice? 
Thanks

**Comment by XeeKee** [comment]
The IKE method requires providing some cases as examples. Therefore, when running it, you need to include the train_data_path parameter, similar to the MEND and SERAC methods.

**Comment by zxlzr** [comment]
Hi, have you solved your issue?

**Comment by AmitRozner** [comment]
I tried with `KnowEdit/benchmark/wiki_counterfact/train_cf.json` how much GPU memory is required for llama-7b? I am trying with A100 40gb and getting OOM.
Also, what is the file for ZsRE? I tried `zsre/zsre_mend_train_10000.json `but getting an error:
`"prompt": record["prompt"] if "prompt" in record else record["text"],
KeyError: 'text'`

**Comment by XeeKee** [comment]
run_knowedit_llama2.py  is prepared for KnowEdit, so your dataset should be selected in KnowEdit. You can download it from https://huggingface.co/datasets/zjunlp/KnowEdit. If you encounter an out-of-memory error, you can reduce the value of k in the hparams.

**Comment by zxlzr** [comment]
Hi, have you solved your issue?

**Comment by AmitRozner** [comment]
I lowered K and was able to run it partially. Need to get an 80GB GPU to run everything.
