### ISSUE TITLE
What is the gpu requirement to run MEMIT on llama7b?

### ISSUE THREAD

**Issue by edchengg** [zjunlp/EasyEdit#26]
I got OOM on 46GB A40 GPU. Is it expected? how should I solve it? Thank you.

**Comment by pengzju** [comment]
- What editing method did you choose?
- What's the model to be edited?

**Comment by pengzju** [comment]
Around 50 GB VRAM. You can use accelerate (https://github.com/huggingface/accelerate) for the model parallel.

**Comment by edchengg** [comment]
Thank you!
Do you have an example to support accelerate? or is this built in the library already

**Comment by pengzju** [comment]
> Thank you! Do you have an example to support accelerate? or is this built in the library already

- Sorry, we don't support Model Parallel yet. Model editing requires modifying the weights of internal parameters, which is a complex process combined with `accelerate`.
- My suggestion is that you can use `device_map='auto'`, using the native model parallel of `huggingface`. You can refer here(https://huggingface.co/docs/accelerate/usage_guides/big_modeling) for learning `device_map`.
    - For example, to edit the llama, you should modify the code here. https://github.com/zjunlp/EasyEdit/blob/main/easyeditor/editors/editor.py#L73
