### ISSUE TITLE
Invalid Dataset Link in "examples/PersonalityEdit.md" (404 Error)

### ISSUE THREAD

**Issue by LewisVille-flow** [zjunlp/EasyEdit#260]
Hello,
Thank you for your fascinating research. I recently came across a paper titled "Editing Personality For Large Language Models," which utilizes this library, 'Knowledge edit' tool. I'm very interested in this project; however, the dataset link provided appears to be expired or has changed, as it's currently invalid. Links: (https://github.com/zjunlp/EasyEdit/blob/main/examples/PersonalityEdit.md#datasets)

Could you please update or reopen the Google Drive link for the dataset?
I'm eager to explore this project further and believe the dataset could lead to some intriguing experiments.

Thanks.

**Comment by shengyumao** [comment]
Thanks for reminding! We've updated the Google Drive Link, the dataset is available now.
