### ISSUE TITLE
运行BLIP2拨错TypeError: forward() got an unexpected keyword argument 'input_ids'

### ISSUE THREAD

**Issue by tobocca** [zjunlp/EasyEdit#262]
代码如下：
from easyeditor import EditTrainer, MENDTrainingHparams, ZsreDataset,MENDMultimodalTrainingHparams,CounterFactDataset

training_hparams = MENDMultimodalTrainingHparams.from_hparams('hparams/TRAINING/MEND/blip2.yaml')
train_ds = CounterFactDataset("./data/counterfact/counterfact-train.json", config=training_hparams)
eval_ds = CounterFactDataset("./data/counterfact/counterfact-val.json", config=training_hparams)
trainer = EditTrainer(
    config=training_hparams,
    train_set=train_ds,
    val_set=eval_ds
)
trainer.run()
报错：
![image](https://github.com/zjunlp/EasyEdit/assets/68278927/6ddf9073-5d18-4372-b04c-8c7ccd2f4b45)

**Comment by tobocca** [comment]
有遇到类似问题的吗

**Comment by tbozhong** [comment]
It appears that you are editing the model with mismatched `dataset` and `trainer` classes. Please refer to the `Use EasyEdit` section [here](https://github.com/zjunlp/EasyEdit/blob/3c59cb13ea1e6a7f0029cfcac9aa11c6af8d6a0b/examples/MMEdit.md) for guidance on properly editing BLIP2.

**Comment by zxlzr** [comment]
Do  you have any further issues?
