### ISSUE TITLE
About the configuration file of KE on BLIP2 and MiniGPT4

### ISSUE THREAD

**Issue by yaohui120** [zjunlp/EasyEdit#264]
The paper 'Can We Edit Multimodal Large Language Models?' provides the results of KE on BLIP2 and MiniGPT4 pretrained-model, but the corresponding configuration files aren't provided (EasyEdit-main/hparams/TRAINING/KE). So could you upload these files? Thank you so much!

**Comment by tbozhong** [comment]
Thank you for your interest in our work!

In our original code, we implemented FT and KE (referred to as EFK in MEND) based on the [MEND](https://github.com/eric-mitchell/mend)  repository. We plan to integrate both FT and KE into our project in the future.

**Comment by yaohui120** [comment]
Thank you, I'll have a try.
