### ISSUE TITLE
A Package Conflict When Installing Dependencies

### ISSUE THREAD

**Issue by nuster1128** [zjunlp/EasyEdit#268]
Kindly remind a package conflict between `tokenizers==0.13.3` and `transformers==4.40.0` when installing dependencies.
**Error Message:**
```
INFO: pip is looking at multiple versions of transformers to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 19) and tokenizers==0.13.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested tokenizers==0.13.3
    transformers 4.40.0 depends on tokenizers<0.20 and >=0.19
```
Replace `transformers==4.40.0` with `transformers` can address this issue for installation.

**Comment by XeeKee** [comment]
Thank you very much for your suggestion. However, we set 'transformers==4.40.0' to ensure compatibility with LLaMA3. We have already replaced 'tokenizers==0.13.3' with 'tokenizers' in the requirements.

**Comment by nuster1128** [comment]
Thanks for addressing my issue. Have a good weekend :)
