### ISSUE TITLE
Repository Not Found for url: https://huggingface.co/zjunlp/MEND-Safety-Classifier/resolve/main/config.json.

### ISSUE THREAD

**Issue by CaiJichang212** [zjunlp/EasyEdit#269]
when i run:
```
DATE=2024年5月28日
EDIT_METHOD=MEND
MODEL=gpt2-xl
DATA=SafeEdit_test

CUDA_VISIBLE_DEVICES=1 nohup python run_safety_editing.py \
    --editing_method $EDIT_METHOD \
    --edited_model $MODEL \
    --hparams_dir ../hparams/$EDIT_METHOD/$MODEL \
    --safety_classifier_dir zjunlp/$EDIT_METHOD-Safety-Classifier \
    --data_dir ../dataset/round1_dataset/$DATA.json \
    --metrics_save_dir ./safety_results \
    > log/$DATE/$EDIT_METHOD-$MODEL-$DATA-1.log 2>&1 
```
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/zjunlp/MEND-Safety-Classifier/resolve/main/config.json

Repository Not Found for url: https://huggingface.co/zjunlp/MEND-Safety-Classifier/resolve/main/config.json.

![image](https://github.com/zjunlp/EasyEdit/assets/167088965/745f617f-4de2-4a39-817f-62bf737beb31)

if you can provide the `MEND-Safety-Classifier`,the bug can be solved.

**Comment by mengrusun** [comment]
Actually, the security classifier is shared by all methods. There is no need to change the path with method.
To avoid misunderstandings, we have updated the name of the classifier to "SafeEdit-Safety-Classifier".
Then, the classifier path should be : --safety_classifier_dir SafeEdit-Safety-Classifier
And, the huggingface url:  https://huggingface.co/zjunlp/SafeEdit-Safety-Classifier

By the way, MEND method code for SafeEdit dataset is ongoing. You can also try it yourself.

**Comment by CaiJichang212** [comment]
I got it,thanks!
