### ISSUE TITLE
Which language model did you choose to produce the result of sequential editing in your tutorial.pdf？

### ISSUE THREAD

**Issue by wending0417** [zjunlp/EasyEdit#27]
Hello, thanks for your great contributions!
I'm very interested in your tutorial.pdf of this repo. May I ask which language model did you choose to produce the result of sequential editing in your tutorial.pdf？
![image](https://github.com/zjunlp/EasyEdit/assets/108311377/8d8a00b2-6696-4883-8ff2-17ea5f3fc853)
Looking forward to your reply. Thank you very much!

**Comment by pengzju** [comment]
GPT-J(https://huggingface.co/EleutherAI/gpt-j-6b)

**Comment by wending0417** [comment]
Thanks a lot!
