### ISSUE TITLE
Some doubts on the dataset tested

### ISSUE THREAD

**Issue by yihuaihong** [zjunlp/EasyEdit#28]
Hello! I greatly appreciate your work and have a simple problem.

I would like to know whether the editing performance results showed were tested on the dataset named 'zsre_mend_eval_portability_gpt4.json' which the number of the samples is 1037. Because I didnt see any "probability inputs" on the orginal Zsre dataset that you provide in google drive and it will not have the prob metric I think.  

Thank you so much.

**Comment by pengzju** [comment]
Thank you for your interest in EasyEdit. 😊
- To test the model's ability to **take advantage of edited facts**, we used `gpt4` to generate a `one-hop` question about edited facts. So the editing performance was tested on the dataset `zsre_mend_eval_portability_gpt4`. 
    - That is, we extend the original ZsRE dataset for more robust evaluation.
- Yes, the original ZsRE dataset could not be used for portability evaluation.

**Comment by yihuaihong** [comment]
OK, Thank you very much for your qucik response.

So the portability evaluation in the same performance table with original dataset is only on 1037 samples? I mean, maybe too small to be representative compared to the original amount of zsre? And the probability problem is only one per sample.

Dont mind it, it is a little comment :). Anyway it is a good work. Thanks.

**Comment by pengzju** [comment]
Thank you for your advice. 🤗
- In fact, 1037 samples is enough to measure the performance of different editing methods. For example, in the sequence editing scenario, the editing capacity of most editing methods is **<=100**.
- You're right. In our experiments, only one one-hop entity is considered for each editing case. We test the model's ability to apply edited facts, unabling to identify all of the affected one-hop link entities.

**Comment by pengzju** [comment]
If your problem has been resolved, please help close this issue.
