### ISSUE TITLE
ROME test

### ISSUE THREAD

**Issue by SXxinxiaosong** [zjunlp/EasyEdit#282]
您好，对于ROME模型我有一个问题：
ROME的test似乎是修改一条，计算一次acc，最后计算平均值。并且没有保存最终的模型。
为什么不是在最终的模型，在edit set上重新推理进行评测？因为之后的编辑会影响目前编辑的效果，当前编辑成功，没准经过之后的编辑后，当前这条就推理失败了？
谢谢~

**Comment by XeeKee** [comment]
Hello, thank you very much for your interest in EasyEdit. The setting you mentioned should be the 'continue' setting. You can set 'sequential edit' to true, so that the final model will contain the results of each edit.

**Comment by SXxinxiaosong** [comment]
谢谢您的回复。好像没有找到sequential edit这个参数？

**Comment by XeeKee** [comment]
Have you updated to the latest EasyEdit code? If so, set the editor.edit() function accordingly

**Comment by SXxinxiaosong** [comment]
好的好的谢谢！我需要更新一下~

**Comment by SXxinxiaosong** [comment]
还有一个小小的问题是：'./data/zsre_mend_eval_one_hop.json'  这个文件是zsre_mend_eval.json做了特定的处理吗？
