### ISSUE TITLE
llama2-7b-chat data is not reproducible

### ISSUE THREAD

**Issue by jiangkl8bigai** [zjunlp/EasyEdit#283]
![image](https://github.com/zjunlp/EasyEdit/assets/147908634/259175b6-602b-4ce9-8aed-a4b9d3cdb8eb)

I reproduced the results of your paper on llama2-7b-chat, and found that it was impossible to reproduce the data, and the data were very different.
I used the json file after each run_knowedit_llama2.py calculation, and the data set I used each time was test data.
Hope to get your reply!

**Comment by zxlzr** [comment]
Could you please report the details of your settings and results, dataset and metric, so we can help you.

**Comment by zxlzr** [comment]
I found you have submitted many issues and thank you for your interests in EasyEdit and knowledge editing, maybe you can add the WeChat: yaoxiaoyun12 so we can make communication more convenient.

**Comment by jiangkl8bigai** [comment]
非常感谢 我已经添加您的微信了
