### ISSUE TITLE
Question about hyparams in tutorial-notebooks

### ISSUE THREAD

**Issue by Leo-Lsc** [zjunlp/EasyEdit#284]
Why don't the .yaml files in the tutorial-notebooks have hyperparameters "stats_dir"?

**Comment by XeeKee** [comment]
Only ROME and MEMIT require stats_dir

**Comment by Leo-Lsc** [comment]
Thanks for your answering, but I found that ROME's examples in [tutorial-notebooks] do not have stats_dir? btw, may I ask what is the effect of this hyperparameter? I have not yet make this file "./data/stats", but it seems that my program still can run?

**Comment by XeeKee** [comment]
If there is no ./data/stats, the accuracy of your results will be lower.
