### ISSUE TITLE
RuntimeError when executing run_knowedit_llama2.py

### ISSUE THREAD

**Issue by Leo-Lsc** [zjunlp/EasyEdit#286]
I got an error " 
../easyeditor/util/generate.py", line 134, in generate_fast
new_tok_indices = torch.multinomial(softmax_out_top_k, 1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0"
when executing the script run_knowedit_llama2.py?

**Comment by XeeKee** [comment]
Could you provide more detailed information, such as the method you ran, the model used, and the hyperparameters, so that I can better assist you?

**Comment by zxlzr** [comment]
Hi, have you solved your issue yet?
