### ISSUE TITLE
Does this framework support the Qwen model? 

### ISSUE THREAD

**Issue by ChrisXULC** [zjunlp/EasyEdit#29]
Hi.
Does this framework support the Qwen model? Or is there any plan to support them in the future? Thank you.

**Comment by pengzju** [comment]
Thank you for your attention, EasyEdit recently do not support Qwen, and we plan to support Qwen in the next version as soon as possible.

**Comment by zxlzr** [comment]
Hi, EasyEdit now has supported Qwen. If you have problems, please contact us.
