### ISSUE TITLE
Question about finetuning the backbone(mulitmodal editing)

### ISSUE THREAD

**Issue by yaohui120** [zjunlp/EasyEdit#293]
My understanding is that it does not need training when finetuning the last layer of the language model. In testing, we finetune the model from original weights on each sample. But in this way, the Reliability is about 10% and locality is about 100% when finetuning the self_attn, fc1, fc2 of the 31 layer of blip2. I want to know if there is misunderstanding. Thank you!

**Comment by tbozhong** [comment]
Thanks for your attention to our work!

We fine-tune the model on all samples for evaluation, rather than fine-tuning it on each sample.

**Comment by zxlzr** [comment]
hi, do you have any further questions?

**Comment by yaohui120** [comment]
Thank you! I will try again.
