### ISSUE TITLE
KeyError: 'Subject_Aliasing_acc'

### ISSUE THREAD

**Issue by CaiJichang212** [zjunlp/EasyEdit#294]
run `run_knowedit_llama2.py` with `Llama-2-7b` & `Wiki_recent_test`
> Traceback (most recent call last):
  File "EasyEdit/examples/run_knowedit_llama2.py", line 208, in <module>
    metrics, edited_model, _ = editor.edit(
  File "EasyEdit/easyeditor/editors/editor.py", line 171, in edit
    return self.edit_requests(requests, sequential_edit, verbose, **kwargs)
  File "EasyEdit/easyeditor/editors/editor.py", line 366, in edit_requests
    summary_metrics(all_metrics)
  File "EasyEdit/easyeditor/editors/utils.py", line 33, in summary_metrics
    [metric[eval][key][lkey] for metric in all_metrics])
  File "EasyEdit/easyeditor/editors/utils.py", line 33, in <listcomp>
    [metric[eval][key][lkey] for metric in all_metrics])
KeyError: 'Subject_Aliasing_acc'

**Comment by CaiJichang212** [comment]
![image](https://github.com/zjunlp/EasyEdit/assets/167088965/68ed4d6f-b45d-4145-9be2-8111af53f9a1)
1266th,in 'pre' dict,without 'Subject_Aliasing_acc'
![image](https://github.com/zjunlp/EasyEdit/assets/167088965/d4c1fac0-d805-4799-be1a-c3858f62f34b)
1265th and above,in 'pre' dict,with 'Subject_Aliasing_acc'

**Comment by XeeKee** [comment]
Do you mean that the data for item 1265 doesn't have Subject_Aliasing_acc in the 'pre' , but does have Subject_Aliasing_acc in the 'post' ?

**Comment by CaiJichang212** [comment]
in `Llama-2-7b-ms_recent_pre_edit.json`
`pre` 1266,
![image](https://github.com/zjunlp/EasyEdit/assets/167088965/7fdfc4b3-8433-40c9-8f74-ab730b2154a7)
`Subject_Aliasing_acc`only 629
![image](https://github.com/zjunlp/EasyEdit/assets/167088965/4212e472-fe12-483e-b248-f90137be6b1a)

**Comment by CaiJichang212** [comment]
this is relative issue [https://github.com/zjunlp/EasyEdit/issues/274#issue-2324392601]

**Comment by XeeKee** [comment]
Hello, Subject_Aliasing_acc is a metric under portability, and not all edited data have this. However, locality evaluates the model's locality, and every data point will have it. Our evaluation script has already handled cases where Subject_Aliasing_acc is missing. Could you please provide your eval function?

**Comment by CaiJichang212** [comment]
run run_knowedit_llama2.py with Llama-2-7b & Wiki_recent_test

> Traceback (most recent call last):
File "EasyEdit/examples/run_knowedit_llama2.py", line 208, in
metrics, edited_model, _ = editor.edit(
File "EasyEdit/easyeditor/editors/editor.py", line 171, in edit
return self.edit_requests(requests, sequential_edit, verbose, **kwargs)
File "EasyEdit/easyeditor/editors/editor.py", line 366, in edit_requests
**summary_metrics(all_metrics)**
File "EasyEdit/easyeditor/editors/utils.py", line 33, in summary_metrics
[metric[eval][key][lkey] for metric in all_metrics])
File "EasyEdit/easyeditor/editors/utils.py", line 33, in
**[metric[eval][key][lkey] for metric in all_metrics])**
KeyError: 'Subject_Aliasing_acc'

![image](https://github.com/zjunlp/EasyEdit/assets/167088965/b9ec94d9-0a24-4816-a449-600e2c311d86)

**Comment by CaiJichang212** [comment]
```python
def summary_metrics(all_metrics):
    if isinstance(all_metrics, dict):
        all_metrics = [all_metrics, ]
    logs_dir = './logs'
    if not os.path.exists(logs_dir):
        os.makedirs(logs_dir)
    output_file = os.path.join(logs_dir, 'results.json')
    with open(output_file, 'w') as f:
        json.dump(all_metrics, f, ensure_ascii=False, indent=4)

    mean_metrics = dict()
    for eval in ["pre", "post"]:
        mean_metrics[eval] = dict()
        for key in ["rewrite_acc", "rephrase_acc"]:
            if key in all_metrics[0][eval].keys():
                mean_metrics[eval][key] = np.mean([metric[eval][key] for metric in all_metrics])
        for key in ["locality", "portability"]:
            if key in all_metrics[0][eval].keys() and all_metrics[0][eval][key] != {}:
                mean_metrics[eval][key] = dict()
                for lkey in all_metrics[0][eval][key].keys():
                    if lkey.endswith("acc"):
                        mean_metrics[eval][key][lkey] = np.mean(
                            [metric[eval][key][lkey] for metric in all_metrics])
    # mean_metrics["time"] = np.mean([metric["time"] for metric in all_metrics])

    print("Metrics Summary: ", mean_metrics)
```

**Comment by CaiJichang212** [comment]
> Hello, Subject_Aliasing_acc is a metric under portability, and not all edited data have this. However, locality evaluates the model's locality, and every data point will have it. Our evaluation script has already handled cases where Subject_Aliasing_acc is missing. Could you please provide your eval function?

Looking forward to your reply

**Comment by CaiJichang212** [comment]
Thanks for fixing this bug with your updated code.
