### ISSUE TITLE
[BUG] GRACE editor with large eps.

### ISSUE THREAD

**Issue by leeve818** [zjunlp/EasyEdit#298]
Hi!
Thanks for your awesome framework!

I am now playing with GRACE on llama2 recently but I met some issue with trying with eps value larger than 100 while keeping other parameters unchanged.
The rewrite acc and F1 drops significantly. The key used to query in the codebook changes in one generation call with multiple model forward passes and thus the distance changes which is relevant to the eps.
This doesn't occur when editing on gpt2-xl model.

Could you please check this issus?

**Comment by pengzju** [comment]
Hi, I don't quite get what you mean. From my experience, increasing `eps` doesn't lead to a decrease in rewrite acc because a larger deferral radius should result in a higher hit probability. Additionally, could you please explain in detail what you mean by "The key used to query in the codebook changes"?

**Comment by zxlzr** [comment]
hi, could you please provide more details of your questions?

**Comment by pengzju** [comment]
I have fixed this issue (https://github.com/zjunlp/EasyEdit/commit/38c5c34d614646db14a45f59790434bc2f520c1b), please update EasyEdit and try again

**Comment by zxlzr** [comment]
Hi, do you have any further questions?

**Comment by leeve818** [comment]
Hi. I need to reopen this issue. I just tested the new version. The editing speed is 10x slower then the previous version. Is this normal? By the way, does GRACE here support batch editing?

**Comment by pengzju** [comment]
Q1: It's normal. I just set `n_iters` from 100 to 50. In addition, increasing `eps` will reduce some fine-tuning costs because more Keys are shared

Q2: Nope. plz refer to GRACE paper: https://arxiv.org/abs/2211.11031

**Comment by leeve818** [comment]
Thanks!
