### ISSUE TITLE
any model-edit performance of llama series LLMs?  

### ISSUE THREAD

**Issue by skykiseki** [zjunlp/EasyEdit#3]
As the Readme.md says, llama series LLMs are best supported. Is there any model-edit performance of llama series LLMs?

**Comment by pengzju** [comment]
Hello, the editing performance on llama was not tested in the original paper. Excitingly this work is underway and **will be open soon**(within a week).

**Comment by zxlzr** [comment]
Hi, we have released the paper "[EasyEdit: An Easy-to-use Knowledge Editing Framework for Large Language Models](https://arxiv.org/abs/2308.07269)" and reported the performance of editing LaMA2 with EasyEdit.

<img width="446" alt="image" src="https://github.com/zjunlp/EasyEdit/assets/1264492/8a91ea83-7ff8-4706-ab98-c6b8e26c42ca">
