### ISSUE TITLE
希望能同步一个gitee的镜像

### ISSUE THREAD

**Issue by lizhixi212** [zjunlp/EasyEdit#30]
这是我见到第一个非常全面详尽,优秀漂亮的大模型知识编辑的框架.
而且自从发布以来,你们还在不断更新,优化.
非常感谢你们的辛勤付出和杰出的共享.

你们的更新非常及时勤奋,但是国内代理不稳定,同步非常麻烦.
所以希望能同步一个gitee的镜像.
万分感谢.

**Comment by zxlzr** [comment]
感谢您对easyedit的关注，我们将在近期发布一个gitee 镜像。

**Comment by lizhixi212** [comment]
> 感谢您对easyedit的关注，我们将在近期发布一个gitee 镜像。

哇塞,非常感谢.

**Comment by zxlzr** [comment]
我们已添加gitee 镜像，会定期同步https://gitee.com/openkg/EasyEdit

**Comment by lizhixi212** [comment]
thanks very much!!!
