### ISSUE TITLE
SERAC的portability在edit之后降低了？

### ISSUE THREAD

**Issue by SXxinxiaosong** [zjunlp/EasyEdit#300]
llama+serac+zsre, portability在edit之后降低了，请问为什么会出现这种情况呢？
Metrics Summary:  {'pre': {'rewrite_acc': 0.40287348593761324, 'rephrase_acc': 0.39428592943539903, 'portability': {'one_hop_acc': 0.566645032103213}}, 'post': {'rewrite_acc': 0.993713550994168, 'rephrase_acc': 0.990426826468292, 'locality': {'neighborhood_acc': 1.0}, 'portability': {'one_hop_acc': 0.38730608993487514}}}

**Comment by XeeKee** [comment]
I think it's reasonable too. Serac replaces large models with smaller ones, so its logical reasoning ability will be somewhat weaker.

**Comment by zxlzr** [comment]
Hi, do you have any further questions?

**Comment by SXxinxiaosong** [comment]
但是large models的output使用的是编辑前的知识，按理说是不能输出正确答案的。

**Comment by XeeKee** [comment]
During prediction, we used the teacher forcing mechanism. For example, when predicting the third token of the label, the model can see the first two correct labels, which may result in the accuracy before editing not being zero.
https://github.com/zjunlp/EasyEdit/blob/d6ee11f583f8de2bfe8406339e1c59a392abc40d/easyeditor/evaluate/evaluate_utils.py#L126

**Comment by zxlzr** [comment]
Hi, do you have any further questions?

**Comment by SXxinxiaosong** [comment]
No thanks!

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月17日 21:19 |
| 收件人 | zjunlp/EasyEdit ***@***.***> |
| 抄送人 | xxs ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [zjunlp/EasyEdit] SERAC的portability在edit之后降低了？ (Issue #300) |

Hi, do you have any further questions?
