### ISSUE TITLE
run llama2 ROME error

### ISSUE THREAD

**Issue by dignfei** [zjunlp/EasyEdit#306]
![image](https://github.com/zjunlp/EasyEdit/assets/25482706/e9b05581-c289-44c9-852d-01a9a7455813)

code : 
`
cd examples
 python  run_zsre_llama2.py     --editing_method=ROME     --hparams_dir=../hparams/ROME/llama-7b     --data_dir=../data
`

**Comment by xzwyyd** [comment]
Thank you for reporting this issue to us. We are very sorry for the inconvenience caused by the bug in the updated code. After our emergency fix, the latest version just released has resolved this issue. We recommend that you update to the latest version and test if there are any issues.
