### ISSUE TITLE
TypeError: compute_edit_quality() missing 1 required positional argument: 'eval_metric'

### ISSUE THREAD

**Issue by lizhixi212** [zjunlp/EasyEdit#31]
当我把EasyEdit_Example_MEMIT_llama.ipynb中的模型修改为chatglm2-6b时,
![image](https://github.com/zjunlp/EasyEdit/assets/53890383/ed0587ac-9156-43fe-b107-a192b3e143dd)

出现如下bug:
![image](https://github.com/zjunlp/EasyEdit/assets/53890383/ccf08bb0-a705-4a4e-ab15-3a75305fd2cb)

**Comment by littlefive5** [comment]
Thanks for pointing out the error.
I have fixed it and please give it another try.
Leave message if you encounter other issues.

**Comment by lizhixi212** [comment]
Your response speed is also cool.

**Comment by pengzju** [comment]
If your problem has been resolved, please help close this issue.😊

**Comment by lizhixi212** [comment]
IndexError: index 11 is out of bounds for dimension 1 with size 7
![image](https://github.com/zjunlp/EasyEdit/assets/53890383/8403dbd9-ecc7-4510-9607-0c8bbbaf1500)
![image](https://github.com/zjunlp/EasyEdit/assets/53890383/212946a6-c7ed-446e-8a28-7a3f7fa106d3)
![image](https://github.com/zjunlp/EasyEdit/assets/53890383/35abff3a-1180-436c-a86c-e97f7abfb857)
![image](https://github.com/zjunlp/EasyEdit/assets/53890383/58fd8358-9661-4ea5-96c4-44b05d51c2ff)

maybe reason,in 'chaglm2-6b.yaml',
`model_name: "/home/lyc/TNTprojectz/LLM/huggingface/chatglm2-6b-32k"`
unsupport chatglm2-6b-32k version ?
or other reason?

**Comment by lizhixi212** [comment]
thanks for you prompt response,I am looking forward to the new version.
