### ISSUE TITLE
why need download  wiki ,  has 18G ？

### ISSUE THREAD

**Issue by dignfei** [zjunlp/EasyEdit#311]
![image](https://github.com/zjunlp/EasyEdit/assets/25482706/c8e3040a-8a86-46ef-b122-c00813b03adb)

It's too wasteful

**Comment by XeeKee** [comment]
Hello, the editing methods of ROME and MEMIT require using Wikipedia. I will upload a mirror source soon to facilitate downloads for users in mainland China.

**Comment by dignfei** [comment]
thanks

**Comment by XeeKee** [comment]
https://pan.baidu.com/s/1iFxsVu5gAD8r_kELfAbcBw?pwd=7jya
