### ISSUE TITLE
error when cache file  exist

### ISSUE THREAD

**Issue by dignfei** [zjunlp/EasyEdit#312]
![image](https://github.com/zjunlp/EasyEdit/assets/25482706/aa973110-6014-4946-9fa9-8fde916b09ad)
![image](https://github.com/zjunlp/EasyEdit/assets/25482706/cb1f3313-a7d9-4da1-8054-69c2d88d3b0d)

when file exists , ds = none ，then error

shell:
`cd examples`
`python run_zsre_llama2.py --editing_method=MEMIT --hparams_dir=../hparams/MEMIT/llama-7b --data_dir=../dataroot`

**Comment by dignfei** [comment]
What needs to be adjusted?

**Comment by XeeKee** [comment]
Please ensure that your filename is the correct path. You can print it out to check if the filename is the Wikipedia path.

**Comment by dignfei** [comment]
filename = PosixPath('data/stats/Llama-2-7b-chat-hf/wikipedia_stats/model.layers.4.mlp.down_proj_float32_mom2_100000.npz')
No code or cache files were altered by me. They were created automatically upon successful execution. However, when I run the program again, the error I previously described occurs.

**Comment by xzwyyd** [comment]
Hello, thank you for your feedback. We will review it thoroughly later and address it promptly. Thank you for your patience.

**Comment by XeeKee** [comment]
So you mean that you are sure that your ds is not a null value at this location: https://github.com/zjunlp/EasyEdit/blob/4f228d6cd4865facc2cf1cfd3e029e82a2cdc6fb/easyeditor/models/rome/layer_stats.py#L168

**Comment by zxlzr** [comment]
hi, do you have any further questions?
