### ISSUE TITLE
When will the WISE pipeline implementation be publicized?

### ISSUE THREAD

**Issue by wpwpwpyo** [zjunlp/EasyEdit#313]
At present, only the WISE class methods have been implemented, but how long will it take to implement the related processes for experimental reproduction?

**Comment by pengzju** [comment]
Theoretically, you only need to set `sequential_edit=True` and read 1K/3K data from ZsRE to reproduce the results. I will provide the data as soon as possible and include a README for the reproduction experiment.

Thanks 😊

**Comment by yjh576** [comment]
Do you mean that I just need to set `sequential_edit=True`, read 1K/3K data from ZsRE, and then execute the `run_zsre_llama2` command to achieve the WISE process for experimental reproduction?  I am looking forward to a WISE README for the reproduction experiment.

**Comment by pengzju** [comment]
Please refer to this README: https://github.com/zjunlp/EasyEdit/tree/main/easyeditor/models/wise

**Comment by yjh576** [comment]
Thanks for your reply!
