### ISSUE TITLE
关于portability和locality的评估具体应该怎么设置呢

### ISSUE THREAD

**Issue by exxaid** [zjunlp/EasyEdit#316]
我看很多示例里都没有portability和locality的评估

**Comment by zxlzr** [comment]
您好，请问您用的是什么数据集，有部分数据集没有这些指标，您可以参考具体示例跑代码。

**Comment by exxaid** [comment]
> 您好，请问您用的是什么数据集，有部分数据集没有这些指标，您可以参考具体示例跑代码。

用的是zsre数据集

**Comment by exxaid** [comment]
> 在我们上传的zsre数据集是有portability和locality的，在不同的文件夹下

好的谢谢

**Comment by zxlzr** [comment]
请问您还有其他问题吗？

**Comment by exxaid** [comment]
> 请问您还有其他问题吗？

没有了
