### ISSUE TITLE
使用mend预训练llama时出现的报错

### ISSUE THREAD

**Issue by exxaid** [zjunlp/EasyEdit#317]
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/data/qiaoshuofei/PLMs/llama-2-converted/7b-chat'. Use `repo_type` argument if needed.请问该如何解决

**Comment by XeeKee** [comment]
https://github.com/zjunlp/EasyEdit/tree/main/hparams/TRAINING/MEND在这个地方里面的model_name和tokenizer_name换成你本地的路径

**Comment by exxaid** [comment]
> [https://github.com/zjunlp/EasyEdit/tree/main/hparams/TRAINING/MEND在这个地方里面的model_name和tokenizer_name换成你本地的路径](https://github.com/zjunlp/EasyEdit/tree/main/hparams/TRAINING/MEND%E5%9C%A8%E8%BF%99%E4%B8%AA%E5%9C%B0%E6%96%B9%E9%87%8C%E9%9D%A2%E7%9A%84model_name%E5%92%8Ctokenizer_name%E6%8D%A2%E6%88%90%E4%BD%A0%E6%9C%AC%E5%9C%B0%E7%9A%84%E8%B7%AF%E5%BE%84)

好的，谢谢
