### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by SXxinxiaosong** [zjunlp/EasyEdit#318]
您好，有一个关于数据集的问题请教一下~
论文 Table 4 中ZsRE的结果是ZsRE-test-all.json上进行的实验吗? ZsRE-test-all共有1301条数据，Table 3的统计是1230？

**Comment by XeeKee** [comment]
您好，是在ZsRE-test-all.json上面进行的，我们会在近期更新一下数据介绍

**Comment by SXxinxiaosong** [comment]
好哒 谢谢！
