### ISSUE TITLE
counterfact数据结果

### ISSUE THREAD

**Issue by SXxinxiaosong** [zjunlp/EasyEdit#319]
您好，请问为什么在大表中没有counterfact数据集的性能比较，是出于什么考虑呢？

**Comment by XeeKee** [comment]
因为我们有wiki-counterfact数据集的实验结果

**Comment by SXxinxiaosong** [comment]
有两个问题请教一下：
1. 如果把读取的文件改成counterfact，是不是就可以评估了？
2.  27%|██▋       | 2660/10000 [13:57:58<40:38:56, 19.94s/it]  这是使用ROME编辑counterfact的进度条，耗时很长，这是正常的吗

**Comment by XeeKee** [comment]
1. 可以
2. 这地方并不是在进行编辑而是在算C，您可以在https://rome.baulab.info/data/stats/下载计算好的C，在https://github.com/zjunlp/EasyEdit/blob/6ce393c8ab64795394e77891dedf8d724977a2b0/hparams/ROME/gpt-j-6B.yaml#L3中换成本地路径即可

**Comment by SXxinxiaosong** [comment]
我是在用llama-2-7b-chat编辑，似乎https://rome.baulab.info/data/stats/中是GPT相关的C?

**Comment by XeeKee** [comment]
是的，那你需要等待了，或者你可以把mom2_adjustment设置为false

**Comment by SXxinxiaosong** [comment]
1. mom2_adjustment 会影响结果吗
2. 还有请问ROME和R-ROME的区别是什么呢?

**Comment by XeeKee** [comment]
https://pan.baidu.com/s/1iFxsVu5gAD8r_kELfAbcBw?pwd=7jya&_at_=1719341021014#list/path=%2F
这里有llama的
rome和r-rome的具体区别建议您去看r-rome的论文：Rebuilding ROME : Resolving Model Collapse during Model Editing

**Comment by littlefive5** [comment]
1. mom2_adjustment 在ROME中是依靠C作为约束进行最优化计算，如果设置为false则会忽略这个约束，结果会有一定的下降。
2. r-rome对原rome代码的k的计算进行了优化，具体请看原论文。

**Comment by SXxinxiaosong** [comment]
好哒，谢谢解答~

**Comment by SXxinxiaosong** [comment]
还有请问  表格中的评估是single-edit的结果吗

**Comment by littlefive5** [comment]
你好，是的 单条edit的结果。近期easyedit有较大的更新我们也会更新表格的结果。
