### ISSUE TITLE
Some questions about sequential editing

### ISSUE THREAD

**Issue by myt517** [zjunlp/EasyEdit#32]
First of all, thank you very much for your great work. In my opinion, the sequential editing mode of knowledge editing is more valuable for practical applications.

I have a few questions about sequential editing that I'd like answered:
(1) I see that single editing is implemented in the source code. If I want to implement sequential editing, do I only need to assign the edited_model in the following code to self.model?
<img width="437" alt="企业微信截图_16956984015422" src="https://github.com/zjunlp/EasyEdit/assets/49244727/008a5bcf-e437-4103-9c10-36a9bdeda744">

(2) Should the calculation of metrics for sequential editing be performed after all editing is completed?

Very much looking forward to your reply, thank you!

**Comment by pengzju** [comment]
Thank you for your attention. 😊
- Q1. You only need to set `keep_original_weight` to `False` for sequential editing, then each case will be edited based on the last edited model weights, not the original model weights.
    - In particular, note that `serac` is limited by VRAM, and too much sequential editing may result in OOM. `IKE` cannot perform sequential editing because IKE does not involve parameter updates.
- Q2. Yep, u r right! However, currently we only support editing performance evaluation for the current editing sample. Thankfully, you can get the `edited_model` after sequential editing and make a final evaluation.

**Comment by pengzju** [comment]
If your problem has been resolved, please help close this issue.😊
