### ISSUE TITLE
ROME Question

### ISSUE THREAD

**Issue by SXxinxiaosong** [zjunlp/EasyEdit#320]
当在整个counterfact数据集上进行编辑后，后面几千条数据的post_acc全为0，但是单独编辑时就能编辑成功？请问是什么原因呢？谢谢~
在一万条编辑时的部分输出：
Executing ROME algorithm for the update: [Azerbaijan is located in] -> [ Americas]
Computing left vector (u)...
Selected u projection object Azerbaijan
Left vector shape: torch.Size([11008])
Computing right vector (v)
Lookup index found: 5 | Sentence: Azerbaijan is located in Amer | Token: an
Rewrite layer is 5
Tying optimization objective to 31
Recording initial value of v*
loss 11.013 = 11.013 + 0.0 + 0.0 avg prob of [ Americas] 1.7819385902839713e-05
loss 11.013 = 11.013 + 0.0 + 0.0 avg prob of [ Americas] 1.7819622371462174e-05
loss 11.013 = 11.013 + 0.0 + 0.0 avg prob of [ Americas] 1.7819855202105828e-05
loss 11.013 = 11.013 + 0.0 + 0.0 avg prob of [ Americas] 1.78200971276965e-05
loss 11.013 = 11.013 + 0.0 + 0.0 avg prob of [ Americas] 1.782033359631896e-05
loss 11.013 = 11.013 + 0.0 + 0.0 avg prob of [ Americas] 1.7820560969994403e-05
loss 11.013 = 11.013 + 0.0 + 0.0 avg prob of [ Americas] 1.7820799257606268e-05
loss 11.012 = 11.012 + 0.0 + 0.0 avg prob of [ Americas] 1.7821037545218132e-05
loss 11.012 = 11.012 + 0.0 + 0.0 avg prob of [ Americas] 1.7821255823946558e-05
loss 11.012 = 11.012 + 0.0 + 0.0 avg prob of [ Americas] 1.7821490473579615e-05
2024-07-03 21:15:10,897 - easyeditor.editors.editor - INFO - 4001 editing: Azerbaijan is located in -> Americas  

 {'pre': {'rewrite_acc': [0.5], 'portability': {}}, 'case_id': 4001, 'requested_rewrite': {'prompt': 'Azerbaijan is located in', 'target_new': 'Americas', 'ground_truth': 'A', 'portability': {}, 'locality': {}, 'subject': 'Azerbaijan'}, 'post': {'rewrite_acc': [0.0], 'locality': {}, 'portability': {}}}
07/03/2024 21:15:10 - INFO - easyeditor.editors.editor -   4001 editing: Azerbaijan is located in -> Americas 

重新编辑1000条，这条数据在第一条时的输出：
 {'pre': {'rewrite_acc': [0.5], 'portability': {}}, 'case_id': 0, 'requested_rewrite': {'prompt': 'Azerbaijan is located in', 'target_new': 'Americas', 'ground_truth': 'A', 'portability': {}, 'locality': {}, 'subject': 'Azerbaijan'}, 'post': {'rewrite_acc': [1.0], 'locality': {}, 'portability': {}}}
 
 相关代码 ：
     hparams = ROMEHyperParams.from_hparams('./hparams/ROME/llama-7b.yaml')
    editor = BaseEditor.from_hparams(hparams)
    metrics, edited_model, _ = editor.edit(
        prompts=prompts,
        ground_truth=ground_truth,
        target_new=target_new,
        subject=subject,
        keep_original_weight=True,
        sequential_edit=False,
    )

**Comment by XeeKee** [comment]
We have also noticed this issue recently and are currently debugging. If there are any code updates, we will update the code promptly and inform you.

**Comment by littlefive5** [comment]
Sorry for being slow, we've been busy recently. Which model did you test? I would try to reproduce the results.

**Comment by SXxinxiaosong** [comment]
Llama2-7b-chat！
谢谢你们～
---- Replied Message ----
| From | Yunzhi ***@***.***> |
| Date | 07/18/2024 00:08 |
| To | zjunlp/EasyEdit ***@***.***> |
| Cc | xxs ***@***.***>,
Author ***@***.***> |
| Subject | Re: [zjunlp/EasyEdit] ROME Question (Issue #320) |

Sorry for being slow, we've been busy recently. Which model did you test? I would try to reproduce the results.

**Comment by tommaso-green** [comment]
@littlefive5 Also experiencing this issue. Any fixes yet?

**Comment by pengzju** [comment]
@SXxinxiaosong @tommaso-green 

Hi,

Sry for the late reply 😢. I hope everything has been going well. It seems that I have already fixed this issue in [this commit](https://github.com/zjunlp/EasyEdit/commit/2a9a5ec8319ca27d060a1681e5975017d5538001) (the bug was introduced during a code refactor). Are you still experiencing any problems? I recommend updating to the latest version of EasyEdit and trying again.

**Comment by pengzju** [comment]
Also: `keep_original_weight` is now deprecated. To enable continuous editing, you can set `sequential_edit=True` or `=False` for single editing

**Comment by zxlzr** [comment]
hi, do you have any further questions?

**Comment by SXxinxiaosong** [comment]
暂时没有了，谢谢！

---- Replied Message ----
| From | ***@***.***> |
| Date | 08/08/2024 22:56 |
| To | zjunlp/EasyEdit ***@***.***> |
| Cc | xxs ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [zjunlp/EasyEdit] ROME Question (Issue #320) |

hi, do you have any further questions?
