### ISSUE TITLE
[Evaluation Issues]:  T5 Results are really strange

### ISSUE THREAD

**Issue by domenicrosati** [zjunlp/EasyEdit#322]
I am doing a random 500 sample of edits from Counterfact and I am getting the following results.
FT for llama2-7b-chat seems off but mostly T5 results seem very bad. Can you check that the T5 evaluation code is working?
```
[
    {
        "model": "llama2-7b-chat",
        "method": "ft",
        "edit_success": 0.306047197640118,
        "rephrase_acc": 0.41076696165191745,
    },
    {
        "model": "llama2-7b-chat",
        "method": "serac",
        "edit_success": 0.995575221238938,
        "rephrase_acc": 0.6342182890855457,
    },
    {
        "model": "t5-small",
        "method": "ft",
        "edit_success": 0.052254428610133664,
        "rephrase_acc": 0.052254428754106234,
    },
    {
        "model": "t5-small",
        "method": "serac",
        "edit_success": 0.01774461055869487,
        "rephrase_acc": 0.010779436399687582,
    },
    {
        "model": "gpt2-xl",
        "method": "ft",
        "edit_success": 0.9652509652509652,
        "rephrase_acc": 0.4362934362934363,
    },
    {
        "model": "gpt2-xl",
        "method": "serac",
        "edit_success": 0.9388489208633094,
        "rephrase_acc": 0.38489208633093525,
    },
    {
        "model": "gpt2-xl",
        "method": "memit",
        "edit_success": 0.8115942028985508,
        "rephrase_acc": 0.5181159420289855,
    },
]

```

**Comment by XeeKee** [comment]
Thank you for your attention to EasyEdit. We will address this issue soon.

**Comment by xzwyyd** [comment]
Thank you for your attention to EasyEdit. Regarding the performance of Llama on FT, please check the `objective_optimization` setting in the [parameter file](https://github.com/zjunlp/EasyEdit/blob/main/hparams/FT/llama-7b.yaml#L20) and try changing it to `target_new`, as Llama's performance with `prompt_last` is generally subpar. As for the T5 model, could you confirm if you are using the `t5-small` model? I have tested `t5-small` and it performs as expected. Please update your code and try again. If the issue persists, feel free to ask any further questions. It would be helpful if you could provide the parameters and code so we can better assist you.

**Comment by zxlzr** [comment]
Hi, have you solve your issue yet?
