### ISSUE TITLE
Evaluation Question

### ISSUE THREAD

**Issue by SXxinxiaosong** [zjunlp/EasyEdit#323]
您好，代码中的评估应该是token 级别的准确率计算，请问怎么改成 exact match 的 0/1 评估呢？

**Comment by XeeKee** [comment]
If you need string-level matching, you should make modifications here: https://github.com/zjunlp/EasyEdit/blob/main/easyeditor/evaluate/evaluate_utils.py.

If it's just 0/1 evaluation, you can set all non-1 values to 0.

**Comment by SXxinxiaosong** [comment]
请问一下，你们使用token level的accuracy 是出于什么考虑呢？~

**Comment by XeeKee** [comment]
we follow [rome](https://github.com/kmeng01/rome)

**Comment by SXxinxiaosong** [comment]
Got it, thanks!
