### ISSUE TITLE
R-ROME has poor performance when using GPT2-xl

### ISSUE THREAD

**Issue by zhilu1** [zjunlp/EasyEdit#328]
I am working on the wiki_counterfact dataset provided by KnowEdit and noticed that R-ROME's Edit Success rate is only about 0.67 when using the gpt2-xl model, which is significantly lower than that of the original ROME. The locality and portability of R-ROME is also much lower.
However, when employing the llama-7b model, R-ROME outperforms ROME and its Edit Success rate reaches 0.98

The hyperparameters I used for R-ROME with the gpt2-xl model are an exact replica of those used by ROME with the same model. So I wonder if there is anything else I need to adjust to make R-ROME work in gpt2-xl?

**Comment by XeeKee** [comment]
Hello, thank you very much for your feedback. We have also identified this issue, and in my experiments, I found that GPT-2 XL also performs poorly on MEMIT. Adjusting the hyperparameters does not improve the results. I look forward to your feedback or further discussion.

**Comment by zxlzr** [comment]
Hi, maybe you can try MEMIT with other LLMs such as LLaMA, QWen. Do you have any further questions?
