### ISSUE TITLE
RuntimeError: Invalid device string: 'cuda:0,1'

### ISSUE THREAD

**Issue by lizhixi212** [zjunlp/EasyEdit#33]
when I run example MEMLT_llama.ipynb  
llama-7b.yaml as follow:
`device: 0,1`
bug
`RuntimeError: Invalid device string: 'cuda:0,1'`
Do EasyEdit support multi GPU for training?  
I only have 3090 24G,I am very looking forward this support.
thank you

**Comment by pengzju** [comment]
Thank you for your attention. EasyEdit does not currently support multi-GPU editing.
- My suggestion is that you can use device_map='auto', using the native model parallel of huggingface. You can refer here(https://huggingface.co/docs/accelerate/usage_guides/big_modeling) for learning device_map.
    - For example, to edit the llama, you should modify the code here. https://github.com/zjunlp/EasyEdit/blob/main/easyeditor/editors/editor.py#L73

**Comment by lizhixi212** [comment]
![image](https://github.com/zjunlp/EasyEdit/assets/53890383/07932682-59bb-441c-b27d-14643773b7f2)

**Comment by lizhixi212** [comment]
would you give some instructions,this is maybe not a simple coding work.
thank you again!

**Comment by pengzju** [comment]
- You should not set it to `device: 0,1,2`. 
- When you use `device_map`, `accelerator` will automatically assign devices to the model, you need to make sure that the input is on `cuda:0`. And the variables in the editing process are device consistent.
> This is not a small coding process 😊

**Comment by lizhixi212** [comment]
thank you

**Comment by pengzju** [comment]
If your problem has been resolved, please help close this issue.😊
