### ISSUE TITLE
what is the meaning of archive

### ISSUE THREAD

**Issue by huangfu170** [zjunlp/EasyEdit#332]
您好，我使用EasyEdit中的MEND方法，但我不太理解配置文件里的archive的含义是什么，应该如何设置，能不能麻烦您提示一下，以下是我使用的代码
`from easyeditor import KnowEditDataset
from easyeditor.models.mend.mend_hparams import MENDHyperParams
from easyeditor.trainer import EditTrainer
training_hparams = MENDHyperParams.from_hparams('/home/yxhuangfu/EasyEdit-main/hparams/MEND/gpt2-xl.yaml')
train_ds = KnowEditDataset('/home/yxhuangfu/EasyEdit-main/Wiki_recent/recent_train.json', config=training_hparams)
eval_ds = KnowEditDataset('/home/yxhuangfu/EasyEdit-main/Wiki_recent/recent_test.json', config=training_hparams)
trainer = EditTrainer(
    config=training_hparams,
    train_set=train_ds,
    val_set=eval_ds
)
trainer.run()`

**Comment by littlefive5** [comment]
Archive is the path of the trained hypernetwork. 
For training, you don't need it and for editing, just set it as the local path of the hypernetwork.

**Comment by zxlzr** [comment]
Hi, do you have any other questions?
