### ISSUE TITLE
Issue with KN batch editing 

### ISSUE THREAD

**Issue by xduan7** [zjunlp/EasyEdit#338]
First of all, thank you for this awesome toolkit. 

I have encountered an issue when I was trying to batch edit with KN on GPT 2:
```python
hparams = KNHyperParams.from_hparams("edit.yaml")
editor = BaseEditor.from_hparams(hparams)

prompts = ['Who is the architect for Toodyay Fire Station?', 'Who is Claire Clairmont\'s sister?',
           'Which fictional universe is Chlorophyll Kid part of?']
ground_truth = ['Ken Duncan', 'Mary Shelley', 'DC Universe']
target_new = ['Wong Tung & Sons', 'Clairmont-Mayer', 'Image Universe']

metrics, edited_model, _ = editor.batch_edit(
    prompts=prompts,
    ground_truth=ground_truth,
    target_new=target_new,
    keep_original_weight=False,
)
```

I got the following message: 
```text
  File ".../experiments/kn/gpt-2-xl/edit.py", line 29, in <module>
    metrics, edited_model, _ = editor.batch_edit(
  File ".../easyeditor/editors/editor.py", line 225, in batch_edit
    for k, v in weights_copy.items():
AttributeError: 'function' object has no attribute 'items'
```

It seems that the error comes from [this line](https://github.com/zjunlp/EasyEdit/blob/4a9a8a61cf4df2baaf3c47cc4992690de72978da/easyeditor/models/kn/kn_main.py#L12C5-L12C22), where the function returns a function instead of a copied weight in dict format like the other methods, e.g. the [fine-tuning method](https://github.com/zjunlp/EasyEdit/blob/4a9a8a61cf4df2baaf3c47cc4992690de72978da/easyeditor/models/ft/ft_main.py#L14).

Is there any solution to this issue? Thank you in advance.

**Comment by littlefive5** [comment]
Hello, KN does not support batch editing. It requires the location of the knowledge neurons for each input and edit it correpspondingly.
So we don't recommend you conduct batch editing with KN.

**Comment by xduan7** [comment]
Thank you for the explanation. It makes perfect sense. 

I was asking because according to the (`is_batchable_method` method)[https://github.com/zjunlp/EasyEdit/blob/a84c79396d8152762eefd3a4ea2b4787cb81a181/easyeditor/editors/batch_editor.py#L25], KN is a capable of batch editing. Again, thank you for the rapid reply.
