### ISSUE TITLE
Question about ZSRE experiment, how to reproduce results in your WISE paper? 

### ISSUE THREAD

**Issue by lliutianc** [zjunlp/EasyEdit#339]
Hi, 

I am testing the ZSRE task with WISE, MEMIT, and GRACE. But my results were different from yours in the paper. After checking the code, I still couldn't understand how current EasyEdit can utilize `loc_prompts`. As a result, from all methods I got pretty low locality scores. 

Below is my complete code: 

```
def load_data(args):
    # test_data = json.load(open(os.path.join(args.data_dir, 'zsre_mend_eval_portability_gpt4.json'), 'r', encoding='utf-8'))
    test_data = json.load(open(os.path.join(args.data_dir, 'zsre_mend_edit.json'), 'r', encoding='utf-8'))
    loc_data  = json.load(open(os.path.join(args.data_dir, 'zsre_mend_train.json'), 'r', encoding='utf-8'))

    if args.ds_size is not None:
        test_data = random.sample(test_data, args.ds_size)
        loc_data = loc_data[:args.ds_size]

    prompts = [test_data_['src'] for test_data_ in test_data]
    rephrase_prompts = [edit_data_['rephrase'] for edit_data_ in test_data]
    target_new = [edit_data_['alt'] for edit_data_ in test_data]

    locality_prompts = [edit_data_['loc'] for edit_data_ in test_data]
    locality_ans = [edit_data_['loc_ans'] for edit_data_ in test_data]
    locality_inputs = {
        'neighborhood':{
            'prompt': locality_prompts,
            'ground_truth': locality_ans
        },
    }

    portability_prompts = [edit_data_['portability']['New Question'] for edit_data_ in test_data]
    portability_ans = [edit_data_['portability']['New Answer'] for edit_data_ in test_data]
    portability_inputs = {
        'one_hop':{
            'prompt': portability_prompts,
            'ground_truth': portability_ans
        },
    }

    portability_inputs = None
    subject = [edit_data_['subject'] for edit_data_ in test_data]
    loc_prompts = [edit_data_['loc'] + ' ' + edit_data_['loc_ans'] for edit_data_ in loc_data]

    return prompts, rephrase_prompts, target_new, subject, locality_inputs, portability_inputs, loc_prompts


def main(args):

    if args.editing_method == 'FT':
        editing_hparams = FTHyperParams
    elif args.editing_method == 'IKE':
        editing_hparams = IKEHyperParams
    elif args.editing_method == 'KN':
        editing_hparams = KNHyperParams
    elif args.editing_method == 'MEMIT':
        editing_hparams = MEMITHyperParams
    elif args.editing_method == 'ROME':
        editing_hparams = ROMEHyperParams
    elif args.editing_method == 'LoRA':
        editing_hparams = LoRAHyperParams
    elif args.editing_method == 'WISE':
        editing_hparams = WISEHyperParams
    elif args.editing_method == "GRACE":
        editing_hparams = GraceHyperParams        
    elif args.editing_method == "ReFT":
        editing_hparams = ReFTHyperParams
    elif args.editing_method in ["MeFT", "SMeFT"]:
        # SMeFT shares the setting from MeFT
        editing_hparams = MeFTHyperParams
        args.hparams_dir = args.hparams_dir.replace("SMeFT", "MeFT")
    else:
        raise NotImplementedError

    hparams = editing_hparams.from_hparams(args.hparams_dir)
    hparams = editing_hparams.from_hparams(args.hparams_dir)
    if args.editing_method in ["MeFT", "SMeFT"]:
        hparams.alg_name = args.editing_method
    if args.editing_method == "SMeFT":
        hparams.smeft = args.smeft

    if "llama" in hparams.model_name.lower():
        hparams.model_name = "meta-llama/Llama-2-7b-hf"

    (
        prompts, rephrase_prompts, target_new, subject, locality_inputs, portability_inputs, loc_prompts
        ) = load_data(args)
    args.ds_size = len(prompts)

    output_folder = f"~/dev/edit/outputs/zsre_new"
    output_folder = os.path.expanduser(output_folder)
    os.makedirs(output_folder, exist_ok=True)

    edit_method_name = args.editing_method
    if args.editing_method == "SMeFT":
        edit_method_name += f"({args.smeft.replace('-', '')})"
    output_file = os.path.join(
        output_folder, 
        f'{hparams.model_name.split("/")[-1]}_{edit_method_name}_N={args.ds_size}B={args.bs_size}S={args.sequential_edit}R={"T" if args.reset_seq else "F"}.json'
        )

    print("See results at: ", output_file)

    if os.path.exists(output_file) is False or args.retrain:
        # Prepare pre-edit stat
        args.pre_file = os.path.join(output_folder, f"./{hparams.model_name.split('/')[-1]}_PRE_N={args.ds_size}.json") 
        if args.pre_file is not None and os.path.exists(args.pre_file):
            pre_edit = json.load(open(args.pre_file,'r'))
            assert len(pre_edit) == len(prompts)
        else:
            pre_edit = None

        if args.editing_method == 'IKE':
            train_data_path = os.path.join(args.data_dir, 'zsre_mend_train_10000.json')
            train_ds = ZsreDataset(train_data_path)
            sentence_model = SentenceTransformer(hparams.sentence_model_name).to(f'cuda:{hparams.device}')
            encode_ike_facts(sentence_model, train_ds, hparams)
        else:
            train_ds = None

        editor = BaseEditor.from_hparams(hparams)

        metrics, edited_model, _ = editor.edit(
            prompts=prompts,
            rephrase_prompts=rephrase_prompts,
            target_new=target_new,
            loc_prompts=loc_prompts,
            subject=subject,
            train_ds=train_ds,
            locality_inputs=locality_inputs,
            portability_inputs=portability_inputs,
            keep_original_weight=True,
            pre_file=args.pre_file,
            pre_edit=pre_edit,
            sequential_edit=(args.sequential_edit > 1),
            sequential_edit_size=args.sequential_edit,
            verbose=False,
            reset_seq=args.reset_seq, 
        )

        with open(output_file, 'w') as f:
            json.dump(metrics, f, indent=4)

        # json.dump(metrics, open(os.path.join(args.metrics_save_dir, f'{args.editing_method}_results.json'), 'w'), indent=4)

    with open(output_file, "r") as f:
        metrics = json.load(f)

    if len(metrics) > 0:
        summary_metrics(metrics)
```

I got following results when using T=1 (no sequence edit). 

WISE: 

Metrics Summary:  {'pre': {'rewrite_acc': 0.011500000000000002, 'rephrase_acc': 0.004, 'portability': {'one_hop_acc': 0.012619047619047618}}, 'post': {'rewrite_acc': 0.9975, 'rephrase_acc': 0.976, 'locality': {'neighborhood_acc': 0.24815370534178582}}}

GRACE: 

Metrics Summary:  {'pre': {'rewrite_acc': 0.011500000000000002, 'rephrase_acc': 0.004, 'portability': {'one_hop_acc': 0.012619047619047618}}, 'post': {'rewrite_acc': 0.9933333333333333, 'rephrase_acc': 0.0025, 'locality': {'neighborhood_acc': 0.4452706521204973}}}

MEMIT: 

Metrics Summary:  {'pre': {'rewrite_acc': 0.011500000000000002, 'rephrase_acc': 0.004, 'portability': {'one_hop_acc': 0.012619047619047618}}, 'post': {'rewrite_acc': 0.9398736263736265, 'rephrase_acc': 0.914349816849817, 'locality': {'neighborhood_acc': 0.16812631660851476}}}

**Comment by pengzju** [comment]
Hi,

It motivates me to put things together. Numerous past experiments have demonstrated that individual edits like ROME, MEMIT, and GRACE have good locality. 

However, I couldn't understand what was happening in your code. But please don't worry, I have improved the [README](https://github.com/zjunlp/EasyEdit/blob/main/examples/WISE.md) for the rerun experiments and provided the scripts(https://github.com/zjunlp/EasyEdit/blob/main/examples/run_wise_editing.py, https://github.com/zjunlp/EasyEdit/blob/main/examples/run_wise_editing.sh). You can follow my code to conduct the experiments. I have just tested it, and it can successfully run and reproduce the experimental results on the latest version of EasyEdit.

Best regards.

**Comment by zxlzr** [comment]
hi, have you solved your issue yet?

**Comment by lliutianc** [comment]
Thanks for providing the new instruction! 

I noted that the main difference was from the `eval_metric`: the default value was `exact match` instead of `token em`, but I haven't got time to dive into the details here. Can you share some idea about this setting? 

BTW, I am now able to achieve good locality from WISE and MEMIT, but for GRACE the locality was still lower than the results reported in the paper: I followed your setup and only tested with 3 samples. Both WISE and MEMIT achieved 100% locality. But GRACE result was only round 70%. Could you help confirm you could achieve 100% as well? 

Thanks again for your help!

**Comment by pengzju** [comment]
I will reply to you at weekday

**Comment by pengzju** [comment]
Hi,
Q1: Both token em and exact match are fine, and this is not important because the default setting calculates token-level accuracy, which is `exact match` (em). For the hallucination task, previous literature uses perplexity (ppl), so we follow this setting as well. Therefore, you don't need to worry about the first question and can proceed with the script I provided.

Q2: I experiment with GRACE and achieve 100% locality.

```json
{"post": {"rewrite_acc": 1.0, "rephrase_acc": 0.0, "locality": {"neighborhood_acc": 1.0}}}
```

 The 70% locality you mentioned might be because you use the same `pre_file` to evaluate locality. However, GRACE should have an independent `pre_file`. For more details, you can refer to [this issue comment](https://github.com/zjunlp/EasyEdit/issues/325#issuecomment-2226990985). You can try testing GRACE's performance without providing a `pre_file` (or new pre_file).

I understand you might be confused about the operation for Q2, but different editing methods have different perspectives, leading to different utilization methods. Therefore, I have to handle this special case.
Hope you can be tolerant. 

Best,

**Comment by lliutianc** [comment]
Got it. Thanks a lot for the information!
