### ISSUE TITLE
CCKS2024 ROME Question

### ISSUE THREAD

**Issue by zhengguanyu** [zjunlp/EasyEdit#343]
您好，关于CCKS2024复赛提交，我采用ROME生成了提交集，结果显示评测失败，我初步检查了提交集，与复赛提交示例一致。另外我试了FT和LoRA方法，均能提交成功，其提交集格式与ROME提交集也一致。请问这是什么情况？

ROME生成的提交集示例如下：

`{
        "pre": {
            "rewrite_ans": "天将降大任于是人也。\n\n\n\n\n",
            "rephrase_ans": "可以为天地立心，可以为生民立命。\n",
            "portability_ans": [
                "不患寡而患不均，不患贫而患不安。\n"
            ]
        },
        "case_id": 0,
        "requested_rewrite": {
            "prompt": "请填写下列古诗文的后一句：克己复礼为仁。一日克己复礼，",
            "target_new": "天下归仁焉。",
            "ground_truth": "其斯而已矣。",
            "portability": {
                "por_hop": {
                    "prompt": [
                        "请填写下列古诗文的前一句：天下归仁焉。"
                    ],
                    "ground_truth": [
                        "克己复礼为仁。一日克己复礼，"
                    ]
                }
            },
            "locality": {},
            "subject": "请填写下列古诗文的后一句：克己复礼为仁。一日克己复礼，",
            "rephrase_prompt": "下列古诗文的接下来一句是什么？克己复礼为仁。一日克己复礼，"
        },
        "post": {
            "rewrite_ans": "然后可以为天地立心， 为生民立命, 为往圣继绝学, 为万世开太平.\n",
            "rephrase_ans": "然后君子不怨天尤人。\n\n",
            "portability_ans": [
                "己所不欲， 勿施于人。\n\n\n"
            ],
            "fluency": {
                "ngram_entropy": 3.7360781194465966
            }
        }
    },`

**Comment by zxlzr** [comment]
请问您的问题解决了吗？

**Comment by zhengguanyu** [comment]
您好，还是没有解决。

**Comment by zhengguanyu** [comment]
我向任务负责人的邮箱发了邮件，并附上测试集，盼望回复

**Comment by JizhanFang** [comment]
你好，麻烦你到比赛钉钉群里找到我然后私聊我吧，我们一起看看是什么问题

**Comment by zxlzr** [comment]
> 我向任务负责人的邮箱发了邮件，并附上测试集，盼望回复

您好，比赛是我们组织的，您钉钉里直接交流即可

**Comment by zhengguanyu** [comment]
好的好的，非常感谢，抱歉麻烦您们啦！
