### ISSUE TITLE
Use EasyEdit with KnowEdit

### ISSUE THREAD

**Issue by Lastwish-1** [zjunlp/EasyEdit#346]
我在按照示例运行run_knowedit_llama2.py文件时发现当前文件目录下并无./hugging_cache/llama-2-7b这个路径，想请问您能否提供您利用KnowEdit这个数据集测试所用的llama-2-7b模型文件？

**Comment by Lastwish-1** [comment]
另外在您提供的edit.py示例中'./data/zsre_mend_eval_one_hop.json'这个路径的文件并没有给出下载方式，请问zsre_mend_eval_one_hop.json这个文件如何获取

**Comment by XeeKee** [comment]
问题1：llama2-7b模型太大了不可能传到仓库，您可以在huggingface上面下载模型然后自行制定路径
问题2：我貌似并没有在KnowEdit的md和py文件中找到zsre_mend_eval_one_hop.json，您想使用KnowEdit的数据集可以参考https://github.com/zjunlp/EasyEdit#dataset 和 https://github.com/zjunlp/EasyEdit/blob/main/examples/KnowEdit.md#dataset-structure

**Comment by zxlzr** [comment]
hi, have you solved your issue?

**Comment by Lastwish-1** [comment]
是的，非常感谢，上述问题已经解决。目前我想复现您团队在knowedit数据集上测试的结果。我另外有三个问题，麻烦您帮忙解惑：
1. 请问除了SERAC与MEND模型，其它编辑模型的训练应该怎么操作？
2. 我目前已经按照您提供的ROME示例，成功运行了run_knowedit_llama2.py文件，输出保存的结果文件并不是像您在knowedit.md文件在Performance部分所列结果表一样，给出了ROME模型的四个指标，请问怎么对输出结果文件进行处理可以复现相同的结果？
3. 在四个测试指标中，我并不清楚fluency指标在文件中对应的变量名。

**Comment by XeeKee** [comment]
1. 仅仅serac和mend需要训练，别的方法不需要训练
2. 给出的是个json文件，您可以查阅json文件
3. 之前版本更新了，test_generation没有默认开启，您需要https://github.com/zjunlp/EasyEdit/blob/fa09943dd022d169c598f8a59e6c5f1c023449d0/easyeditor/editors/editor.py#L180C9-L180C24中设置成true，这个地方我也会更新代码

**Comment by Lastwish-1** [comment]
不好意思，对于第二个问题我没有表述清楚，我之前已经查阅过result的json文件，但json文件中是对每一部分的prompt进行编辑前与编辑后测试返回的指标。我的疑惑在于最终比如由wiki_counterfact数据集编辑后在performance部分结果表中呈现的指标是所有部分指标值的平均值还是有经过其它处理得到的？

**Comment by XeeKee** [comment]
平均值

**Comment by Lastwish-1** [comment]
对于MEND和SERAC模型，KnowEdit框架中只在convsent数据集中提供了两种模型训练所需要的训练集和验证集，请问在您performance部分SERAC和MEND两种模型都是只经过convsent数据集进行训练然后对所有测试集进行编辑然后得到的指标么？
如果是这样，请问KnowEdit框架中其余数据的训练集在编辑测试中该怎么使用？

**Comment by XeeKee** [comment]
训练集用来训练
测试集测试训练后的编辑器的编辑效果
我们对每个数据集都用训练集训一个编辑器然后用测试集进行测试

**Comment by Lastwish-1** [comment]
可在您提供的knowedit数据集中，ZsRE并没有训练数据集。
其次根据您提供的训练示例：
training_hparams = MENDHyperParams.from_hparams('./hparams/MEND/llama-7b.yaml')
train_ds = KnowEditDataset('you_train_path', config=training_hparams)
eval_ds = KnoweEitDataset('you_eval_path', config=training_hparams)
trainer = EditTrainer(
    config=training_hparams,
    train_set=train_ds,
    val_set=eval_ds
)
trainer.run()
除convsent数据集外其余数据集并无验证集，请问对于其它数据集的训练，您原论文中使用的验证集是什么。特别的对于ZsRE数据集训练集该怎么获取。
最后是对于出SERAC和ROME两个需要训练的模型外，对于其余模型都是只需要直接利用测试集得到metrics么？

**Comment by Lastwish-1** [comment]
另外对于Convsent数据集，您提供的训练示例代码会报KeyError的错误，我对应源代码查询了一下，发现您在huggingface上提供的Convsent数据集当中并无subject或concept属性，且在KnowEdit.md文档中您也没有列出Convsent数据集的格式，请问您是怎么得到在Convsent数据集上训练测试的结果的呢？

**Comment by XeeKee** [comment]
1. 我们训练的时候没有使用验证集，验证集并非必须
2. zsre的训练集合是zsre_mend_train_10000(此处我们会更新readme)
3. 是的，别的方法都是在测试集得到的结果
4. 您跑Convsent数据集是按照readme使用的run_convsent_llama2.py吗，如果您需要训练convsent数据集需要参考 https://github.com/zjunlp/EasyEdit/blob/fa09943dd022d169c598f8a59e6c5f1c023449d0/examples/run_convsent_llama2.py#L137 处的代码

**Comment by XeeKee** [comment]
如果您有更多的疑问，欢迎添加我的微信进行更高效率的沟通
xi1786594371
