### ISSUE TITLE
Error calculation "adj_k" to edit LLAMA-3-8B using MEMIT

### ISSUE THREAD

**Issue by NangMayPhuLwin** [zjunlp/EasyEdit#347]
HI, 

I'm trying to edit the model on llamas-3-8b using MEMIT and I used the data provided in here [stats](https://github.com/zjunlp/EasyEdit/tree/main/examples#memit) 

However, I'm always stuck in here with 
`**adj_k = torch.linalg.solve(hparams.mom2_update_weight * cov.double() + layer_ks @ layer_ks.T,layer_ks )**`

```
COV torch.Size([11008, 11008])
layer_ks: torch.Size([14336, 8]), target: torch.Size([4096, 8])
hparams.mom2_update_weight 1500
```

The error:
Error: 
![image](https://github.com/user-attachments/assets/e77be7bc-71b0-420a-b324-4295f2e98cfb)

I tried to reshape, however, it still can't be resolved. Also dont see how it fixed in [#291](https://github.com/zjunlp/EasyEdit/issues/291)

**Comment by XeeKee** [comment]
We provide the stat for llama2-7b, but you are using the llama3-8b model, which might cause bugs. You can try to locally compute the stat for llama3-8b yourself.

**Comment by zxlzr** [comment]
Hi, do you have any further issues?

**Comment by NangMayPhuLwin** [comment]
Yes.. there's no issue when I tried with LLAMA-2 models. However, I want to use it for LLAMA-3 for some reason, but cannot compute the stats locally on A6000, and got `EOFError: Ran out of input`. still fixing.
is there any chance for LLAMA-3-8B in progress?
Thank you for your timely response.

**Comment by XeeKee** [comment]
Thank you for your attention. We will be completing the support for MEMIT on Llama 3 in the near future.
