### ISSUE TITLE
关于wise.py

### ISSUE THREAD

**Issue by zhengguanyu** [zjunlp/EasyEdit#349]
非常感谢工作的分享，很有启发！有两个问题想请教：

1. 观察到论文和代码中只复制了一个层的weight，请问有考虑过优化两个层的weight吗？比如` transformer.h[7].mlp.c_fc.weight`和`transformer.h[8].mlp.c_fc.weight`。如果想修改的话，主要在wise.py中修改吗？
2. 请问有考虑过引入bias吗？联合更新weight和bias

**Comment by pengzju** [comment]
1. WISE论文中通过单层MLP的激活来判定使用Main Memory/Side Memory。如果将知识存储在多层weight中，如何判定路由？因为涉及1个/多个MLP的召回，可能需要额外的检索组件。这是WISE的future work
2. 近来流行且广为使用的LLM，例如llama/mistral/qwen实际上都没有bias层，这似乎已经成为一种趋势。联合更新weight和bias是技术上可行的，你可以重写`new_weight_forward`。如果您一定要使用GPT2，我可以考虑添加联合更新 bias

**Comment by zhengguanyu** [comment]
好的，感谢回复！很有启发！

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
