### ISSUE TITLE
How to tune MEMIT's hyperparameters under thousands of edits?

### ISSUE THREAD

**Issue by henryoung217** [zjunlp/EasyEdit#35]
Thanks for your contribution and it really impresses me ! 
I want to use MEMIT method to inject thousands of edits into the language model, but in practical attempt, I found that injecting thousands of edits under the default hyperparameter setting would cause the model internal parameters to be totally corrupted (even only edit one layer), so I would like to ask if you have relevant experience in tuning MEMIT hyperparameter under large edit batch. Is it more effective to increase kl_factor or lower v_lr?
Looking forward to your early reply  !

**Comment by littlefive5** [comment]
Hi there! Could you be more specific about what you ran?
Have you employed the `batch_edit()` when you edit thousands knowledge simultaneously? 
Meanwhile, you should change the batch_size.

**Comment by henryoung217** [comment]
> Hi there! Could you be more specific about what you ran? Have you employed the `batch_edit()` when you edit thousands knowledge simultaneously? Meanwhile, you should change the batch_size.

I used **batch_edit()**, but I found that I didn't add the batch_size parameter to the yaml file, and I'll experiment further to see if it works.  Thank you for your reply !

**Comment by pengzju** [comment]
- The default batch_size is 1: https://github.com/zjunlp/EasyEdit/blob/main/easyeditor/models/memit/memit_hparams.py#L43
- You can add the `batch_size` field to yaml and use `batch_edit` function for batch editing

**Comment by Wenyueh** [comment]
Hello, I'm editing MEMIT on llama-7b and llama-13b models with thousands of edits. Is there any batch size that you recommend?
