### ISSUE TITLE
Question about edit performance

### ISSUE THREAD

**Issue by BUGLI27** [zjunlp/EasyEdit#359]
<img width="883" alt="image" src="https://github.com/user-attachments/assets/b1c3b9aa-deb0-4036-9caf-7cd780d576ee">
I'm confusing about the edit performance showed in README

- Is IKE and ICE the same method?
- Why do the results in two tables differ when using the llama-2-7b model and ZsRE dataset (eg. ROME)?

**Comment by zxlzr** [comment]
1 IKE and ICE is different method.

2 KnowEdit is constructed by re-organizing and extending exsiting datasests including WikiBio, ZsRE, WikiDataCounterfact, WikiDataRecent, convsent, Sanitation to make a comprehensive evaluation for knowledge editing. Special thanks to the builders and maintainers of the those datasets. You can find details at https://github.com/zjunlp/EasyEdit?tab=readme-ov-file#Dataset

**Comment by BUGLI27** [comment]
Thanks for your reply, Is there a brief introduction or paper available regarding the ICE method?
