### ISSUE TITLE
I met some problem when MMEdit

### ISSUE THREAD

**Issue by WangzcBruce** [zjunlp/EasyEdit#360]
已连接到 pydev 调试器(内部版本号 221.5787.24)09/02/2024 19:33:36 - INFO - easyeditor.trainer.BaseTrainer -   Config: SERACMultimodalTrainingHparams(qformer_name_or_path='bert-base-uncased', state_dict_file='hugging_cache/eva_vit_g.pth', coco_image='./', rephrase_image='./', name='lmsys/vicuna-7b-v1.5', model_name='minigpt4', model_class='Blip2OPT', small_name='lmsys/vicuna-7b-v1.5', tokenizer_class='LlamaTokenizer', tokenizer_name='lmsys/vicuna-7b-v1.5', cls_name='distilbert-base-cased', cls_class='AutoModel', inner_params=['llama_model.model.layers.29.mlp.down_proj.weight', 'llama_model.model.layers.29.mlp.up_proj.weight', 'llama_model.model.layers.30.mlp.down_proj.weight', 'llama_model.model.layers.30.mlp.up_proj.weight', 'llama_model.model.layers.31.mlp.down_proj.weight', 'llama_model.model.layers.31.mlp.up_proj.weight'], archive=None, alg='SERAC_MULTI', lr=1e-05, edit_lr=0.01, seed=0, lr_lr=0.0, cedit=0.1, iedit=0.1, cloc=1.0, cbase=1.0, dropout=0.0, final_eval=True, supervised=False, train_base=False, no_grad_layers=None, soft_weighting=False, checkpoint_grad=False, cross_attend=False, cos=False, freeze=None, square=True, bound_embeds=False, use_all_negatives=False, freeze_cntr=False, dist_heads=1, lora=None, results_dir='./results', device=0, batch_size=1, model_save_pt=5000, edit_bs=1, silent=False, log_interval=200, val_interval=5000, early_stop_patience=30000, early_stop_key='loss/total_edit_val', eval_only=False, half=False, save=False, debug=False, log_errors=False, unlikelihood=True, val_batch_size=1, accumulate_bs=1, val_steps=1000, opt='Adam', grad_clip=100.0, qformer_checkpoint='hugging_cache/blip2_pretrained_flant5xxl.pth', exact_match=True, max_length=32, model_parallel=False, freeze_qformer=True, max_epochs=None, max_iters=20000, pretrained_ckpt='hugging_cache/pretrained_minigpt4_7b.pth')
/home/tianyu/miniconda3/envs/EasyEdit/lib/python3.9/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Loading VIT
Position interpolate from 16x16 to 26x26
freeze vision encoder
Loading VIT Done
Loading Q-Former
Some weights of BertLMHeadModel were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['bert.encoder.layer.0.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.0.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.0.crossattention.output.dense.bias', 'bert.encoder.layer.0.crossattention.output.dense.weight', 'bert.encoder.layer.0.crossattention.self.key.bias', 'bert.encoder.layer.0.crossattention.self.key.weight', 'bert.encoder.layer.0.crossattention.self.query.bias', 'bert.encoder.layer.0.crossattention.self.query.weight', 'bert.encoder.layer.0.crossattention.self.value.bias', 'bert.encoder.layer.0.crossattention.self.value.weight', 'bert.encoder.layer.0.intermediate_query.dense.bias', 'bert.encoder.layer.0.intermediate_query.dense.weight', 'bert.encoder.layer.0.output_query.LayerNorm.bias', 'bert.encoder.layer.0.output_query.LayerNorm.weight', 'bert.encoder.layer.0.output_query.dense.bias', 'bert.encoder.layer.0.output_query.dense.weight', 'bert.encoder.layer.1.intermediate_query.dense.bias', 'bert.encoder.layer.1.intermediate_query.dense.weight', 'bert.encoder.layer.1.output_query.LayerNorm.bias', 'bert.encoder.layer.1.output_query.LayerNorm.weight', 'bert.encoder.layer.1.output_query.dense.bias', 'bert.encoder.layer.1.output_query.dense.weight', 'bert.encoder.layer.10.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.10.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.10.crossattention.output.dense.bias', 'bert.encoder.layer.10.crossattention.output.dense.weight', 'bert.encoder.layer.10.crossattention.self.key.bias', 'bert.encoder.layer.10.crossattention.self.key.weight', 'bert.encoder.layer.10.crossattention.self.query.bias', 'bert.encoder.layer.10.crossattention.self.query.weight', 'bert.encoder.layer.10.crossattention.self.value.bias', 'bert.encoder.layer.10.crossattention.self.value.weight', 'bert.encoder.layer.10.intermediate_query.dense.bias', 'bert.encoder.layer.10.intermediate_query.dense.weight', 'bert.encoder.layer.10.output_query.LayerNorm.bias', 'bert.encoder.layer.10.output_query.LayerNorm.weight', 'bert.encoder.layer.10.output_query.dense.bias', 'bert.encoder.layer.10.output_query.dense.weight', 'bert.encoder.layer.11.intermediate_query.dense.bias', 'bert.encoder.layer.11.intermediate_query.dense.weight', 'bert.encoder.layer.11.output_query.LayerNorm.bias', 'bert.encoder.layer.11.output_query.LayerNorm.weight', 'bert.encoder.layer.11.output_query.dense.bias', 'bert.encoder.layer.11.output_query.dense.weight', 'bert.encoder.layer.2.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.2.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.2.crossattention.output.dense.bias', 'bert.encoder.layer.2.crossattention.output.dense.weight', 'bert.encoder.layer.2.crossattention.self.key.bias', 'bert.encoder.layer.2.crossattention.self.key.weight', 'bert.encoder.layer.2.crossattention.self.query.bias', 'bert.encoder.layer.2.crossattention.self.query.weight', 'bert.encoder.layer.2.crossattention.self.value.bias', 'bert.encoder.layer.2.crossattention.self.value.weight', 'bert.encoder.layer.2.intermediate_query.dense.bias', 'bert.encoder.layer.2.intermediate_query.dense.weight', 'bert.encoder.layer.2.output_query.LayerNorm.bias', 'bert.encoder.layer.2.output_query.LayerNorm.weight', 'bert.encoder.layer.2.output_query.dense.bias', 'bert.encoder.layer.2.output_query.dense.weight', 'bert.encoder.layer.3.intermediate_query.dense.bias', 'bert.encoder.layer.3.intermediate_query.dense.weight', 'bert.encoder.layer.3.output_query.LayerNorm.bias', 'bert.encoder.layer.3.output_query.LayerNorm.weight', 'bert.encoder.layer.3.output_query.dense.bias', 'bert.encoder.layer.3.output_query.dense.weight', 'bert.encoder.layer.4.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.4.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.4.crossattention.output.dense.bias', 'bert.encoder.layer.4.crossattention.output.dense.weight', 'bert.encoder.layer.4.crossattention.self.key.bias', 'bert.encoder.layer.4.crossattention.self.key.weight', 'bert.encoder.layer.4.crossattention.self.query.bias', 'bert.encoder.layer.4.crossattention.self.query.weight', 'bert.encoder.layer.4.crossattention.self.value.bias', 'bert.encoder.layer.4.crossattention.self.value.weight', 'bert.encoder.layer.4.intermediate_query.dense.bias', 'bert.encoder.layer.4.intermediate_query.dense.weight', 'bert.encoder.layer.4.output_query.LayerNorm.bias', 'bert.encoder.layer.4.output_query.LayerNorm.weight', 'bert.encoder.layer.4.output_query.dense.bias', 'bert.encoder.layer.4.output_query.dense.weight', 'bert.encoder.layer.5.intermediate_query.dense.bias', 'bert.encoder.layer.5.intermediate_query.dense.weight', 'bert.encoder.layer.5.output_query.LayerNorm.bias', 'bert.encoder.layer.5.output_query.LayerNorm.weight', 'bert.encoder.layer.5.output_query.dense.bias', 'bert.encoder.layer.5.output_query.dense.weight', 'bert.encoder.layer.6.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.6.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.6.crossattention.output.dense.bias', 'bert.encoder.layer.6.crossattention.output.dense.weight', 'bert.encoder.layer.6.crossattention.self.key.bias', 'bert.encoder.layer.6.crossattention.self.key.weight', 'bert.encoder.layer.6.crossattention.self.query.bias', 'bert.encoder.layer.6.crossattention.self.query.weight', 'bert.encoder.layer.6.crossattention.self.value.bias', 'bert.encoder.layer.6.crossattention.self.value.weight', 'bert.encoder.layer.6.intermediate_query.dense.bias', 'bert.encoder.layer.6.intermediate_query.dense.weight', 'bert.encoder.layer.6.output_query.LayerNorm.bias', 'bert.encoder.layer.6.output_query.LayerNorm.weight', 'bert.encoder.layer.6.output_query.dense.bias', 'bert.encoder.layer.6.output_query.dense.weight', 'bert.encoder.layer.7.intermediate_query.dense.bias', 'bert.encoder.layer.7.intermediate_query.dense.weight', 'bert.encoder.layer.7.output_query.LayerNorm.bias', 'bert.encoder.layer.7.output_query.LayerNorm.weight', 'bert.encoder.layer.7.output_query.dense.bias', 'bert.encoder.layer.7.output_query.dense.weight', 'bert.encoder.layer.8.crossattention.output.LayerNorm.bias', 'bert.encoder.layer.8.crossattention.output.LayerNorm.weight', 'bert.encoder.layer.8.crossattention.output.dense.bias', 'bert.encoder.layer.8.crossattention.output.dense.weight', 'bert.encoder.layer.8.crossattention.self.key.bias', 'bert.encoder.layer.8.crossattention.self.key.weight', 'bert.encoder.layer.8.crossattention.self.query.bias', 'bert.encoder.layer.8.crossattention.self.query.weight', 'bert.encoder.layer.8.crossattention.self.value.bias', 'bert.encoder.layer.8.crossattention.self.value.weight', 'bert.encoder.layer.8.intermediate_query.dense.bias', 'bert.encoder.layer.8.intermediate_query.dense.weight', 'bert.encoder.layer.8.output_query.LayerNorm.bias', 'bert.encoder.layer.8.output_query.LayerNorm.weight', 'bert.encoder.layer.8.output_query.dense.bias', 'bert.encoder.layer.8.output_query.dense.weight', 'bert.encoder.layer.9.intermediate_query.dense.bias', 'bert.encoder.layer.9.intermediate_query.dense.weight', 'bert.encoder.layer.9.output_query.LayerNorm.bias', 'bert.encoder.layer.9.output_query.LayerNorm.weight', 'bert.encoder.layer.9.output_query.dense.bias', 'bert.encoder.layer.9.output_query.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
load checkpoint from hugging_cache/blip2_pretrained_flant5xxl.pth
freeze Qformer
Loading Q-Former Done
Loading LLAMA
Loading checkpoint shards:   0%|                          | 0/2 [00:00<?, ?it/s]/home/tianyu/miniconda3/envs/EasyEdit/lib/python3.9/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Loading checkpoint shards: 100%|██████████████████| 2/2 [00:09<00:00,  4.84s/it]
/home/tianyu/miniconda3/envs/EasyEdit/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:567: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/home/tianyu/miniconda3/envs/EasyEdit/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:572: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/home/tianyu/miniconda3/envs/EasyEdit/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:567: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/home/tianyu/miniconda3/envs/EasyEdit/lib/python3.9/site-packages/transformers/generation/configuration_utils.py:572: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
Loading LLAMA Done
Load BLIP2-LLM Checkpoint: hugging_cache/pretrained_minigpt4_7b.pth
09/02/2024 19:46:31 - INFO - easyeditor.trainer.models -   Set 167 dropout modules to p=0.0
09/02/2024 19:46:31 - INFO - easyeditor.trainer.BaseTrainer -   Loading class SERAC_MULTI from module <class 'easyeditor.trainer.algs.SERAC.SERAC_MULTI'>
09/02/2024 19:46:33 - INFO - easyeditor.trainer.utils -   Set 13 dropout modules to p=0.0
Loading checkpoint shards: 100%|██████████████████| 2/2 [00:10<00:00,  5.16s/it]
09/02/2024 19:46:46 - INFO - easyeditor.trainer.utils -   Set 0 dropout modules to p=0.0
09/02/2024 19:47:52 - INFO - easyeditor.trainer.BaseTrainer -   Building optimizer <class 'torch.optim.adam.Adam'> with lr 1e-05
09/02/2024 19:48:13 - INFO - easyeditor.trainer.utils -   Skipping grad accumulation because inf: False nan: True
09/02/2024 19:48:16 - INFO - easyeditor.trainer.utils -   Skipping grad accumulation because inf: False nan: True
09/02/2024 19:48:20 - INFO - easyeditor.trainer.utils -   Skipping grad accumulation because inf: False nan: True
09/02/2024 19:48:23 - INFO - easyeditor.trainer.utils -   Skipping grad accumulation because inf: False nan: True
09/02/2024 19:48:28 - INFO - easyeditor.trainer.utils -   Skipping grad accumulation because inf: False nan: True
09/02/2024 19:48:31 - INFO - easyeditor.trainer.utils -   Skipping grad accumulation because inf: False nan: True
09/02/2024 19:48:35 - INFO - easyeditor.trainer.utils -   Skipping grad accumulation because inf: False nan: True
09/02/2024 19:48:38 - INFO - easyeditor.trainer.utils -   Skipping grad accumulation because inf: False nan: True
09/02/2024 19:48:41 - INFO - easyeditor.trainer.utils -   Skipping grad accumulation because inf: False nan: True
09/02/2024 19:48:45 - INFO - easyeditor.trainer.utils -   Skipping grad accumulation because inf: False nan: True
09/02/2024 19:48:48 - INFO - easyeditor.trainer.utils -   Skipping grad accumulation because inf: False nan: True
09/02/2024 19:48:51 - INFO - easyeditor.trainer.utils -   Skipping grad accumulation because inf: False nan: True
09/02/2024 19:48:55 - INFO - easyeditor.trainer.utils -   Skipping grad accumulation because inf: False nan: True
09/02/2024 19:49:02 - INFO - easyeditor.trainer.utils -   Skipping grad accumulation because inf: False nan: True
09/02/2024 19:49:06 - INFO - easyeditor.trainer.utils -   Skipping grad accumulation because inf: False nan: True

code:
--------------------------------
from easyeditor import BaseEditor, MultimodalTrainer, MultimodalEditor
from easyeditor import CaptionDataset, VQADataset
from easyeditor import MENDMultimodalTrainingHparams, SERACMultimodalTrainingHparams, IKEMultimodalHyperParams, \
    MENDMultimodalHparams \
    , SERACMultimodalHparams
training_hparams = SERACMultimodalTrainingHparams.from_hparams('hparams/TRAINING/SERAC/minigpt4.yaml')
train_ds = CaptionDataset('data/caption_train_edit.json', config=training_hparams)
eval_ds = CaptionDataset('data/caption_eval_edit.json', config=training_hparams)
trainer = MultimodalTrainer(
    config=training_hparams,
    train_set=train_ds,
    val_set=eval_ds
)

trainer.run()
------------------------------------------------------------
config:
----------------------------------------------------
# Model
device: 0

name: lmsys/vicuna-7b-v1.5
model_name: minigpt4
model_class: Blip2OPT
small_name: lmsys/vicuna-7b-v1.5
tokenizer_class: LlamaTokenizer
tokenizer_name: lmsys/vicuna-7b-v1.5
cls_name: distilbert-base-cased 
cls_class: AutoModel 
inner_params:
- llama_model.model.layers.29.mlp.down_proj.weight
- llama_model.model.layers.29.mlp.up_proj.weight
- llama_model.model.layers.30.mlp.down_proj.weight
- llama_model.model.layers.30.mlp.up_proj.weight
- llama_model.model.layers.31.mlp.down_proj.weight
- llama_model.model.layers.31.mlp.up_proj.weight

# Method
alg: SERAC_MULTI
alg_name: SERAC_MULTI
lr: 1e-5
edit_lr: 1e-2
seed: 0
lr_lr: 0.0
cedit: 0.1
iedit: 0.1
cloc: 1.0
cbase: 1.0
dropout: 0.0
final_eval: True
supervised: False
train_base: False
no_grad_layers: null
soft_weighting: False
checkpoint_grad: False
cross_attend: False
cos: False
freeze: null
square: True
bound_embeds: False
use_all_negatives: False
freeze_cntr: False
dist_heads: 1
lora: null
archive: results/models/SERAC_MULTI/minigpt4-caption

batch_size: 1
model_save_pt: 1000
edit_bs: 1
silent: False
#max_epochs: 1
max_iters: 50000
log_interval: 200
val_interval: 5000
early_stop_patience: 30000
early_stop_key: "loss/total_edit_val"
eval_only: True
half: False
save: False
debug: False
log_errors: False
unlikelihood: True

exact_match: False 
val_batch_size: 1
accumulate_bs: 1
val_steps: 1000
opt: Adam
grad_clip: 100.

# Output
results_dir: ./results

# Multimodal
qformer_checkpoint: hugging_cache/blip2_pretrained_flant5xxl.pth
qformer_name_or_path: bert-base-uncased
state_dict_file: hugging_cache/eva_vit_g.pth
pretrained_ckpt: hugging_cache/pretrained_minigpt4_7b.pth

# image
coco_image: ../
rephrase_image: ../

**Comment by cheng-siyuan** [comment]
I appreciate your interest in our work. The issue you're encountering is a 'NaN' error, which can arise for various reasons. I recommend that you first verify whether your data is normal or not. Additionally, it may be necessary to pinpoint where the 'NaN' error occurs and assess if the loss is normal. The 'NaN' error could also be a result of precision overflow. I hope my suggestions are helpful to you.

**Comment by WangzcBruce** [comment]
In face, i set the wrong name of the model Vicuna(name: lmsys/vicuna-7b-v1.5).
By the way, how to train in four 4090 GPUS? It seems to need over 50G for the multimodal large model's editing.

**Comment by cheng-siyuan** [comment]
If you cannot edit models above 7B parameters, we suggest you try to employ smaller multimodal models. You can go to the huggingface model repository to find models around 2B.

**Comment by zxlzr** [comment]
Hi, have you solved your issue yet?
