### ISSUE TITLE
out of memory. Can I run multimodal_edit.py with multi-Gpus?

### ISSUE THREAD

**Issue by lissaaymk** [zjunlp/EasyEdit#362]
I want to run train_MEND_MiniGPT4_VQA() and train_SERAC_MiniGPT4_VQA() in multimodal_edit.py. VRAM of one RTX4090 is 23.65GB. It is not enough. I  have eight RTX4090. I want to know how I run train_MEND_MiniGPT4_VQA() and train_SERAC_MiniGPT4_VQA()  with multi-Gpus?  
![image](https://github.com/user-attachments/assets/1ccb1409-93a4-41f6-9ce0-43d566ba04eb)

**Comment by cheng-siyuan** [comment]
Thank you for your interest in our work. In the future, we plan to adapt the multimodal model editing to accommodate multi-GPUs. However, the issue of multi-GPUs editing backpropagation in single-modal scenarios within MEND has yet to be resolved, making multimodal adaptation currently unfeasible. serac, ike, etc. will be supported in the future.

**Comment by zxlzr** [comment]
hi, have you solved your issue yet?

**Comment by lissaaymk** [comment]
I am trying to use DeepSpeed to solve this problem.  But it doesn't seem to work. Could you give me some suggestions?

**Comment by cheng-siyuan** [comment]
I am sorry that we haven't attempted this at present, and thus we may not be able to provide you with a helpful suggestion.

**Comment by zxlzr** [comment]
hi,  have you solved your issue yet?
