### ISSUE TITLE
Edit return the unmodified model weights

### ISSUE THREAD

**Issue by LuckMonkeys** [zjunlp/EasyEdit#363]
Hello, thank you for the fantastic work on this project. I encountered a potential issue with the `ROME` edition when `copy=False` and `sequential_edit=False`. Specifically, during the execution of `BaseEditor:edit_requests()`,  I noticed that the function can return the unmodified model weights in certain scenarios.
https://github.com/zjunlp/EasyEdit/blob/e8bb5c145a764216de244c8384d4b3a075ba23ae/easyeditor/editors/editor.py#L351-L353

When `copy=False`, both `self.model` and `edited_model` refer to the same object. If `self.model` is later reverted to the unmodified weights (`weights_copy`), this change also affects `edited_model`, as they share the same reference.

To prevent this behavior, would it consider to set `copy=True` by default? This would ensure that `edited_model` remains independent of `self.model` and preserves the intended changes without being reverted.

**Comment by XeeKee** [comment]
Thank you very much for your interest in EasyEdit. Currently, EasyEdit focuses on single-edit scenarios, so we set the default for copy to false. The reason we chose this approach instead of reloading the model is that it reduces the number of I/O operations, which can significantly improve time efficiency when performing a large number of single edits on a dataset.

**Comment by LuckMonkeys** [comment]
Thank you for your quick reply! If `copy=False`, would it be possible to avoid assigning `weights_copy` to `self.model` in the final edit request? This would ensure that the returned `edited_model` retains the modified parameters.

**Comment by zxlzr** [comment]
We have developed a new method for lifelong (continue) editing https://arxiv.org/abs/2405.14768  and you can try it here： https://github.com/zjunlp/EasyEdit/blob/main/examples/WISE.md

**Comment by LuckMonkeys** [comment]
Thank you for your reply and for introducing the new edit method. I will go ahead and close the issue.
