### ISSUE TITLE
Issue regarding the Wise model in a multi-GPU environment

### ISSUE THREAD

**Issue by Eliaukyh** [zjunlp/EasyEdit#367]
I would like to ask how to run the Wise method to edit LLaMA2 in a multi-GPU setup. I followed the settings mentioned in other issues, setting the device to 0 and CUDA_VISIBLE_DEVICES='0,1', but this didn't work.

I look forward to your reply. Thank u.

**Comment by pengzju** [comment]
I have supported Multi-GPU for WISE: https://github.com/zjunlp/EasyEdit/commit/465f8d8b207661b0b6c687715a014d209ead6e48

**Comment by zxlzr** [comment]
Hi, have you solved your issue yet?

**Comment by Eliaukyh** [comment]
The issue has been solved, thank you very much for your reply!
 I have no further questions and would like to close the issue.
