### ISSUE TITLE
如何保存编辑后的模型？

### ISSUE THREAD

**Issue by SXxinxiaosong** [zjunlp/EasyEdit#368]
metrics, edited_model, _ = editor.edit(
        prompts=prompts,
        rephrase_prompts=rephrase_prompts,
        target_new=target_new,
        subject=subjects,
        locality_inputs=locality_inputs,
        portability_inputs=portability_inputs,
        train_ds=train_ds,
        sequential_edit=True,
        pre_file=args.pre_file,
        pre_edit = pre_edit,
        test_generation=True,

    )
    
    请问，如何保存编辑后的模型，（不保存整个模型的情况下，只保留修改或添加的部分），以及如何重新加载？

**Comment by XeeKee** [comment]
我们没有正对修改后的参数进行单独编写，您可能需要保存下整个模型，因为像wise，grace，serac，melo是添加额外参数的。
像rome这种直接对模型参数进行修改的方法，您可以参考
https://github.com/zjunlp/EasyEdit/blob/63952a2df613933fb51b2ab0f7435f85bfb61dc1/easyeditor/models/rome/rome_main.py#L41
这个地方有涉及到保存修改后的参数，您可以自行编写代码

**Comment by zxlzr** [comment]
hi, do you have any further questions?

**Comment by SXxinxiaosong** [comment]
好的 谢谢
