### ISSUE TITLE
WISE的loc_prompts

### ISSUE THREAD

**Issue by SXxinxiaosong** [zjunlp/EasyEdit#372]
用wise编辑wiki_counterfact，训练过程的loc_prompts是否可以用zsre_train中的loc？

**Comment by pengzju** [comment]
感谢您的提问，首先您这个问题的答案是否定的。在我最近的实验中发现wise在counterfact数据集上表现较差(原paper中我们follow GRACE的设置，未在这个数据集上测试)，可能的原因是counterfact数据集的`edit_prompt`和`neightborhood_prompt`在语义上非常接近，这会使得WISE的gate失去分类作用。

如果一定要在counteract上验证持续编辑的表现，请直接使用train_set中的neightborhood_prompt，但正如上面说的效果可能会大打折扣。

**Comment by zxlzr** [comment]
请问您还有其他问题吗？
