### ISSUE TITLE
device使用不规范

### ISSUE THREAD

**Issue by scut-xz** [zjunlp/EasyEdit#373]
![image](https://github.com/user-attachments/assets/2f51b5a5-ca02-4046-832a-e0c7c7460122)
代码中device是0，1，2，3等数字参数，使用的时候应该统一规范为”.to(f"cuda:{device}")“形式
直接使用to(device)形式会报下面的错误
![image](https://github.com/user-attachments/assets/98b91760-13fb-4b3e-871d-b8295cc7923f)
代码中存在多处这种情况，希望能尽快修改

**Comment by XeeKee** [comment]
非常感谢您对easyedit的关注，已经更新了代码。
