### ISSUE TITLE
How to save and load WISE models?

### ISSUE THREAD

**Issue by shash42** [zjunlp/EasyEdit#375]
Hi, I am trying to perform WISE edits, save the model, and load it subsequently to perform different evaluations. It would be great if you could clarify how to edit the codebase to be able to perform this functionality. Currently it is not clear how to save the configs, main model, adapter etc. in a way that can be quickly loaded again into a WISE class and used for further evaluation.

**Comment by pengzju** [comment]
Thank you for pointing out this issue. Saving the WISE model and reloading it indeed seems necessary. I did not originally support this functionality in the codebase. As you observed, for sequential edits, we perform the evaluation after editing a batch of n entries.

The insight I can provide is that you should save the following components from WISE.py:

- `editing_mean_act` (the minimum **activation** during the training phase),
- `new_weight` (the **side memory** introduced in WISE),
- `original_layer` (the layer where WISE is applied, such as the FFN in Layer 27: **main memory**).

These three components should ensure the WISE model can be reloaded. I hope this approach works for you, though I may not plan to support this functionality directly.

**Comment by shash42** [comment]
Thanks for your response! I hope saving/reloading models is added as a function in future versions of the repository, as it greatly helps the usability of the repository for research, and can be non-trivial with methods like WISE that modify the model logic.

**Comment by xzwyyd** [comment]
Thank you for your suggestion! We have implemented preliminary support for saving and loading the WISE model. You can use this feature by adding the following lines in the configuration file:

```yaml
save_path: "your_path"
load_path: "your_path"
```

For reference, please see this file: [WISE Configuration](https://github.com/zjunlp/EasyEdit/blob/main/hparams/WISE/llama-7b.yaml#L32).

Please ensure that the configuration used for loading is consistent with that used for saving.

We will continue to optimize and maintain this functionality. If you encounter any issues while using it, please feel free to reach out. Additionally, contributions and pull requests are always welcome!
