### ISSUE TITLE
dataset download speed is not stable

### ISSUE THREAD

**Issue by yws-wxs** [zjunlp/EasyEdit#379]
The download speed of MMEDIT is too slow, the network is always unstable, and the download will be disturbed.can you upload the dataset on Baidu Net Disk or others? Thanks

**Comment by tbozhong** [comment]
We have uploaded the images to [BaiduNetDisk](https://pan.baidu.com/s/15WJuPOvxRyF6GDZ-B6_NiA?pwd=wqlg), and you can download them directly.

**Comment by yws-wxs** [comment]
very thanks
