### ISSUE TITLE
Issues while running the repo

### ISSUE THREAD

**Issue by NamburiSrinath** [zjunlp/EasyEdit#38]
Hi folks, 

Thanks for building this amazing repo, it's super concise and easy to setup.

However, when I am running `python edit.py` with `test_MEND_T5()` after installing zsRE and CounterFact datasets and t5-3B model path changed in YAML file, I am getting this error:

`ValueError: You have to specify either decoder_input_ids or decoder_inputs_embeds`

**Comment by pengzju** [comment]
Can you provide complete error information?

**Comment by pengzju** [comment]
- I reproduced your error and now the bug has been fixed.
- However, I notice that you test `MEND` directly. The hypernetwork structure needs to be trained before using MEND, see details here: https://github.com/zjunlp/EasyEdit#trainer

**Comment by NamburiSrinath** [comment]
Awesome, thanks for the info @pengzju. I will give it a try and raise another issue if needed!
