### ISSUE TITLE
is cuda  inevitable?[MacOS]

### ISSUE THREAD

**Issue by York-lap** [zjunlp/EasyEdit#381]

**Comment by littlefive5** [comment]
It's ok if you use cpu to conduct the edit on CPU, but it may take more times.

**Comment by York-lap** [comment]
Thanks for AW 😀, i try to use 'mps' to accelerate. But it always reminds me “Torch not compiled with CUDA enabled”

**Comment by zxlzr** [comment]
hi, we recommend using a GPU, as it may speed up the process. We will also continue to iterate on EasyEdit to support more features.  Do you have any other questions?
