### ISSUE TITLE
Questions about DINM

### ISSUE THREAD

**Issue by Pan-BR** [zjunlp/EasyEdit#385]
Hi, Thanks a lot for your great work! I have two questions about the code for the DINM section.
1. Do you need the data ./data/SafeEdit_train.json to train? After reading the paper and code, my understanding is that there is no need for training, just use test data to test the performance of the model, right?
2. Do you currently provide the corresponding code and data for the "D.1 Generalization Among Different Categories" mentioned in the paper?

**Comment by mengrusun** [comment]
1. Your understanding is absolutely correct, DINM does not require SafeEdit_train.json. DINM just uses one instance to detoxifying. The SafeEdit_train.json and SafeEdit_val.json files are prepared for methods like SFT and DPO. For a comparison of results between SFT, DPO, and DINM, please refer to Table 3.
2. The code for “D.1 Generalization Among Different Categories” has not been open-sourced yet. To make it more convenient for everyone, I will upload the related code within the next two days.

Let me know if you have further questions!

**Comment by Pan-BR** [comment]
Thank you for your detailed answers. I have no further questions.

**Comment by Pan-BR** [comment]
Hello, may I ask when the relevant code can be released?

**Comment by mengrusun** [comment]
The code related to ensemble analysis contains some redundancy. If you need it, you can email me (mengruwg@zju.edu.cn), and I will send it directly to you.
