### ISSUE TITLE
Can the knowledge editing code of sft and dpo be disclosed？

### ISSUE THREAD

**Issue by Mint-hfut** [zjunlp/EasyEdit#386]
Our work will involve the methods of sft and dpo. Can you publish the code of sft and dpo?

**Comment by zxlzr** [comment]
Thank you for your suggestion, we supported lora sft, and will support full sft and dpo soon.

**Comment by HaomingX** [comment]
> Our work will involve the methods of sft and dpo. Can you publish the code of sft and dpo?

Dear Mint-hfut
We already support `DPO`, which accompanies `lora`.  You can check the code [here](easyeditor/models/dpo/dpo_main py) , and adjust it by your need. It can run on an A800-80G, and we will support multi-gpu parallelism soon.
Regards,
EasyEdit Team

**Comment by zxlzr** [comment]
hi, do you have any further questions?
