### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 22.00 MiB (GPU 0; 23.65 GiB total capacity; 22.27 GiB already allocated; 9.69 MiB free; 23.16 GiB reserved in total by PyTorch)

### ISSUE THREAD

**Issue by yzlbig** [zjunlp/EasyEdit#389]
hello, I'm trying to modify some chemistry knowledge（original dataset） on llama-7b (using Rome editing method)

dataset examples are shown below：

    {
        "subject": "'retrosynthesis of COC(=O)c1cccn1CCF'",
        "prompt": "what are the reactants for the retrosynthesis of COC(=O)c1cccn1CCF?",
        "ground_truth": "COC(=O)C1=CC=CN1.FCCI",
        "target_new": "COC(=O)c1ccc[nH]1.FCCI"
    },
    
 error logs are shown below:

 0%|          | 0/100 [00:00<?, ?it/s]2024-10-15 15:37:58,106 - easyeditor.editors.editor - INFO - 0 editing: what are the reactants for the retrosynthesis of COC(=O)c1cccn1CCF? -> COC(=O)c1ccc[nH]1.FCCI  

 {'pre': {'rewrite_acc': [0.5555555555555556], 'portability': {}, 'fluency': {'ngram_entropy': 5.941268505337739}}, 'case_id': 0, 'requested_rewrite': {'prompt': 'what are the reactants for the retrosynthesis of COC(=O)c1cccn1CCF?', 'target_new': 'COC(=O)c1ccc[nH]1.FCCI', 'ground_truth': 'COC(=O)C1=CC=CN1.FCCI', 'portability': {}, 'locality': {}, 'subject': 'retrosynthesis of COC(=O)c1cccn1CCF'}, 'post': {'rewrite_acc': [0.7777777777777778], 'locality': {}, 'portability': {}, 'fluency': {'ngram_entropy': 5.38545249509755}}}
10/15/2024 15:37:58 - INFO - easyeditor.editors.editor -   0 editing: what are the reactants for the retrosynthesis of COC(=O)c1cccn1CCF? -> COC(=O)c1ccc[nH]1.FCCI  

 {'pre': {'rewrite_acc': [0.5555555555555556], 'portability': {}, 'fluency': {'ngram_entropy': 5.941268505337739}}, 'case_id': 0, 'requested_rewrite': {'prompt': 'what are the reactants for the retrosynthesis of COC(=O)c1cccn1CCF?', 'target_new': 'COC(=O)c1ccc[nH]1.FCCI', 'ground_truth': 'COC(=O)C1=CC=CN1.FCCI', 'portability': {}, 'locality': {}, 'subject': 'retrosynthesis of COC(=O)c1cccn1CCF'}, 'post': {'rewrite_acc': [0.7777777777777778], 'locality': {}, 'portability': {}, 'fluency': {'ngram_entropy': 5.38545249509755}}}

  1%|          | 1/100 [00:15<25:29, 15.45s/it]
  1%|          | 1/100 [00:16<27:08, 16.45s/it]
Executing ROME algorithm for the update: [what are the reactants for the retrosynthesis of COC(=O)c1cccn1CCF?] -> [ COC(=O)c1ccc[nH]1.FCCI]
Cached context templates ['{}', 'The following are the. {}', 'The first thing I. {}', 'Therefore, I have. {}', 'Therefore, I have. {}', 'Because of this,. {}', 'Because of its location. {}', "I'd like. {}", 'I’m so. {}', "You're able. {}", 'You may not be. {}', 'The first step to creating a beautiful, functional. {}', 'The first thing I did was take a look. {}', 'Therefore, it is necessary for all of us. {}', 'Therefore, the question is: what is the. {}', 'Because the 1970’s. {}', 'Because of the recent events that have occurred in. {}', 'I was born in London and grew up in. {}', 'I have a 2004 Toy. {}', 'You are here: Home / Archives for S. {}', 'You are here: Home1 / Blog. {}']
Computing left vector (u)...
Selected u projection object retrosynthesis of COC(=O)c1cccn1CCF
Left vector shape: torch.Size([11008])
Computing right vector (v)
Lookup index found: 25 | Sentence: what are the reactants for the retrosynthesis of COC(=O)c1cccn1CCF? COC(=O)c1ccc[nH]1.FCC | Token: F
Rewrite layer is 5
Tying optimization objective to 31
Recording initial value of v*
loss 2.537 = 2.537 + 0.0 + 0.0 avg prob of [ COC(=O)c1ccc[nH]1.FCCI] 0.07934864610433578
loss 2.387 = 2.338 + 0.047 + 0.001 avg prob of [ COC(=O)c1ccc[nH]1.FCCI] 0.0967082530260086
loss 1.96 = 1.892 + 0.067 + 0.001 avg prob of [ COC(=O)c1ccc[nH]1.FCCI] 0.1511920988559723
loss 1.912 = 1.587 + 0.324 + 0.001 avg prob of [ COC(=O)c1ccc[nH]1.FCCI] 0.20478160679340363
loss 1.407 = 1.33 + 0.076 + 0.001 avg prob of [ COC(=O)c1ccc[nH]1.FCCI] 0.26555386185646057
loss 1.074 = 1.054 + 0.019 + 0.001 avg prob of [ COC(=O)c1ccc[nH]1.FCCI] 0.34961894154548645
loss 0.714 = 0.676 + 0.038 + 0.001 avg prob of [ COC(=O)c1ccc[nH]1.FCCI] 0.5103287696838379
loss 1.016 = 0.742 + 0.272 + 0.001 avg prob of [ COC(=O)c1ccc[nH]1.FCCI] 0.47791504859924316
loss 0.593 = 0.531 + 0.062 + 0.001 avg prob of [ COC(=O)c1ccc[nH]1.FCCI] 0.5896281599998474
loss 0.384 = 0.335 + 0.048 + 0.001 avg prob of [ COC(=O)c1ccc[nH]1.FCCI] 0.7161792516708374
loss 0.446 = 0.179 + 0.266 + 0.001 avg prob of [ COC(=O)c1ccc[nH]1.FCCI] 0.8369407057762146
loss 0.282 = 0.257 + 0.025 + 0.001 avg prob of [ COC(=O)c1ccc[nH]1.FCCI] 0.7743651866912842
loss 0.207 = 0.162 + 0.044 + 0.001 avg prob of [ COC(=O)c1ccc[nH]1.FCCI] 0.8510351777076721
loss 0.125 = 0.082 + 0.042 + 0.001 avg prob of [ COC(=O)c1ccc[nH]1.FCCI] 0.9209381341934204
loss 0.074 = 0.046 + 0.027 + 0.001 avg prob of [ COC(=O)c1ccc[nH]1.FCCI] 0.9549732208251953
loss 0.046 = 0.026 + 0.02 + 0.001 avg prob of [ COC(=O)c1ccc[nH]1.FCCI] 0.974860429763794
Delta norm: 17.296875
Change in target norm: 4.32421875 to 17.75 => 13.421875
Division Factor: 3.689453125
Right vector norm: 4.6875
Right vector shape: torch.Size([4096])
Deltas successfully computed for ['model.layers.5.mlp.down_proj.weight']
New weights successfully inserted into ['model.layers.5.mlp.down_proj.weight']
Executing ROME algorithm for the update: [what are the reactants for the retrosynthesis of CC(C)(C)OC(=O)N1CCC(C(c2cc(F)ccc2F)S(=O)(=O)c2ccc(Cl)cc2)CC1?] -> [ CC(C)(C)OC(=O)N1CCC(O)CC1.O=S(=O)(Cc1cc(F)ccc1F)c1ccc(Cl)cc1]
Computing left vector (u)...
Selected u projection object retrosynthesis of CC(C)(C)OC(=O)N1CCC(C(c2cc(F)ccc2F)S(=O)(=O)c2ccc(Cl)cc2)CC1
Left vector shape: torch.Size([11008])
Computing right vector (v)
Lookup index found: 59 | Sentence: what are the reactants for the retrosynthesis of CC(C)(C)OC(=O)N1CCC(C(c2cc(F)ccc2F)S(=O)(=O)c2ccc(Cl)cc2)CC1? CC(C)(C)OC(=O)N1CCC(O)CC1.O=S(=O)(Cc1cc(F)ccc1F)c1ccc(Cl)cc | Token: 1
Rewrite layer is 5
Tying optimization objective to 31
Recording initial value of v*
Traceback (most recent call last):
  File "/root/EasyEdit/run_chemistry_llama2.py", line 80, in <module>
    metrics, edited_model, _ = editor.edit(
  File "/root/EasyEdit/easyeditor/editors/editor.py", line 184, in edit
    return self.edit_requests(requests, sequential_edit, verbose, test_generation=test_generation, **kwargs)
  File "/root/EasyEdit/easyeditor/editors/editor.py", line 362, in edit_requests
    edited_model, weights_copy, icl_examples = edit_func(request)
  File "/root/EasyEdit/easyeditor/editors/editor.py", line 312, in edit_func
    edited_model, weights_copy = self.apply_algo(
  File "/root/EasyEdit/easyeditor/models/rome/rome_main.py", line 41, in apply_rome_to_model
    deltas = execute_rome(model, tok, request, hparams)
  File "/root/EasyEdit/easyeditor/models/rome/rome_main.py", line 112, in execute_rome
    right_vector: torch.Tensor = compute_v(
  File "/root/EasyEdit/easyeditor/models/rome/compute_v.py", line 124, in compute_v
    logits = model(**input_tok).logits
  File "/root/miniconda3/envs/EasyEdit/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/EasyEdit/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 1208, in forward
    outputs = self.model(
  File "/root/miniconda3/envs/EasyEdit/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/EasyEdit/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 1018, in forward
    layer_outputs = decoder_layer(
  File "/root/miniconda3/envs/EasyEdit/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/EasyEdit/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 741, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/root/miniconda3/envs/EasyEdit/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/EasyEdit/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 388, in forward
    attn_output = attn_output.transpose(1, 2).contiguous()
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 22.00 MiB (GPU 0; 23.65 GiB total capacity; 22.27 GiB already allocated; 9.69 MiB free; 23.16 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

I will appreciate it if you could show me the method to dealing with this kind of errors.

**Comment by XeeKee** [comment]
It seems that the error is due to insufficient GPU memory. You can try using a model with fewer parameters, or you can try adding quantization code at https://github.com/zjunlp/EasyEdit/blob/b6462bea7c1131591935ebe060fff5a2dd2683e5/easyeditor/editors/editor.py#L96.

**Comment by zxlzr** [comment]
We have provided GPU consumption information at https://github.com/zjunlp/EasyEdit?tab=readme-ov-file#editing-gpu-memory-usage. Do you have any other questions?
