### ISSUE TITLE
Use two GPU

### ISSUE THREAD

**Issue by bibidentuhanoi** [zjunlp/EasyEdit#39]
So hi, i'm trying to run this with 2xt4 gpu on kaggle but then came a crosss this error : `RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!`. I change the `self.model = LlamaForCausalLM.from_pretrained(self.model_name)`  by adding `device_map="auto"`

what should i do ?

**Comment by pengzju** [comment]
It is the holiday now,, and I will address the issues and get back to you after the holiday. I apologize for any inconvenience this may have caused.

**Comment by pengzju** [comment]
Thank you for your attention. The `accelerator` module is currently under active development

**Comment by zxlzr** [comment]
The `accelerator` module has been added in EasyEdit, so you can use two GPUs. If you have any questions, feel free to contact us.

**Comment by peixin-lin** [comment]
> The `accelerator` module has been added in EasyEdit, so you can use two GPUs. If you have any questions, feel free to contact us.

What codes or configs should be added to make it work? Is there a demo for training with multiple GPUs using EasyEdit?

**Comment by bibidentuhanoi** [comment]
I have tried, and it loaded the model on two GPUs. But I came across another problem: the model is too big for the GPUs.
`OutOfMemoryError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 1; 14.76 GiB total capacity; 13.95 GiB already allocated; 61.75 MiB free; 13.95 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`. So i tried to offload everything to a folder while using two GPUs.  I got this error again: `runtimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!`

**Comment by pengzju** [comment]
Which model you are editing? llama-7b or gptj-6b?
How much VRAM is available on your GPU? (It seems that 2*14=28G cannot load a model with a large number of parameters)

**Comment by bibidentuhanoi** [comment]
I'm trying to work around with llama-7b. I used two t4 GPUs on the Kaggle notebook.  
![image](https://github.com/zjunlp/EasyEdit/assets/95683666/c9b087f0-73be-4cf0-9297-7caef7213e91)

**Comment by lukaswangbk** [comment]
still got the error saying that expected all tensors to be on the same device

**Comment by pengzju** [comment]
- Editing llama-7b requires about 45GB of VRAM. (It seems that two t4 GPUs are not enough)
- I hope you can provide specific screenshots or error information (about device inconsistency).

**Comment by zxlzr** [comment]
Have you solved your issue?
