### ISSUE TITLE
Upgrade requirements.txt

### ISSUE THREAD

**Issue by Syon-Li** [zjunlp/EasyEdit#392]
Dear EasyEdit Team,

Thank you very much for this nice repo.

Since you have integrated llama-3.2 into your repo, you also have to update the dependencies of your repo. The current transformer version may have the problem of loading llama-3.2 (see this [issue](https://github.com/ollama/ollama/issues/7020)).

Regards,
Syon

**Comment by XeeKee** [comment]
Thank you very much for your attention to EasyEdit. We will update the requirements in the near future and test whether there is any impact on other methods.

**Comment by XeeKee** [comment]
Thank you very much for your interest in EasyEdit. We have updated the Transformers library.
