### ISSUE TITLE
两个GPU训练出现卡死的情况

### ISSUE THREAD

**Issue by yzlbig** [zjunlp/EasyEdit#394]
![1](https://github.com/user-attachments/assets/869b7b3d-6b7f-42ec-8ee7-95ea35d8fdd8)

请问在使用两个GPU时，一个GPU-util到了100%，随后出现了卡死的情况，这该怎么解决呢？

**Comment by XeeKee** [comment]
我们没遇到这种情况，如果您提供更多的信息例如使用的什么方法或者卡在哪一行代码，也许我们能帮助到您

**Comment by yzlbig** [comment]
你好，我从dataparallel换成了distributeddataparallel之后，又开始报torch.cuda.OutOfMemoryError: CUDA out of memory.的错误，报错如下，请您过目。另外，我看了咱用rome编辑llama2-7b，需要31GB的显存，我两块GPU4090，每一块24GB，应该是够用的呀，请您帮助一下我

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]
Loading checkpoint shards:  50%|█████     | 1/2 [00:05<00:05,  5.55s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:06<00:00,  3.00s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:06<00:00,  3.38s/it]
10/20/2024 14:15:51 - WARNING - accelerate.big_modeling -   We've detected an older driver with an RTX 4000 series GPU. These drivers have issues with P2P. This can affect the multi-gpu inference when using accelerate device_map.Please make sure to update your driver to the latest version which resolves this.
/root/miniconda3/envs/EasyEdit/lib/python3.9/site-packages/huggingface_hub/file_download.py:1142: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
2024-10-20 14:15:51,577 - easyeditor.editors.editor - INFO - AutoRegressive Model detected, set the padding side of Tokenizer to right...
10/20/2024 14:15:51 - INFO - easyeditor.editors.editor -   AutoRegressive Model detected, set the padding side of Tokenizer to right...

  0%|          | 0/100 [00:00<?, ?it/s]10/20/2024 14:15:53 - INFO - torch.distributed.distributed_c10d -   Added key: store_based_barrier_key:1 to store for rank: 0
10/20/2024 14:15:53 - INFO - torch.distributed.distributed_c10d -   Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
10/20/2024 14:15:53 - WARNING - accelerate.big_modeling -   You shouldn't move a model that is dispatched using accelerate hooks.

  0%|          | 0/100 [00:02<?, ?it/s]
Executing ROME algorithm for the update: [retrosynthesis of COC(=O)c1cccn1CCF?] -> [ COC(=O)c1ccc[nH]1.FCCI]
Cached context templates ['{}', 'The 20. {}', 'The 15. {}', 'Therefore the following information. {}', 'Therefore, we must. {}', 'Because I have been. {}', 'Because we are committed. {}', 'I have a conf. {}', "I've had. {}", "You've been. {}", 'You are here:. {}', 'The 1980s were a. {}', 'The 15th of August was celebrated. {}', 'Therefore, I am writing this letter to you. {}', 'Therefore, if you are planning to buy a. {}', 'Because of their small size, it can be. {}', 'Because of the high level of interest in our. {}', 'I was searching for a Property and found this. {}', 'I’ve been thinking a lot lately. {}', 'You are here: Home / Featured. {}', 'You are here: Home / News / . {}']
Computing left vector (u)...
Selected u projection object retrosynthesis
Left vector shape: torch.Size([11008])
Traceback (most recent call last):
  File "/root/EasyEdit/run_chemistry_llama2.py", line 80, in <module>
    metrics, edited_model, _ = editor.edit(
  File "/root/EasyEdit/easyeditor/editors/editor.py", line 190, in edit
    return self.edit_requests(requests, sequential_edit, verbose, test_generation=test_generation, **kwargs)
  File "/root/EasyEdit/easyeditor/editors/editor.py", line 368, in edit_requests
    edited_model, weights_copy, icl_examples = edit_func(request)
  File "/root/EasyEdit/easyeditor/editors/editor.py", line 318, in edit_func
    edited_model, weights_copy = self.apply_algo(
  File "/root/EasyEdit/easyeditor/models/rome/rome_main.py", line 41, in apply_rome_to_model
    deltas = execute_rome(model, tok, request, hparams)
  File "/root/EasyEdit/easyeditor/models/rome/rome_main.py", line 112, in execute_rome
    right_vector: torch.Tensor = compute_v(
  File "/root/EasyEdit/easyeditor/models/rome/compute_v.py", line 141, in compute_v
    model = torch.nn.parallel.DistributedDataParallel(model)
  File "/root/miniconda3/envs/EasyEdit/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 688, in __init__
    self._ddp_init_helper(
  File "/root/miniconda3/envs/EasyEdit/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 825, in _ddp_init_helper
    self.reducer = dist.Reducer(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 12.55 GiB (GPU 0; 23.65 GiB total capacity; 12.71 GiB already allocated; 10.34 GiB free; 12.72 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by XeeKee** [comment]
你好，双卡的时候显存开销会很大并且卡0会占用超过24g，实测4张3090很难编辑7b的模型，我建议您更换模型或者机器，我怀疑您卡很久是因为没有下载本地的Wikipedia，您可以把超参数中的mom2_adjustment设置为false

**Comment by yzlbig** [comment]
您好，我用的数据集是化学数据集

**Comment by yzlbig** [comment]
您好，我用的数据集是化学数据集，形式如下，我还需要用到Wikipedia吗，或者说我使用自创数据集时需要注意什么吗？
{
        "subject": "retrosynthesis",
        "prompt": "retrosynthesis of COC(=O)c1cccn1CCF?",
        "ground_truth": "COC(=O)C1=CC=CN1.FCCI",
        "target_new": "COC(=O)c1ccc[nH]1.FCCI"
    },

**Comment by XeeKee** [comment]
mom2_adjustment设置为false就不需要，使用Wikipedia进行约束可以得到更好的locality性能

**Comment by yzlbig** [comment]
mom2_adjustment我是设置为false的

您好，另外又出现了如下的报错
  File "/root/EasyEdit/easyeditor/models/rome/repr_tools.py", line 31, in get_reprs_at_word_tokens
    return get_reprs_at_idxs(
  File "/root/EasyEdit/easyeditor/models/rome/repr_tools.py", line 156, in get_reprs_at_idxs
    with nethook.Trace(
  File "/root/EasyEdit/easyeditor/util/nethook.py", line 69, in __init__
    module = get_module(module, layer)
  File "/root/EasyEdit/easyeditor/util/nethook.py", line 362, in get_module
    raise LookupError(name)
LookupError: model.layers.5.mlp.down_proj


我查看了我的模型结构
DistributedDataParallel(
  (module): LlamaForCausalLM(
    (model): LlamaModel(
      (embed_tokens): Embedding(32000, 4096)
      (layers): ModuleList(
        (0-31): 32 x LlamaDecoderLayer(
          (self_attn): LlamaAttention(
            (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
            (k_proj): Linear(in_features=4096, out_features=4096, bias=False)
            (v_proj): Linear(in_features=4096, out_features=4096, bias=False)
            (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
            (rotary_emb): LlamaRotaryEmbedding()
          )
          (mlp): LlamaMLP(
            (gate_proj): Linear(in_features=4096, out_features=11008, bias=False)
            (up_proj): Linear(in_features=4096, out_features=11008, bias=False)
            (down_proj): Linear(in_features=11008, out_features=4096, bias=False)
            (act_fn): SiLU()
          )
          (input_layernorm): LlamaRMSNorm()
          (post_attention_layernorm): LlamaRMSNorm()
        )
      )
      (norm): LlamaRMSNorm()
    )
    (lm_head): Linear(in_features=4096, out_features=32000, bias=False)
  )
)

是存在的呀，请问是哪里出现问题，以至于找不到这个layer呢？

**Comment by yzlbig** [comment]
感谢您的帮助，已成功跑通。最后我想请问，按照我的理解，ROME 方法是通过计算模型中的一些向量更新，来调整模型的输出以实现特定的文本重写或编辑，是一种特殊的模型编辑机制。所以，是不是只用了一个数据集（不用区分train，val或者是test）就可得到效果？

**Comment by XeeKee** [comment]
是的

**Comment by yzlbig** [comment]
那每次跑一个数据，都要优化delta（计算loss），更新向量。我想问问，有没有办法像传统深度学习模型那样来学习呢（区分train，val和test）

**Comment by XeeKee** [comment]
您加我一个微信吧这样沟通方便一些
xi1786594371

**Comment by yzlbig** [comment]
好的好的
