### ISSUE TITLE
Questions About WISE

### ISSUE THREAD

**Issue by zhengguanyu** [zjunlp/EasyEdit#399]
非常感谢您的工作，对我很有启发，有两个问题想请教！

# 问题1
使用WISE复现结果（`T=600 or 1000`），编辑速度很慢，请问有什么方法可以加快编辑速度？
数据集ZsRE，编辑模型Llama2-7b-hf
### T=600
` 8%|███████████████▌                                                                                                                                                                       | 51/600 [7:11:03<56:50:11, 372.70s/it]Executing WISE algorithm for the update:
`
### T=1000
`1%|█▊                                                                                                                                                                                   | 10/1000 [2:08:45<156:35:06, 569.40s/it]Executing WISE algorithm for the update:
`

我观察到有`editor.py`中有`batch_edit()`，在`run_wise_editing.py`替换后（`llama-7b.yaml`加入`batch_size`参数）引出断言报错，是否因为引入batch_size会违背原文中lifelong editing的问题定义？

> AssertionError: The Method WISE can not batch edit examples.

### run_wise_editing.py

>     editor = BaseEditor.from_hparams(hparams)
>     metrics, edited_model, _ = editor.batch_edit(
>         prompts=prompts,
>         rephrase_prompts=rephrase_prompts,
>         target_new=target_new,
>         loc_prompts=loc_prompts,
>         subject=subject,
>         locality_inputs=locality_inputs,
>         sequential_edit=args.sequential_edit,
>         eval_metric='ppl' if args.data_type == 'hallucination' else 'token em'
>     )

### llama-7b.yaml

> alg_name: "WISE"
> 
> model_name: "XXX/Llama-2-7b-hf/"
> device: 0
> 
> mask_ratio: 0.2
> edit_lr: 1.0
> n_iter: 70
> norm_constraint: 1.0
> act_margin: [5.0, 20.0, 10.0] # alpha, beta, gamma
> act_ratio: 0.88
> save_freq: 500
> merge_freq: 1000
> merge_alg: 'ties'
> objective_optimization: 'only_label'
> batch_size: 4
> inner_params:
> - model.layers[27].mlp.down_proj.weight
> 
> 
> /## alternative: WISE-Merge, WISE-Retrieve
> 
> /# for merge (if merge)
> densities: 0.53
> weights: 1.0
> 
> /# for retrieve (if retrieve, pls set to True)
> retrieve: True
> replay: False # True --> will replay the past editing instances: see https://arxiv.org/abs/2405.14768 Appendix B.3
> 
> model_parallel: False
> 
> /# for save and load
> /# save_path: "./wise_checkpoint/wise.pt"
> /# load_path: "./wise_checkpoint/wise.pt"

# 问题2
我观察到原文中表6尝试了T=2000，`zsre_mend_edit`中有1037条数据，请问关于ZsRE的实验如何采样？

**Comment by zxlzr** [comment]
hi, do you have any further issues?

**Comment by zhengguanyu** [comment]
非常感谢您的解答！！
