### ISSUE TITLE
Does this framework support the ChatGLM series models?

### ISSUE THREAD

**Issue by gaozhengjie** [zjunlp/EasyEdit#4]
Hi.

Does this framework support the ChatGLM series models? Or is there any plan to support them in the future? Thank you.

**Comment by zxlzr** [comment]
Thank you for your attention, EasyEdit recently do not support ChatGLM, and we plan to support ChatGLM in the next  version.

**Comment by gaozhengjie** [comment]
Thank you very much for your reply.  Could you please disclose when is the next version approximately going to be released? And do you know of any frameworks or methods that can be used to edit the knowledge of ChatGLM?

**Comment by zxlzr** [comment]
The timeline is contingent upon our human resources, and we can't commit to a definitive date at this time. There's potential that MEND (though I'm uncertain of the exact terminology) could be integrated with ChatGLM.

**Comment by zxlzr** [comment]
EasyEdit has partially supported ChatGLM2 (still optimizing the performance, previous baselines do not perform well). EasyEdit has also supported fine-tuning ChatGPT now.
