### ISSUE TITLE
alphaedit

### ISSUE THREAD

**Issue by SXxinxiaosong** [zjunlp/EasyEdit#401]
# Make sure that the projection matrix P has been downloaded from the google drive beforehand to avoid double computation.
# But if the projection matrix P which we provided is not needed, then nothing needs to be done to the P_loc field; 
# just run the program, and the program will compute P and save it locally automatically.
P_loc: "./null_space_project.pt"

请问从哪个链接下载呢

**Comment by JizhanFang** [comment]
Thank you for your question. You can find the specific download link for the projection matrix P in the README of AlphaEdit ( https://github.com/zjunlp/EasyEdit/blob/main/easyeditor/models/alphaedit/README.md ). However, please note: if you are using a base model other than llama3-8b, or if you have selected layers other than the default configuration in the hyperparameter file (layers: [4, 5, 6, 7, 8]), then you will need to recalculate P accordingly.

**Comment by zxlzr** [comment]
hi, do you have any further issues?

**Comment by Lucyferko** [comment]
Hello, there is no such readme (anymore). Please advise
