### ISSUE TITLE
alphaedit stats

### ISSUE THREAD

**Issue by SXxinxiaosong** [zjunlp/EasyEdit#403]
请问alphaedit 的 stats 可以直接用llama2的嘛？
如果不可以，请问哪里可以下载llama3的呢？
谢谢~

**Comment by JizhanFang** [comment]
你好，如果你想编辑llama3-8B模型，那么stats是不可以直接用llama2的。我们在alphaedit的readme中提供了llama3-8B的投影矩阵P（P就是由layer_states计算得来）的百度网盘的链接。
alphaedit的readme的地址：https://github.com/zjunlp/EasyEdit/blob/main/easyeditor/models/alphaedit/README.md
llama3-8B的投影矩阵的百度网盘链接：https://pan.baidu.com/s/1Unk3X6jl3LZw_OF5eLoEeA?pwd=mcaf

**Comment by SXxinxiaosong** [comment]
那我知道啦，谢谢！
