### ISSUE TITLE
Questions about reproducing the WISE model on the ZsRE dataset

### ISSUE THREAD

**Issue by Eliaukyh** [zjunlp/EasyEdit#407]
When editing the ZsRE dataset, if I set the ds_size to 2000 (which is greater than 1037), it throws an error.

![GS{()KHSQZHXM 66S5)0UXA](https://github.com/user-attachments/assets/858bd12c-2768-4c02-958c-d8ebf838714f)
![63Y58W12A6%S1T32KQR%YG4](https://github.com/user-attachments/assets/4be025d0-102d-4d91-87a4-1a5d9cd6464f)

How should I resolve this issue? I look forward to your response.

**Comment by pengzju** [comment]
You can download the dataset again. https://drive.google.com/file/d/1YtQvv4WvTa4rJyDYQR2J-uK8rnrt0kTA/view (#399)

To edit 2,000 samples, please use `zsre_mend_edit.json`. The number of loc_prompt and edit_prompt should be the same.

**Comment by Eliaukyh** [comment]
It has been resolved, thank you very much for your answer.

**Comment by Mint-hfut** [comment]
为什么https://drive.google.com/file/d/1YtQvv4WvTa4rJyDYQR2J-uK8rnrt0kTA/view (https://github.com/zjunlp/EasyEdit/issues/399)中的zsre_mend_edit.json还是只有1037条数据啊？

**Comment by pengzju** [comment]
sry, 请使用`zsre_mend_train.json`

<img width="666" alt="image" src="https://github.com/user-attachments/assets/b54752c9-df79-4af6-b0bb-0e6c44381959">
