### ISSUE TITLE
Deos MEMIT support fp16？

### ISSUE THREAD

**Issue by asdfo123** [zjunlp/EasyEdit#409]
Hi! 
I'm currently reproducing experiments using EasyEdit and noticed that ROME supports `fp16` in its configuration, but MEMIT lacks an `fp16` option in the hparams YAML file. 

Could you clarify if MEMIT supports `fp16`? 

Also, based on your experience, does using `fp16` affect the results? And if so, to what extent?

**Comment by XeeKee** [comment]
Not supported; using fp16 will reduce the effectiveness.

**Comment by asdfo123** [comment]
> Not supported; using fp16 will reduce the effectiveness.

Thanks a lot for your reply.
