### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by shariqahn** [zjunlp/EasyEdit#414]
Is there a way to use this framework with a custom dataset? How would I go about doing that?

**Comment by shariqahn** [comment]
That's great news! Thank you.

**Comment by shariqahn** [comment]
I understand that ROME requires a 'subject.' I have a dataset of prompts and answers. Do you have suggestions for the best way to determine the subject? I saw a suggestion for using the last token as the subject, but that doesn't seem very accurate.

**Comment by JizhanFang** [comment]
The best approach is to use a tool to extract the subject from the prompt. If this is not done, apart from taking the last token as the subject as you mentioned, we sometimes use the entire prompt as the subject. You can also try this and see how it works. In addition, if you are selecting some methods as baselines, consider using the WISE method. The link to the method is as follows:
https://github.com/zjunlp/EasyEdit/blob/main/examples/WISE.md
This method does not require specifying the subject, making it well-suited for your data.

**Comment by zxlzr** [comment]
hi, do you have any further questions?

**Comment by shariqahn** [comment]
All good! Thank you
