### ISSUE TITLE
Quick fix to make runnning example easier

### ISSUE THREAD

**Issue by lauraaisling** [zjunlp/EasyEdit#415]
Hey, this repo is amazing, and documented so well, thank you so much! 
I figured a quick fix to make running examples easier, you say in https://github.com/zjunlp/EasyEdit/blob/main/examples/SafeEdit.md:
"Also, move the file run_safety_editing.py to ./ (We will later modify the code to adapt to running in the current directory)."

My suggestion is simply to add the following to examples/run_safety_editing.py: 

"from pathlib import Path
path_root = Path(\_\_file\_\_).parents[1]
sys.path.append(str(path_root))"

Add or ignore as you wish :) but I can also insert this suggestion as a PR if you prefer that?

**Comment by mengrusun** [comment]
Thank you for your suggestion. We have modified the code to make it more convenient for users. 

If you have any further comments or questions, please feel free to contact us.
