### ISSUE TITLE
Tutorial on injecting or adding new knowledge 

### ISSUE THREAD

**Issue by bibidentuhanoi** [zjunlp/EasyEdit#42]
I read your Readme. md and there is no section about injecting knowledge except this line `2023-9-21 The EasyEdit have supported Parameter-Efficient Fine-Tuning through AdaLoRA to inject knowledge into the LLM.` and this part [LoRA](https://github.com/zjunlp/EasyEdit/tree/main/examples#lora) in the example folder. Can you provide more details on this? 

Thank you

**Comment by pengzju** [comment]
Loading LoRAHyperParams uses AdaLoRA for editing by default, You can refer to here: https://github.com/zjunlp/EasyEdit/blob/main/easyeditor/models/lora/lora_main.py#L64

**Comment by zxlzr** [comment]
hi, have you solved your issue?

**Comment by bibidentuhanoi** [comment]
> Loading LoRAHyperParams uses AdaLoRA for editing by default, You can refer to here: https://github.com/zjunlp/EasyEdit/blob/main/easyeditor/models/lora/lora_main.py#L64

Hello, and I apologize for the delayed response. Thank you for responding, however, I believe I still need more examples on this. Could you possibly give me with some sample code so that I know where to begin? Thank you very much.

**Comment by pengzju** [comment]
Specifically, you can use the code as below

```python
from easyeditor import LoRAHyperParams
from easyeditor import BaseEditor

hparams = LoRAHyperParams.from_hparams('./hparams/LoRA/llama-7b.yaml')
editor = BaseEditor.from_hparams(hparams)
metrics, edited_model, _ = editor.edit(
    prompts=YOUR_INPUTS,
    target_new=YOUR_OUTPUTS,
    keep_original_weight=True
)
```

**Comment by pengzju** [comment]
As for the format of `input`, you can refer to the **Step3** here(https://github.com/zjunlp/EasyEdit#baseeditor)

**Comment by pengzju** [comment]
If your problem has been resolved, please help close this issue.
