### ISSUE TITLE
How to evaluate commonsense locality? 

### ISSUE THREAD

**Issue by lliutianc** [zjunlp/EasyEdit#424]
Hi, 

Thanks for maintaining the repo!

After reading through the codes and your paper: Editing Large Language Models: Problems, Methods, and Opportunities, I am not sure how to evaluate the locality results shown in Table 4 in the paper. The dataset looks like "locality" but I didn't find an example of using it properly. Can you share a  minimal example? 

<img width="866" alt="image" src="https://github.com/user-attachments/assets/30c6e6f2-2d67-4825-8541-eb8a53f19449">

**Comment by littlefive5** [comment]
Hi there, you can find it in appendix B.3.3. For the computation, we combine the question and choice as the input, we compute the loss between different choice and select the one with the minimum loss as the answer.

**Comment by zxlzr** [comment]
Hi buddy, do you have any further questions?

**Comment by lliutianc** [comment]
Thanks for your answer. By loss do you mean using PPL? BTW, were `distracting neighbor` and `other attribution` computed in the same logic?

**Comment by littlefive5** [comment]
Yes, PPL.
But, `distracting neighbor` and `other attribution` are computed by the token-level exact metric, this can be calculated by our evaluation code. 
This means you can directly use our code to get results of `distracting neighbor` and `other attribution` but you need to evaluate the reasoning task by your own.
