### ISSUE TITLE
GRACE使用llama2-7b出现了不正确的结果

### ISSUE THREAD

**Issue by Mint-hfut** [zjunlp/EasyEdit#428]
我拉取了最新版的代码，使用的hparams/GRACE/llama-7B.yaml参数如下：
alg_name: "GRACE"
model_name: "/root/work/filestorage/Llama-2-7b-hf"
device: 0

inner_params:
- model.layers[27].mlp.down_proj.weight

edit_lr: 1.0
n_iter: 50
eps: 1.0
dist_fn: euc # euc, mmd, cos
val_init: cold # cold, warm
val_train: sgd # sgd, pert
val_reg: None # early
reg: early_stop # early_stop
replacement: replace_last # replace_last, replace_all, replace_prompt
eps_expand: coverage # , moving_avg, decay
num_pert: 8 # only matters when using perturbation training
dropout: 0.0

examples/run_wise_editing.py
    parser = argparse.ArgumentParser()
    parser.add_argument('--editing_method', default="GRACE", type=str)
    parser.add_argument('--hparams_dir', default="./hparams/GRACE/llama-7B.yaml", type=str)
    parser.add_argument('--data_dir', default="/root/work/GC/EasyEdit/data/wise", type=str)
    parser.add_argument('--data_type', default="ZsRE", type=str,
                        choices=['ZsRE', 'temporal', 'hallucination'])
    parser.add_argument('--output_dir', default='./outputs', type=str)
    parser.add_argument('--ds_size', default=1, type=int)
    parser.add_argument('--sequential_edit', default=True, action="store_true")

得出的结果是：
Metrics Summary:  {'pre': {'rewrite_acc': 0.0, 'rephrase_acc': 0.0}, 'post': {'rewrite_acc': 0.2, 'rephrase_acc': 0.0, 'locality': {'neighborhood_acc': 1.0}}}

rewrite_acc明显不符合情况，请问这是为什么？

**Comment by zxlzr** [comment]
hi, we will run the code and help you asap.

**Comment by JizhanFang** [comment]
你好，我拉取了最新版的代码，并且超参数的配置和你一样也维持了默认配置，也是用了run_wise_editing.py，然后只跑一条sample的情况下，我的结果是：
Metrics Summary: {'pre': {'rewrite_acc': 0.0, 'rephrase_acc': 0.0}, 'post': {'rewrite_acc': 0.6666666666666666, 'rephrase_acc': 0.0, 'locality': {'neighborhood_acc': 1.0}}}
考虑到样本数太少，我又跑了10条sample，结果如下：
Metrics Summary: {'pre': {'rewrite_acc': 0.0, 'rephrase_acc': 0.0}, 'post': {'rewrite_acc': 0.9666666666666666, 'rephrase_acc': 0.016666666666666666, 'locality': {'neighborhood_acc': 1.0}}}
明显可以看出这个结果相较于你跑的结果更为正常，如果你需要进一步的帮助的话，你可以提供更多的信息。

**Comment by zxlzr** [comment]
请问您的问题解决了吗？

**Comment by Mint-hfut** [comment]
问题解决了，我重新查看了我的环境，发现最新版代码需要sentence-transformers==3.2.1和transformers==4.44.2，而我之前安装的环境是sentence-transformers==2.2.2，transformers==4.40.0。通过升级sentence-transformers==3.2.1解决了，10条数据的结果是Metrics Summary:  {'pre': {'rewrite_acc': 0.0, 'rephrase_acc': 0.0}, 'post': {'rewrite_acc': 1.0, 'rephrase_acc': 0.0, 'locality': {'neighborhood_acc': 1.0}}}
