### ISSUE TITLE
Edits do not work

### ISSUE THREAD

**Issue by AmjadAlwadi** [zjunlp/EasyEdit#429]
I tried every model editing method available on this framework on multiple models like gpt2-xl and gpt-neo and llama2-7b but the edits were not successful and I wanna know the reason.
I just ran the jupyter-notebook examples and the edits didn't work.

**Comment by zxlzr** [comment]
could you please tell me which file do you use?

**Comment by AmjadAlwadi** [comment]
for example the tutorial-notebooks/EasyEdit_Example_ROME.ipynb
and as you can see in EasyEdit_Example_ROME.ipynb the pre and post edit responses are the same and nothing has changed also the weights didn't change even if I set keep_original_weights to false which does nothing anyways because in the source code it's set to false anyways and was not even used in the rome_main.py file but the copy parameter is kind of interesting and I want to know what that affects exactly because changing it in the source code actually affected the result of the edits which is bizarre to me

**Comment by zxlzr** [comment]
It's midnight now—I'll run the code tomorrow morning and reply you.

**Comment by AmjadAlwadi** [comment]
thank you

**Comment by littlefive5** [comment]
Hi, there, set `sequential_edit` as `true` and try again.
The `keep_original_weights ` has been removed from our current version, we're going to update the demo code.

**Comment by AmjadAlwadi** [comment]
After changing copy to true it worked but also after setting sequential_edit to true it worked as well even though I don't know exactly why but thank you

**Comment by littlefive5** [comment]
Well, setting `copy` as true would require more memory and we highly recommend `sequential_edit`. This originated from the pointer in python and they share the same object in the memory when we transfer it from the function call.
