### ISSUE TITLE
Llama2 ROME index out of bound

### ISSUE THREAD

**Issue by ZihaoLin0123** [zjunlp/EasyEdit#43]
Hi,

Thanks for your excellent work! I am trying to run ROME on LLaMA2-7b. My checkpoint is requested from META form and is converted to hf format using [this code](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/convert_llama_weights_to_hf.py). (I also tried to download the checkpoint from huggingface directly, but the same error occurs.) I followed your instruction to copy the zsre_mend_eval_portability_gpt4.json to the right path. When I run the code, I met the issue:

Traceback (most recent call last):
  File "/home/linzihao/memory-editing/EasyEdit/scripts/../examples/run_zsre_llama2.py", line 78, in <module>
    metrics, edited_model, _ = editor.edit(
  File "/home/linzihao/memory-editing/EasyEdit/scripts/../easyeditor/editors/editor.py", line 199, in edit
    "pre": compute_edit_quality(self.model, self.model_name, self.hparams, self.tok, request,
  File "/home/linzihao/memory-editing/EasyEdit/scripts/../easyeditor/evaluate/evaluate.py", line 70, in compute_edit_quality
    compute_portability_quality(model, model_name, hparams, tok, portability_key,
  File "/home/linzihao/memory-editing/EasyEdit/scripts/../easyeditor/evaluate/portability_evaluate.py", line 24, in compute_portability_quality
    portability_correct = test_prediction_acc(model, tok, hparams, prompt, ground_truth, device)
  File "/home/linzihao/memory-editing/EasyEdit/scripts/../easyeditor/evaluate/evaluate_utils.py", line 109, in test_prediction_acc
    if isinstance(answers[0], list):
IndexError: list index out of range

It happens when evaluate the 17th request. The exact item in zsre_mend_eval_portability_gpt4.json is 
{
        "subject": "USS Leedstown (APA-56)",
        "src": "Which corporation created USS Leedstown (APA-56)?",
        "pred": "Lockheed Shipbuilding and Construction Company",
        "rephrase": "Which company was produced by USS Leedstown (APA-56)?",
        "alt": "Arleigh Burke-class aircraft carrier",
        "answers": [
            "Bethlehem Steel"
        ],
        "loc": "nq question: i was a great islamic scholar and mathematician who died in 1131 ce",
        "loc_ans": "Omar Khayyam",
        "cond": "Lockheed Shipbuilding and Construction Company >> Arleigh Burke-class aircraft carrier || Which corporation created USS Leedstown (APA-56)?",
        "portability": {
            "Recalled Relation": "(Arleigh Burke-class, primary user, United States Navy)",
            "New Question": "Which organization is the primary user of the class that USS Leedstown (APA-56) belongs to?",
            "New Answer": "United States Navy"
        }
    },

The exact reason is that the prompt_len is 30 while the generated output from LLaMA2 is also 30. After the line 105 in file easyeditor/evaluate/evaluate_utils.py, the answers become "[]" which causes the indexerror when call "answers[0]". I add "try ... except ..." module and I found there are more than ten data items meet this problem.

I wonder do you face the same problem? How do you fix it? Thanks!

**Comment by NamburiSrinath** [comment]
Hi @ZihaoLin0123,

I was facing the same issue (https://github.com/zjunlp/EasyEdit/issues/44), but have no luck so far!

Are you able to find something?

Thanks
Srinath

**Comment by pengzju** [comment]
Thank you for your attention. This error occurs because `max_length` is too small and truncation truncates the label part. You can try increasing `max_length`.
- I hope you can solve the problem and let me know

**Comment by zxlzr** [comment]
Hi, have you solved your issue?

**Comment by NamburiSrinath** [comment]
Refer #44, thanks for the support.
