### ISSUE TITLE
Question of KnowEdit

### ISSUE THREAD

**Issue by gkruddl** [zjunlp/EasyEdit#433]
Hi, 
I notice in [KnowEdit.md] there are examples of how to implement

ROME, MEMIT, FT,MEND, **_KN, IKE, LoRA_**

However, this does not match with the KnowEdit table which has results of
ROME, MEMIT, FT-L,FT-M, MEND, **_SERAC, ICE, AdaLoRA_**.

Am I misunderstanding something? Or are there no implementation examples of ICE and no results of IKE? 

Also, how can we get the evaluation performance from the results.json file? Do we have to run the editor.py code using the results.json file? Or is it just averaging it? 

Thank you.

**Comment by zxlzr** [comment]
Hi, 

sorry, we will update the KnowEdit.md ASAP. 

Best

**Comment by zxlzr** [comment]
hi, AdaLoRA has been updated, SERAC and ICE will be updated soon after testing.

**Comment by XeeKee** [comment]
Thank you very much for your interest in EasyEdit. Serac now supports it, and we warmly welcome you to use it!

**Comment by littlefive5** [comment]
I have added the `ICE` method, `ICE` is the same setting as `IKE` but the `use_icl_examples` is False. See https://github.com/zjunlp/EasyEdit/blob/main/examples/run_knowedit_llama2.py#L248 for details.

**Comment by zxlzr** [comment]
Hi, do you have any further questions?

**Comment by gkruddl** [comment]
No, that's all. I really appreciate your fast update. Thank you!

**Comment by gkruddl** [comment]
Hi, after updating the code, there is no ['post']['fluency'] results in the output file. I am not getting the fluency results .
