### ISSUE TITLE
Some questions about evaluation metrics.

### ISSUE THREAD

**Issue by asdfo123** [zjunlp/EasyEdit#434]
Hi! Thanks for your great work!

Recently, I've been reading several papers on model editing and encountered some issues about evaluation metrics.

From my understanding, the evaluation metrics used in EasyEdit are token-level, comparing the target_new output with the model's predictions token by token and a 33.3% Reliability is possible.(only match 1 in 3 tokens)

However, in the original ROME paper, I noticed a different approach when using the ZsRE and Counterfact datasets:
The Efficacy(Eff. used for ZsRE)  is defined as whether the output tokens are completely the same as  target_new tokens(only true and false), while the Efficacy Success(ES, used for Counterfact) is defined as whether the edited output is more probable than original output.

I have 2 questions:
1. Why does EasyEdit choose this token-level Evaluation Metrics?
2. If I want to change the metrics in EasyEdit into the Efficacy and ES form, where should I change?

**Comment by pengzju** [comment]
Thank you for your interest in our work and for your insightful questions.

Q1:  The ROME metrics indeed offer two extremes: exact match (binary outcomes) and probability comparison. We believe that these may not always provide the most nuanced assessment of editing robustness. Token-level accuracy, as used in EasyEdit, offers a more granular view of how well edits are being made, aligning with the idea that each token's correctness contributes to the overall reliability of the edit.  It's up to you whether to follow EMNLP's token-level approach or ROME's original metrics.

Q2: To adopt ROME's metrics in EasyEdit, you'll need to modify the evaluation scripts to calculate Efficacy (binary match) and Efficacy Success (probability comparison). You can refer to ROME's official repository: https://github.com/kmeng01/rome

**Comment by zxlzr** [comment]
hi, do you have any further questions?
