### ISSUE TITLE
mom2_dtype: "float32"

### ISSUE THREAD

**Issue by dongdongzhaoUP** [zjunlp/EasyEdit#436]
Thanks for your work. I am wondering if i can change mom2_dtype: "float32" to mom2_dtype: "float16" to save GPU memory(tried but get error).

**Comment by dongdongzhaoUP** [comment]
For ROME

**Comment by pengzju** [comment]
应该不行

**Comment by pengzju** [comment]
mom2 is the precision of the inverse Key matrix. Reducing its precision would not lead to significant savings in GPU memory, and the decrease in precision might impact performance. If the GPU resources are insufficient, you can enable model_parallel.

**Comment by zxlzr** [comment]
hi, do you have any further questions?

**Comment by dongdongzhaoUP** [comment]
Thanks. It is true that mom2 can not directly save GPU memory, but I think in this way i can define the edited model in float16, to save memory.

**Comment by XeeKee** [comment]
You are correct, you can refer to the code here for modifications: https://github.com/zjunlp/EasyEdit/blob/9ce2ab4b157c9f4fcbb729915ce998bbf2e94183/easyeditor/editors/editor.py#L100

**Comment by zxlzr** [comment]
hi, do you have any further questions?
