### ISSUE TITLE
Question About Generating the Edit Requests

### ISSUE THREAD

**Issue by baselmousi** [zjunlp/EasyEdit#438]
Hi, 

I was trying to run the rome method on a custom created dataset. I created a dataset having the same structure as ZsRE but with different samples. 

I tried to run ROME but I obtained an error when generating the requests. The error indicates that the subject field should be included within the prompt (Specifically, line 81 in the easyeditor/editors/utils.py file).  

Why is it necessary to have the subject included in the prompt?

**Comment by XeeKee** [comment]
Hello, thank you very much for your interest in easyedit. You can refer to Chapter 2 of the original [ROME 
paper](https://arxiv.org/pdf/2202.05262), "Interventions on Activations for Tracing Information Flow," for a detailed explanation. You can also modify the code yourself by specifying the last token as the subject, which can yield good results (though there is still quite a difference from the actual subject).

**Comment by zxlzr** [comment]
hi, do you have any further questions?

**Comment by shariqahn** [comment]
If we have a dataset of prompts and answers, how can we best determine the subject of the prompt rather than just relying on the last token?
