### ISSUE TITLE
Questions about train_DINM_for_NLPCC.py

### ISSUE THREAD

**Issue by hundred-henry** [zjunlp/EasyEdit#439]
Hello,

I encountered several questions and bugs while running train_DINM_for_NLPCC.py using DIMN:

1. Is train_DINM_for_NLPCC.py complete?
Based on the comments in Issue #385, it seems the script is intended for SFT and DPO. However, I couldn't find any implementation or references related to SFT or DPO in the code. Could you clarify this?

2. Bug when running the script:

File "/root/EasyEdit/train_DINM_for_NLPCC.py", line 67, in <module>
    editor.edit(
File "/root/EasyEdit/easyeditor/editors/safety_editor.py", line 177, in edit
    "pre": compute_safety_edit_quality(self.model, self.tok, request,
File "/root/EasyEdit/easyeditor/evaluate/safety_evaluate.py", line 39, in compute_safety_edit_quality
    batch = [record["prompt"]] + record['general_prompt']
KeyError: 'general_prompt'

I couldn’t find any key named 'general_prompt' in the dataset or related code. Did I miss something? Could you provide guidance on how to resolve this issue?

**Comment by mengrusun** [comment]
The script train_DINM_for_NLPCC.py is specifically designed for the NLPCC 2024 competition and is not intended for SFT or DPO. If you'd like to use our DINM as a baseline, please run [run_safety_editing.py](https://github.com/zjunlp/EasyEdit/blob/main/examples/run_safety_editing.py). You can obtain the guidence in [here](https://github.com/zjunlp/EasyEdit/blob/main/examples/SafeEdit.md).

For FT, refer to the def test_FT() function in [edit.py](https://github.com/zjunlp/EasyEdit/blob/main/edit.py), and for DPO, ref to the def test_DPO_llama() function in [edit.py](https://github.com/zjunlp/EasyEdit/blob/main/edit.py).
If you want to use SFT and DPO in edit.py to run the SafeEdit dataset, you'll need to make some modifications based on run_safety_editing.py.

**Comment by hundred-henry** [comment]
Thank you for your reply!
I will run run_safety_editing.py instead.
