### ISSUE TITLE
ROME + GPT-2XL + zSRE replicate results

### ISSUE THREAD

**Issue by NamburiSrinath** [zjunlp/EasyEdit#44]
Hi,

Thank you so much for your support and wonderful repo :)

I was able to run the ROME + GPT2XL from `edit.py` and am able to observe the metrics and edited model. The `test_ROME()` is basically used to insert few manually designed facts/prompts described in the function.

I would like to run the repo for entire zSRE dataset i.e would like to replicate the results from Table 1 from official ROME paper (https://arxiv.org/pdf/2202.05262.pdf)

Thanks
Srinath

**Comment by tbozhong** [comment]
Thank you for your attention!

To replicate the results of ROME, you can refer to `examples/run_zsre_llama2.py` to process the entire dataset into the parameter format accepted by `editor.edit()`:


```arduino
{
    'prompt': prompt,
    'target_new': target_new,
    'ground_truth': ground_truth,
    'subject': subject,
    'portability': {},
    'locality': {}
}
```
By doing so, you will be able to reproduce the ROME results.

**Comment by NamburiSrinath** [comment]
Thanks for quick response @tbozhong, 

I have the JSON file `zsre_mend_eval_portability_gpt4.json` and here's the command I ran:
`python run_zsre_llama2.py --editing_method "ROME" --hparams_dir "../hparams/ROME/gpt2-xl.yaml" --data_dir "../data/data"`

```
Traceback (most recent call last):
  File "/hdd4/srinath2/EasyEdit/examples/run_zsre_llama2.py", line 78, in <module>
    metrics, edited_model, _ = editor.edit(
  File "/hdd4/srinath2/EasyEdit/examples/../easyeditor/editors/editor.py", line 197, in edit
    "pre": compute_edit_quality(self.model, self.model_name, self.hparams, self.tok, request,
  File "/hdd4/srinath2/EasyEdit/examples/../easyeditor/evaluate/evaluate.py", line 70, in compute_edit_quality
    compute_portability_quality(model, model_name, hparams, tok, portability_key,
  File "/hdd4/srinath2/EasyEdit/examples/../easyeditor/evaluate/portability_evaluate.py", line 24, in compute_portability_quality
    portability_correct = test_prediction_acc(model, tok, hparams, prompt, ground_truth, device)
  File "/hdd4/srinath2/EasyEdit/examples/../easyeditor/evaluate/evaluate_utils.py", line 109, in test_prediction_acc
    if isinstance(answers[0], list):
IndexError: list index out of range
```

I can try to debug, but still sharing here so if there's something, you can update the codebase :)

**Comment by pengzju** [comment]
same as #43

**Comment by zxlzr** [comment]
Hi, have you solved your issue?

**Comment by NamburiSrinath** [comment]
Sorry about the delay, yes the issue has been resolved by adding this line

`hparams.max_length = 100`
