### ISSUE TITLE
Ignore this! Wrong repo

### ISSUE THREAD

**Issue by shariqahn** [zjunlp/EasyEdit#441]
(Sorry I posted this in the wrong repo.)

**Comment by shariqahn** [comment]
And if anyone has suggestions on how to ensure I reproduced the metrics properly with just the finetuned and unlearned models that are already provided, I'm happy to hear them!

**Comment by zxlzr** [comment]
Hi, Could you please specify which paper you are referring to? In our work, we do not include unlearning or the phi model.

**Comment by zxlzr** [comment]
You can reproduce the llama2 results following:

 https://github.com/zjunlp/EasyEdit/blob/main/examples/README.md  on paper "Editing Large Language Models: Problems, Methods, and Opportunities".

https://github.com/zjunlp/EasyEdit/blob/main/examples/KnowEdit.md  on paper "A Comprehensive Study of Knowledge Editing for Large Language Models".

**Comment by zxlzr** [comment]
If you have any problems when using EasyEdit, feel free to contact us. We have recently fixed some bugs, which may lead to different performance, please see https://github.com/zjunlp/EasyEdit/issues/427  We deeply apologize for any inconvenience caused by this bug.

**Comment by shariqahn** [comment]
Sorry, I posted this in the wrong repo. I would suggest deleting it. Thank you for the prompt response!

**Comment by zxlzr** [comment]
It's all good, brother.
