### ISSUE TITLE
Loading SERAC Trained Model

### ISSUE THREAD

**Issue by shariqahn** [zjunlp/EasyEdit#442]
I see that you shared the trained SERAC model in https://drive.google.com/drive/folders/1rVWN7z05CHkIwbOJ5Cy3E0seWSpU6SeT. However, I am having trouble loading these weights in order to test editing for the ZsRE dataset for example because it is not in a format I am familiar with. Do you mind pointing me in the right direction? Also, I thought SERAC only requires training the small model, not the base model. So why are these weights for llama-2-7b rather than llama-160m?

**Comment by JizhanFang** [comment]
Hi,

1. As you mentioned, we have provided the trained checkpoint on Google Drive. For example, with the llama2-7b model, you simply need to download the **llama-2-7b.bk** file from Google Drive and place it in the `EasyEdit/results/models/SERAC/llama2-7b.bk` position. Then, set the `archive` field in the SERAC hyperparameter file to this path ( for example, `archive: ./results/models/SERAC/llama-2-7b.bk`). Additionally, when running the process, you do not need to train the model using the Trainer class. Instead, you can directly use the Editor class for editing.

2. The SERAC method only requires training the scope classifier and the counterfactual model. When base model is llama2-7b, the scope classifier is set to distilbert-base-cased by default, and the counterfactual model is set to llama-160m by default. Therefore, the weights we provide are not the base model weights, these files are simply named by the base model for convenience.

**Comment by zxlzr** [comment]
hi, have you solved your issue yet?

**Comment by shariqahn** [comment]
I understand that the checkpoint was trained on the CounterFact dataset, but I'm not seeing the results for Llama and CounterFact in any of your papers. Do you happen to have the results for CounterFact or checkpoint for ZsRE? Here are my results for ZsRE using the checkpoint you provided:
```
Metrics Summary:  {'pre': {'rewrite_acc': 0.40287348593761324, 'rephrase_acc': 0.39428592943539903, 'portability': {'one_hop_acc': 0.566645032103213}}, 'post': {'rewrite_acc': 0.9630600327562718, 'rephrase_acc': 0.6961480793930168, 'locality': {'neighborhood_acc': 0.9986392371156113}, 'portability': {'one_hop_acc': 0.5736743852938706}}}
```
The rephrase accuracy seems quite low.
