### ISSUE TITLE
Questions About the WISE Model Configuration File and the Temporal Dataset

### ISSUE THREAD

**Issue by Eliaukyh** [zjunlp/EasyEdit#443]
1. Could you provide the config.yaml for the Mistral-7B model so that I can replicate your results on the Hallucination dataset?

2. In the Temporal dataset, there are only 75 data points. How can I access more data?

I look forward to your reply. Thank u very much!

**Comment by Eliaukyh** [comment]
Thank you for your reply.
 
Regarding the Temporal dataset, I found that T=100 in Table 5 of the WISE paper, so I assumed the Temporal dataset contains 100 data points. 
![image](https://github.com/user-attachments/assets/f26b6372-f741-4f29-a123-dc62e55bfc2c)

Thanks again for your prompt response.

**Comment by pengzju** [comment]
Apologies for any confusion. I meant to convey that in Table 5 of the WISE paper, T=100 is indicative of using the entire dataset (more precisely, T=75). It seems we have overlooked the size of the dataset. If you wish to reproduce T=100, you can indeed utilize the full dataset for your experiment.

**Comment by pengzju** [comment]
Thank you for your clarification. I will make sure to update the information on arXiv accordingly.
