### ISSUE TITLE
cantnot find  zsre_mend_eval_portability_gpt4.json

### ISSUE THREAD

**Issue by 05542133179** [zjunlp/EasyEdit#444]
I hope this message finds you well. I am currently unable to find the file zsre_mend_eval_portability_gpt4.json. Could you please provide the download link or any guidance on how I can access this file?

**Comment by XeeKee** [comment]
Our data has been uploaded to Google Drive. In which paper does the zsre_mend_eval_portability_gpt4.json you mentioned appear?

**Comment by 05542133179** [comment]
in examples/readme.md  In the paper [EasyEdit: An Easy-to-use Knowledge Editing Framework for Large Language Models](https://arxiv.org/abs/2308.07269), the data set we used is zsre_mend_eval_portability_gpt4.json, so you should place it in the ./data directory.

**Comment by XeeKee** [comment]
It seems that this readme is too outdated. We will update it soon, and you can try using other datasets in the meantime.

**Comment by 05542133179** [comment]
Thank you for the update!I'll explore other datasets in the meantime. Looking forward to the updated version!

**Comment by shariqahn** [comment]
I have been using the Google Drive data, specifically data/portability/One Hop/zsre_mend_eval_portability_gpt4.json. My results seem reasonable so far, but I can't confirm that is the data referenced in the README.

**Comment by zxlzr** [comment]
hi, do you have any further questions?
