### ISSUE TITLE
Inquiry Regarding the Hallucination Dataset

### ISSUE THREAD

**Issue by YamingGuo98** [zjunlp/EasyEdit#448]
When using the example with run_wise_editing.py, I encountered an error with GRACE during hallucination:

`2024-12-14 02:09:27,643 - easyeditor.editors.editor - INFO - Instantiating model
2 Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00,  6.77it/s]
3 2024-12-14 02:09:28,640 - easyeditor.editors.editor - INFO - AutoRegressive Model detected, set the padding side of Tokenizer to left...
4   0%|                                                                                                              | 0/600 [00:00<?, ?it/s]Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
5 We detected that you are passing `past_key_values` as a tuple and this is deprecated and will be removed in v4.43. Please use an appropriate `Cache` class (https://huggingface.co/docs/transformers/v4.41.3/en/internal/generation_utils#transformers.Cache)
6  14%|██████████████▍                                                                                      | 86/600 [07:09<42:45,  4.99s/it]
7 Traceback (most recent call last):
8   File "/home/easyedit/run_wise_editing.py", line 165, in <module>
9     metrics, edited_model, _ = editor.edit(
10   File "/home/easyedit/easyeditor/editors/editor.py", line 229, in edit
11     return self.edit_requests(requests, sequential_edit, verbose, test_generation=test_generation, **kwargs)
12   File "/home/easyedit/easyeditor/editors/editor.py", line 346, in edit_requests
13     metrics = {"pre": compute_edit_quality(self.model, self.model_name, self.hparams, self.tok, request, self.hparams.device, eval_metric=eval_metric, test_generation=test_generation)}
14   File "/home/easyedit/easyeditor/evaluate/evaluate.py", line 78, in compute_edit_quality
15     compute_locality_quality(model, model_name, hparams, tok, locality_key,
16   File "/home/easyedit/easyeditor/evaluate/evaluate.py", line 153, in compute_locality_quality
17     loc_tokens = test_prediction_acc(model, tok, hparams, prompt, locality_ground_truth, device, locality=True, vanilla_generation=hparams.alg_name=='GRACE')
18   File "/home/easyedit/easyeditor/evaluate/evaluate_utils.py", line 91, in test_prediction_acc
19     gen_token = model.generate(
20   File "/home/user/miniconda3/envs/EasyEdit/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
21     return func(*args, **kwargs)
22   File "/home/user/miniconda3/envs/EasyEdit/lib/python3.9/site-packages/transformers/generation/utils.py", line 1688, in generate
23     generation_config, model_kwargs = self._prepare_generation_config(generation_config, **kwargs)
24   File "/home/user/miniconda3/envs/EasyEdit/lib/python3.9/site-packages/transformers/generation/utils.py", line 1391, in _prepare_generation_config
25     model_kwargs = generation_config.update(**kwargs)
26   File "/home/user/miniconda3/envs/EasyEdit/lib/python3.9/site-packages/transformers/generation/configuration_utils.py", line 1207, in update
27     self.validate()
28   File "/home/user/miniconda3/envs/EasyEdit/lib/python3.9/site-packages/transformers/generation/configuration_utils.py", line 544, in validate
29     raise ValueError(f"`max_new_tokens` must be greater than 0, but is {self.max_new_tokens}.")
30 ValueError: `max_new_tokens` must be greater than 0, but is 0.
`

I found that in some examples from the hallucination dataset, the locality_ground_truth is empty, for instance:
`{
    "prompt": "This is a Wikipedia passage about k. s. manilal. K. S. Manilal (1925\u20132006) was an Indian botanist and plant taxonomist who specialized in the study of the flora of the Western Ghats. He was a professor at the University of Calicut and the founder of the Centre for Advanced Studies in Botany at the University. He was a Fellow of the Indian Academy of Sciences and the Indian National Science Academy. He was also a recipient of the Padma Shri, the fourth highest civilian award in India. Manilal was born in 1925 in the village of Kallar in Kerala.",
    "target_new": "Medicinal properties of plants are translated and interpreted, with commentaries on their Malayalam names given by van Rheede.",
    "subject": "k. s. manilal",
    "locality_prompt": "The wedding walk of the newlyweds Marina and Nicholas in folklore style. Ukraine. Kiev.",
    "locality_ground_truth": ""
}
`

I am working on reproducing the results from your NeurIPS paper. I was wondering if there might be an issue with the hallucination dataset provided.

Thank you very much for your time and support. I look forward to hearing from you.

**Comment by zxlzr** [comment]
Hi, do you have any further questions?

**Comment by YamingGuo98** [comment]
Thank you very much for your helpful response. I have no further questions at this time.
