### ISSUE TITLE
Question about pre-trained weights for layers of llama2-7b-chat

### ISSUE THREAD

**Issue by Victor-model** [zjunlp/EasyEdit#453]
Hi! Thanks for your great work! Currently I'm reproducing your work. I notice that you've prepared the pre-trained weights for layers `[4,5,6,7,8]` of llama2-7b. 

I want to edit Llama2-7b-chat-hf with MEMIT, can I use your `npz` file directly, or should I calculate it locally again?

**Comment by XeeKee** [comment]
yes, you can~
