### ISSUE TITLE
How to test the general performance of edited model using opencompass?

### ISSUE THREAD

**Issue by ABi-dot** [zjunlp/EasyEdit#454]
Thank you for the work you have done on this project. In the article Detoxifying Large Language Models via Knowledge Editing, I noticed that you used OpenCompass to test the general performance of the edited models. Could you please advise me on how to conduct such tests? Additionally, how can I save the weights of the edited models? Thank you!

**Comment by mengrusun** [comment]
Thank you for your attention to our work.

- For using Opencompass, please refer to the official Opencompass documentation. 
- You can save the edited_model (line 190 in [safety_editor.py](https://github.com/zjunlp/EasyEdit/blob/main/easyeditor/editors/safety_editor.py)) using the torch.save() function.

**Comment by zxlzr** [comment]
hi, have you solved your issue yet?
