### ISSUE TITLE
MMEdit question

### ISSUE THREAD

**Issue by LiuJinzhe-Keepgoing** [zjunlp/EasyEdit#456]
I really want to try this job. But unfortunately, I only have 4090, so I can't reason on a single card. Excuse me, when can MMEdit run with multiple cards?

**Comment by tbozhong** [comment]
Hi there,

I notice that the 4090 GPU has 24GB of VRAM, which should be sufficient to run experiments with `MEND`,` SERAC`, and `IKE` on the `BLIP2OPT` model within MMEdit. Regarding larger-scale models, we are working on supporting them and will provide updates as soon as possible.

**Comment by zxlzr** [comment]
hi, do you have any further questions?
