### ISSUE TITLE
ROME + llama-2-7b +" Can't load the configuration of './hugging_cache/llama-2-7b'"

### ISSUE THREAD

**Issue by pangqianiqian** [zjunlp/EasyEdit#46]
我的examples 目录如下：
![image](https://github.com/zjunlp/EasyEdit/assets/77775690/28d6c60f-604b-4dc0-be19-e658412a20e5)

运行命令“python run_zsre_llama2.py --editing_method=ROME  --hparams_dir=../hparams/ROME/llama-7b --data_dir=./data”报错如下，请问怎么解决：
![image](https://github.com/zjunlp/EasyEdit/assets/77775690/8f5aba09-3c7b-4cd2-bf92-6126a7cf131d)

**Comment by pengzju** [comment]
Hello, you can download the huggingface weight of `llama-2-7b` to the local and place it under `./hugging_cache/llama-2-7b`. The above error stems from an inability to load the model.

**Comment by pengzju** [comment]
> Hello, you can download the huggingface weight of `llama-2-7b` to the local and place it under `./hugging_cache/llama-2-7b`. The above error stems from an inability to load the model.

https://huggingface.co/meta-llama/Llama-2-7b-hf

**Comment by pangqianiqian** [comment]
好的感谢，我已申请下载权限，之后再试试
![G9NJ@3NNJWK~XA(R$TN}0Q0](https://github.com/zjunlp/EasyEdit/assets/77775690/777a97a3-15cb-4ab8-8967-07a775c4b281)

**Comment by zxlzr** [comment]
请问您的问题解决了吗？

**Comment by pangqianiqian** [comment]
暂时还没有，Hugging Face上还不能下载Llama-2-7b的模型，你们能提供下吗

**Comment by pengzju** [comment]
您好，llama2是Gated model(需要通过Facebook的申请才能获取到权重)。如果时间不允许您继续等待，可以采用llama1作为backbone模型，两者的架构相同，性能相近。llama1的link：https://huggingface.co/decapoda-research/llama-7b-hf

**Comment by pengzju** [comment]
如果解决了您的问题，请帮忙关闭此issue，再次感谢您对EasyEdit的关注

**Comment by pangqianiqian** [comment]
OK thanks

**Comment by pangqianiqian** [comment]
OK thanks
