### ISSUE TITLE
Any batch size to recommend for MEMIT batch edit?

### ISSUE THREAD

**Issue by Wenyueh** [zjunlp/EasyEdit#47]
Hello, I'm editing MEMIT on llama-7b and llama-13b models with thousands of edits. 

If I use batch size = 1 for batch_edit(), then after a few hundred edits the model parameters are completely destroyed.

So, is there any batch size that you recommend?

**Comment by pengzju** [comment]
- Whether you set `keep_original_weights` to `True`?
- I recommend that you try `batch_size=10` or larger, you don't need to worry about oom because MEMIT has a special processing mechanism

**Comment by Wenyueh** [comment]
I set keep_original_weights=False. So it should be set to True?

Okay I will try batch_size >= 10, thx!

**Comment by pengzju** [comment]
- When you set `keep_original_weights` to `False`, the editing scene is sequential editing, which does damage the model very quickly, as you can see in the paper: https://arxiv.org/abs/2305.13172

**Comment by Wenyueh** [comment]
I see. Thank you very much!!
