### ISSUE TITLE
does not appear to have a file named config.json

### ISSUE THREAD

**Issue by cccusername** [zjunlp/EasyEdit#48]
执行命令：
`python run_zsre_llama2.py \
    --editing_method=IKE \
    --hparams_dir=../hparams/IKE/llama-7b \
    --data_dir=/home/chenhw/llm/EasyEdit-main/Data/zsre`
![20231008101616](https://github.com/zjunlp/EasyEdit/assets/33566026/86ae92a5-fadd-47ac-854b-856ea5c73a94)

提示没有config.json文件，llama2-7b的模型库好像确实没有这个文件，应该怎么解决呢
![20231008101601](https://github.com/zjunlp/EasyEdit/assets/33566026/41a14223-dcc4-43c1-b0f4-8c092f28b4b7)

**Comment by pengzju** [comment]
Please choose the right model: https://huggingface.co/meta-llama/Llama-2-7b-hf
<img width="905" alt="image" src="https://github.com/zjunlp/EasyEdit/assets/63391142/6e46cc79-0a81-44c2-876a-1c6b916f8571">

**Comment by cccusername** [comment]
> Please choose the right model: https://huggingface.co/meta-llama/Llama-2-7b-hf <img alt="image" width="905" src="https://user-images.githubusercontent.com/63391142/273421671-6e46cc79-0a81-44c2-876a-1c6b916f8571.png">

thx，i will try it again
