### ISSUE TITLE
Codes for Reproducing the Results about the Edit Performance

### ISSUE THREAD

**Issue by HamLaertes** [zjunlp/EasyEdit#5]
Hi,

Your project does provide a platform to use and compare different editing methods. 
But I do not find any .py or .sh scripts to easily reproduce the resutls in the Table of 'Edit Performance'.
May you provide a complete pipeline for the results reproduction? The pipeline better includes data preprocessing (if has), API calls to different editing methods, editing processes and the evaluation.
It will be grateful if you provide the detail scripts for reproducing.

Thanks!

**Comment by pengzju** [comment]
Thank you for your interest in EasyEdit. We will host a wide range of **example module** which includes editing examples for various methods, as well as corresponding replication scripts mentioned in our paper. 

We will develop and release the example module as soon as possible.😊

**Comment by HamLaertes** [comment]
Excited about these and looking forwards!

**Comment by pengzju** [comment]
Hi, we now support scripts to reproduce `ROME` performance on `ZsRE`, welcome to try.

https://github.com/zjunlp/EasyEdit/tree/main/examples

**Comment by HamLaertes** [comment]
Cool ! Thanks for your in time responses.
