### ISSUE TITLE
Does EasyEdit support training on H800?

### ISSUE THREAD

**Issue by peixin-lin** [zjunlp/EasyEdit#54]
In order to train on H800, I change the version of torch to `2.1.0+cu121`. The other dependencies are installed with the version specified in requirements.txt.

After I run my demo, which is adapted from the code in tutorial, I got this error:

```
Use device: cuda:0
2023-10-10 10:41:37,603 - easyeditor.editors.editor - INFO - Instantiating model
10/10/2023 10:41:37 - INFO - easyeditor.editors.editor -   Instantiating model
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:46<00:00,  6.67s/it]
Getting coarse neurons for each prompt...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:02<00:00,  2.49s/it]

484 coarse neurons found - refining
484 neurons remaining after refining

Before modification - groundtruth probability: tensor([2.2667e-07], device='cuda:0')
Argmax completion: `King`
Argmax prob: 0.17146547138690948
Traceback (most recent call last):
  File "/home/workspace/EasyEdit/demo-chatglm2.py", line 31, in <module>
    metrics, edited_model, _ = editor.edit(
  File "/home/workspace/EasyEdit/easyeditor/editors/editor.py", line 241, in edit
    edited_model, weights_copy = self.apply_algo(
  File "/home/workspace/EasyEdit/easyeditor/models/kn/kn_main.py", line 46, in apply_kn_to_model
    results_dict, unpatch_fn = kn.edit_knowledge(
  File "/home/workspace/EasyEdit/easyeditor/models/kn/knowledge_neurons/knowledge_neurons/knowledge_neurons.py", line 906, in edit_knowledge
    return self.modify_weights(
  File "/root/anaconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/workspace/EasyEdit/easyeditor/models/kn/knowledge_neurons/knowledge_neurons/knowledge_neurons.py", line 831, in modify_weights
    output_ff_weights[:, position].detach().clone()
TypeError: 'Linear' object is not subscriptable
```
Should I change some part of the code to make it work?

The code is as follow:
```
import os
import logging

from easyeditor import BaseEditor
from easyeditor import KNHyperParams


PROJECT_PATH = os.path.dirname(os.path.abspath(__file__))
USE_DEVICE = f"cuda:0"
logging.info(f"Use device: {USE_DEVICE}")

prompts = ['Ray Charles, the',
            'Grant Hill is a professional',
            'The law in Ikaalinen declares the language'
            ]
ground_truth = ['piano',
                'basketball',
                'Finnish'
                ]
target_new = ['violin',
              'soccer',
              'Swedish'
              ]
subject = ['Ray Charles',
            'Grant Hill',
            'Ikaalinen'
            ]

hparams = KNHyperParams.from_hparams(os.path.join(PROJECT_PATH, 'hparams/KN/chatglm2-6b.yaml'))
editor = BaseEditor.from_hparams(hparams)
metrics, edited_model, _ = editor.edit(
    prompts=prompts,
    ground_truth=ground_truth,
    target_new=target_new,
    subject=subject,
    keep_original_weight=True
)

print(metrics)


print('*'*20)

from transformers import AutoTokenizer, AutoModel

# tokenizer = GPT2Tokenizer.from_pretrained('./hugging_cache/gpt2-xl')
tokenizer = AutoTokenizer.from_pretrained('/home/workspace/pretrain-model/chatglm/chatglm2-6b', trust_remote_code=True)
# tokenizer = AutoTokenizer.from_pretrained('/home/workspace/pretrain-model/THUDM/chatglm2-6b', trust_remote_code=True)
# tokenizer.pad_token_id = tokenizer.eos_token_id
tokenizer.padding_side='left'
generation_prompts = [
    "Ray Charles, the",
    "The law in Ikaalinen declares the language"
]

model = AutoModel.from_pretrained('/home/workspace/pretrain-model/chatglm/chatglm2-6b', trust_remote_code=True).to(USE_DEVICE)
# model = AutoModel.from_pretrained('/home/workspace/pretrain-model/THUDM/chatglm2-6b', trust_remote_code=True).to(USE_DEVICE)
batch = tokenizer(generation_prompts, return_tensors='pt', padding=True, max_length=30)

pre_edit_outputs = model.generate(
    input_ids=batch['input_ids'].to(USE_DEVICE),
    attention_mask=batch['attention_mask'].to(USE_DEVICE),
    max_length=10
)

post_edit_outputs = edited_model.generate(
    input_ids=batch['input_ids'].to(USE_DEVICE),
    attention_mask=batch['attention_mask'].to(USE_DEVICE),
    max_length=10
)
```

**Comment by XeeKee** [comment]
Thank you for your attention, EasyEdit currently supports chatglm2，If you have any other questions, please feel free to leave a message.

**Comment by peixin-lin** [comment]
> Thank you for your attention, EasyEdit currently supports chatglm2，If you have any other questions, please feel free to leave a message.

My question is, why would I get this error message when I run the codes that are just slightly modified from the tutorial codes?

**Comment by XeeKee** [comment]
We deeply apologize for the inconvenience regarding your situation with ChatGLM. Its architecture is quite unique; it is not the encoder-only structure found in Llama and GPT, but rather an encoder-decoder structure. Additionally, the coding style of ChatGLM is different from that of the prevailing large models, leading to bugs when trying to localize neurons. As of October 11th, we did not fully support ChatGLM. However, we have recently begun to fully support all fine-tuning methods for ChatGLM. If you encounter any issues while running the code, please feel free to contact us.

**Comment by XeeKee** [comment]
We have updated the code,EasyEdit now supports ChatGLM2. You can git pull  to retrieve the latest version. If you encounter any further issues, please feel free to contact us

**Comment by zxlzr** [comment]
> > Thank you for your attention, EasyEdit currently supports chatglm2，If you have any other questions, please feel free to leave a message.
> 
> My question is, why would I get this error message when I run the codes that are just slightly modified from the tutorial codes?
> 
> ```
> Traceback (most recent call last):
>   File "/home/workspace/EasyEdit/demo-chatglm2.py", line 31, in <module>
>     metrics, edited_model, _ = editor.edit(
>   File "/home/workspace/EasyEdit/easyeditor/editors/editor.py", line 241, in edit
>     edited_model, weights_copy = self.apply_algo(
>   File "/home/workspace/EasyEdit/easyeditor/models/kn/kn_main.py", line 46, in apply_kn_to_model
>     results_dict, unpatch_fn = kn.edit_knowledge(
>   File "/home/workspace/EasyEdit/easyeditor/models/kn/knowledge_neurons/knowledge_neurons/knowledge_neurons.py", line 906, in edit_knowledge
>     return self.modify_weights(
>   File "/root/anaconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "/home/workspace/EasyEdit/easyeditor/models/kn/knowledge_neurons/knowledge_neurons/knowledge_neurons.py", line 831, in modify_weights
>     output_ff_weights[:, position].detach().clone()
> TypeError: 'Linear' object is not subscriptable
> ```

Hi buddy, you can pull the code and try again. If any problems, please contact us.

**Comment by zxlzr** [comment]
Have you solved your issue?
