### ISSUE TITLE
Knowledge Editing with BERT on FEVER Dataset

### ISSUE THREAD

**Issue by guanqun-yang** [zjunlp/EasyEdit#59]
I skimmed through the code base, and it seems to me that it is **not** possible to use `easyedit` to edit an encoder-only model (like BERT) on the classification task (like FEVER) even though many of the original papers, including [KnowledgeEditor by De Cao et al.](https://arxiv.org/pdf/2104.08164.pdf) and [MEND by Mitchell et al.](https://arxiv.org/pdf/2110.11309.pdf) do show such possibility.

Do you know if this observation is accurate? If true, would you like to add support for encoder-only models? If not, please give me the pointer to reproduce the knowledge editing experiment for the FEVER dataset on BERT.

**Comment by pengzju** [comment]
- Sorry, EasyEdit doesn't support editing `bert` class models yet, you can use the original open-source code. (like https://github.com/eric-mitchell/mend)
- Of course, we also welcome your pr to support bert model
