### ISSUE TITLE
如何在ZsRE数据集上进行测试呢？

### ISSUE THREAD

**Issue by XZhang00** [zjunlp/EasyEdit#6]
您好！有一些不太懂的地方想请教您一下：

在使用ZsRE数据集测试时，具体流程是什么样的呢？
对于只能单条编辑的方法，是全部顺序编辑后再测试？还是编辑完一条后就测一条呢？
涉及到需要训练模型的编辑方法是需要先在数据集上训练完后，再对数据集整体进行测试吗？

希望您能抽空回答一下！ 非常感谢！

**Comment by pengzju** [comment]
问题一：测试zsre数据集，您可以参考以下代码

```python
test_data = json.load(open('./data/zsre_mend_eval.json', 'r', encoding='utf-8'))
prompts = [test_data_['src'] for test_data_ in test_data] #编辑输入
target_new = [test_data_['alt'] for test_data_ in test_data] #编辑输出
hparams = XXXHparams.from_hparams('./hparams/ROME/gpt2-xl') #例如ROME
editor = BaseEditor.from_hparams(hparams)
metrics, edited_model, _ = editor.edit(
    prompts=prompts,
    target_new=target_new,
    keep_original_weight=True
)
```
后续我们会开放`example`模块，来轻松复现实验细节

问题二：对于只能单条编辑的方法，是编辑完一条后就测一条。每次编辑都会测试其performance

问题三：涉及到需要训练模型的编辑方法（SERAC、MEND）需要预训练一些网络结构，例如external model, hypernetwork. 请先使用Trainer训练后load权重再进行编辑

**Comment by XZhang00** [comment]
好的，明白了！ 非常感谢您快速的解答！
想再确认一下，问题三中，如果要对数据集zsre_mend_eval.json进行测试，那是需要先在zsre_mend_eval.json上对额外的网络结构进行训练，然后load训练好的权重，再在zsre_mend_eval.json测试得到编辑结果吗？

**Comment by pengzju** [comment]
不是的，如果使用了需要额外训练的方法，需要在xxx_train.json上进行训练，在eval上训练会造成标签泄漏。

另外，如果你想复现原论文中的结果，可以参考此处：https://github.com/zjunlp/EasyEdit/tree/main/examples

**Comment by XZhang00** [comment]
好的，感谢感谢！
