### ISSUE TITLE
在使用KN编辑Chatglm2-6b时出现TypeError报错

### ISSUE THREAD

**Issue by HLiang-Lee** [zjunlp/EasyEdit#60]
您好，EasyEdit是一个非常好用的工具，在使用EasyEdit对Chatglm2-6b进行知识编辑时，出现如下报错：
`  File "/path/to/EasyEdit/lib/python3.9/site-packages/easyeditor/models/kn/knowledge_neurons/knowledge_neurons/knowledge_neurons.py", line 836, in modify_weights
    output_ff_weights[:, position].detach().clone()
TypeError: 'Linear' object is not subscriptable`
运行的源代码如下：
`import os

os.environ['CUDA_VISIBLE_DEVICES'] = "0,1,2,3"

from easyeditor import BaseEditor
from easyeditor import KNHyperParams

ENG_TEXTS = [
    "Sarah was visiting the capital of france,",
    "The capital of france is",
    "The eiffel tower is situated in"
]
ground_truth = ['Paris',
                'Paris',
                'Paris'
                ]
target_new = ['Beijing',
              'Beijing',
              'Beijing'
              ]
haprams = KNHyperParams.from_hparams("/path/to/EasyEdit/hparams/KN/chatglm2-6b.yaml")
editor = BaseEditor.from_hparams(haprams)
metrics, edited_model, _ = editor.edit(
    prompts=ENG_TEXTS,
    ground_truth=ground_truth,
    target_new=target_new,
    keep_original_weight=True
)

print(metrics)

print('*'*20)

from transformers import GPT2Tokenizer
from transformers import GPT2LMHeadModel

tokenizer = GPT2Tokenizer.from_pretrained('/path/to/chatglm2-6b')
tokenizer.pad_token_id = tokenizer.eos_token_id
tokenizer.padding_side='left'
generation_prompts = [
    "The eiffel tower is situated in ",
    "The capital of france is "
]

model = GPT2LMHeadModel.from_pretrained('/path/to/chatglm2-6b').to('cuda')
batch = tokenizer(generation_prompts, return_tensors='pt', padding=True, max_length=30)

pre_edit_outputs = model.generate(
    input_ids=batch['input_ids'].to('cuda'),
    attention_mask=batch['attention_mask'].to('cuda'),
    max_length=10
)

post_edit_outputs = edited_model.generate(
    input_ids=batch['input_ids'].to('cuda'),
    attention_mask=batch['attention_mask'].to('cuda'),
    max_length=10
)

`
希望可以帮我解决上述困难，非常感谢～

**Comment by XeeKee** [comment]
We recently fixed this bug.you can try to pull the code and try again. If any problems, please contact us.

**Comment by HLiang-Lee** [comment]
I'm sorry, it's a problem with my local code version. Thank you~
