### ISSUE TITLE
Test case for ChatGLM2

### ISSUE THREAD

**Issue by lukaswangbk** [zjunlp/EasyEdit#61]
Hi, I am trying to use ROME edit on ChatGLM2, while I noticed that the performance (avg prob) after training is significantly low. Could you please share some examples for editing ChatGLM2? Here's some of my cases

1. **Case 1**: ENGLISH CASE
    prompts = ['Ray Charles, the']
    ground_truth = ['piano']
    target_new = ['violin']
    subject = ['Ray Charles'] 

   **avg prob: 0.01**

2. **Case 2**: CHINESE CASE
    prompts = ['中国的首都是']
    ground_truth = ['北京']
    target_new = ['上海']
    subject = ['中国']
    
    **avg prob: 0.01**

Both cases I used the default setting in yaml file. I also tried to raise up the grad_steps (to 100) while the maximum of prob is 0.1 which is not sufficient for editing. Could you please help me out? Appreciate a lot.

**Comment by zxlzr** [comment]
Hi, you can try other cases, ROME may fail on some cases in ChatGLM
