### ISSUE TITLE
KN doesn't work on Llama model

### ISSUE THREAD

**Issue by wowzero** [zjunlp/EasyEdit#64]
When I try to run your code on Llama-7B model using knowledge-neurons(KN)  method, the program throw error "AttributeError: 'Parameter' object has no attribute 'weight'" on ./easyeditor/models/kn/knowledge_neurons/knowledge_neurons/knowledge_neurons.py line 810. Does your framework support the llama model?

**Comment by pengzju** [comment]
If you encounter any further issues, please feel free to contact us.

**Comment by Thewillman** [comment]
Well,I think there are some problems with KN
code in modify_weights function in knowledge_neurons.py
```
def unpatch_fn():
            # reverse modified weights
            for idx, (layer_idx, position) in enumerate(neurons):
                output_ff_weights = self._get_output_ff_layer(layer_idx)
                if self.model_type == "gpt2":
                    output_ff_weights[position, :] = original_weight_values[idx]
                else:
                    output_ff_weights[:, position] = original_weight_values[idx]

        if undo_modification:
            print("undo modification")
            unpatch_fn()
            unpatch_fn = lambda *args: args

        return results_dict, unpatch_fn
```
And in editor.py, the code looks weird, weights_copy() is a function, where is the items() attribute?
```
  with torch.no_grad():
                #print(help(weights_copy))
                # import pdb; pdb.set_trace()
                for k, v in weights_copy.items():
                    nethook.get_parameter(self.model, k)[...] = v.to(f"cuda:{self.hparams.device}")
```
the error is here:
`for k, v in weights_copy.items():
AttributeError: 'function' object has no attribute 'items'`

**Comment by XeeKee** [comment]
I have fixed this bug ,you can pull the newest code.If you encounter any further issues, please feel free to contact us

**Comment by zxlzr** [comment]
Have you solved your issue?

**Comment by wowzero** [comment]
> Have you solved your issue?
Sure, it works. thx
