### ISSUE TITLE
Provide MEND and SERAC trained models

### ISSUE THREAD

**Issue by domenicrosati** [zjunlp/EasyEdit#66]
Hey there,

Do you think you could provide the MEND and SERAC model artifiacts you trained for GPT2-XL, GPT-J, and LLama2?
It would be much appreciated!

**Comment by domenicrosati** [comment]
Part of the issue is I am getting OOM on GPT-J and LLama2 for MEND and GPT-j for SERAC (i set the batch sizes all to 1). This is all on a 40GB VRAM A100 so any tips here would be appreciated!

**Comment by domenicrosati** [comment]
Be also nice to provide the precomputed statistics for MEMIT as it took 4 days to compile all of those for those series of models.

**Comment by XeeKee** [comment]
https://drive.google.com/drive/folders/1WyqsN-O5bpzzRvbYrVDJdVHdOu1x6mSB?usp=share_link
https://drive.google.com/drive/folders/1rVWN7z05CHkIwbOJ5Cy3E0seWSpU6SeT?usp=share_link
first url is about  mend
last url is about serac

**Comment by domenicrosati** [comment]
@XeeKee what about the memit stats?

**Comment by XeeKee** [comment]
sorry,my google drive only have 15G,there is no more room for merit

**Comment by domenicrosati** [comment]
Maybe good @XeeKee to clarify in the repo (1) Memit will take a while to compute stats (2) link to these models so folks don't need to retrain their own MEND and SERAC models

**Comment by wending0417** [comment]
Hi~ In the last two weeks, I have tried to reproduce the results with MEND + gpt2-xl/llama2-7b + COUNTERFACT, but I failed (the performance is very poor) and the maintainer of your repository can't discover the reason in https://github.com/zjunlp/EasyEdit/issues/121. In this issue, you provided the trained mend models for  gpt2-xl and llama2-7b. Could you provide these models trained on COUNTERFACT? It would be much appreciated!

**Comment by wending0417** [comment]
Hi~, I have tried to use the MEND models for gpt2-xl you provide to edit on ZsRE. But the results are really poor, there is no case achieve 1.0 for the metric `rewrite_acc` from 100 test cases. Did you meet the same issue?

**Comment by XeeKee** [comment]
Hello, we fixed the bug causing unstable MEND results in February. You can try the latest code. Please note, you must turn off model_parallel during the training of MEND, as it can only be trained on a single GPU.

**Comment by pengzju** [comment]
Dear Rosati,

I hope this message finds you well. I have had the opportunity to read your insightful work on long-form model editing evaluation, which can be found at: https://arxiv.org/abs/2402.09394. Your focus on evaluating the Edit Consistency and Internal Consistency of generated statements aligns closely with my current research for NeurIPS, where I am particularly interested in the generalization capabilities of model editing in out-of-distribution (OOD) scenarios.

I am eager to extend my work based on the foundation you have laid out in your paper. However, as your official [repository](https://github.com/domenicrosati/longform-evaluation-model-editing) has not yet made the dataset publicly available, I kindly request that you share the dataset with me at [peng2001@zju.edu.cn](mailto:peng2001@zju.edu.cn).

I extend my best wishes for the continued growth and success of the editing community. Your generosity in this matter would be greatly appreciated, and I am looking forward to your response.

Sincerely,

Peng Wang
