### ISSUE TITLE
Implement performance on ground truth in pre and post measures

### ISSUE THREAD

**Issue by domenicrosati** [zjunlp/EasyEdit#67]
For my research, I have implemented ground truth on the pre and post measures in my fork of this code base.
This is important because we don't actually know if Counterfact or zSRE are doing fact injection (introducing a brand new fact) or fact updating (changing a previously known fact) for a given model (except for the models that Counterfact and zSRE were originally measured on of course).

I am opening an issue to see if there is interest for me to merge that in.

The relevant changes are:
https://github.com/domenicrosati/EasyEdit/blob/drosati/longformedit/easyeditor/evaluate/evaluate.py#L60-L73
https://github.com/domenicrosati/EasyEdit/blob/drosati/longformedit/easyeditor/evaluate/evaluate.py#L169-L183
https://github.com/domenicrosati/EasyEdit/blob/drosati/longformedit/easyeditor/evaluate/evaluate.py#L236-L247
https://github.com/domenicrosati/EasyEdit/blob/drosati/longformedit/easyeditor/evaluate/evaluate.py#L357-L377

No worries if there is no interest! I will just keep it on my branch for my work.

**Comment by pengzju** [comment]
I appreciate your suggestion to implement `ground truth` for both pre and post measures to better understand whether Counterfact or zSRE introduce new facts or update existing ones. I've examined the changes you've proposed, and they seem like valuable additions to EasyEdit. I will consider whether to merge them into the main repository.

**Comment by pengzju** [comment]
Dear Rosati,

I hope this message finds you well. I have had the opportunity to read your insightful work on long-form model editing evaluation, which can be found at: https://arxiv.org/abs/2402.09394. Your focus on evaluating the **Edit Consistency** and **Internal Consistency** of generated statements aligns closely with my current research for NeurIPS, where I am particularly interested in the generalization capabilities of model editing in out-of-distribution (OOD) scenarios.

I am eager to extend my work based on the foundation you have laid out in your paper. However, as your official [repository](https://github.com/domenicrosati/longform-evaluation-model-editing) has not yet made the dataset publicly available, I kindly request that you share the dataset with me at [peng2001@zju.edu.cn](mailto:peng2001@zju.edu.cn).

I extend my best wishes for the continued growth and success of the editing community. Your generosity in this matter would be greatly appreciated, and I am looking forward to your response. 

Sincerely,

Peng Wang
