### ISSUE TITLE
I use two A40 GPUs and KN to edit llama2-7b. But the result is still OOM.

### ISSUE THREAD

**Issue by HLiang-Lee** [zjunlp/EasyEdit#71]
Dears,
I have used EasyEdit a lot for my study.
I use two A40 GPUs and the method KN to edit LLama2-7b. Prompts are shot prompts, just as follows.
`    TEXTS = [
        "中国→北京；法国→巴黎；美国→"
    ]
    ground_truth = [
        "华盛顿"
    ]

    target_new = [
        "纽约"
    ]`
But the code still threw the error OOM. When OOM occurs, the GPU 0' 48GB are all in use. While the GPU 1' 15.6GB/48GB  are in use. I have tried to adjust the device_map. But any pre-strategy (like "auto","balanced" and etc) is not useful. Hope for your help.

**Comment by XeeKee** [comment]
Could you please provide the hparam file?

**Comment by HLiang-Lee** [comment]
Here is my param file. Just as the example file for llama-7b.
`alg_name: "KN"
model_name: "/data/lihongliang/models/llama2-7b-hf"
device: 0
model_parallel: true

lr_scale: 1.0
n_toks: 10
refine: false
batch_size: 1
steps: 1
adaptive_threshold: 0.2
p: 0.4`

**Comment by pengzju** [comment]
或许是因为kn收集的neuron过多，在处理梯度时爆了显存。我的建议是您可以提高adaptive_threshold（或许您可以尝试0.4甚至更高），从而提高收集neuron的门槛。

**Comment by zxlzr** [comment]
Have you solved your issue?

**Comment by HLiang-Lee** [comment]
Your suggestions help me a lot. Thank you very much~
