### ISSUE TITLE
qwen14b

### ISSUE THREAD

**Issue by LiuChen19960902** [zjunlp/EasyEdit#74]
If I want to use ROME to edit the qwen14b model, compared to qwen-7b.yaml, I need to change the parameter to v_loss_layer=39 and model_name="my_model_path". Do I need to modify the "layers" parameter?

Thanks!

**Comment by xzwyyd** [comment]
The "layers" parameter typically specifies the layers of the model that you want to edit. If the default setting includes the layers you want to edit (in this case, up to layer 39) and you don't have specific requirements to change the layers, you can leave the "layers" parameter as is.

**Comment by zxlzr** [comment]
Hi buddy, have you solved your issue?
