### ISSUE TITLE
Multimodal model editing

### ISSUE THREAD

**Issue by JH-Yin** [zjunlp/EasyEdit#75]
I am very interested in your multimodal editing work, but when using the code, I found that in the COCO caption task, the image indexes involved in caption_train_edit.json and caption_eval_edit.josn are not in the image download link you provided. How can I solve it?

**Comment by tbozhong** [comment]
Hi there,

Thank you for bringing this to our attention, and I appreciate your interest in our work!

To make it easier for you and other users to find the necessary datasets, we have placed the links in a more prominent position in our repository. Now, you can access the images download link by scrolling down to the "Dataset for Multimodal" subsection

Should you encounter any further issues or have additional questions, please feel free to reach out.

**Comment by JH-Yin** [comment]
Thank you very much for your reply. But maybe because my previous statement was unclear, the question I want to ask seems to have not been resolved yet. So I will describe my problem in more detail: I have downloaded the image dataset (the download link you provided), but some of the image indexes contained in caption_train_edit.json and caption_eval_edit.josn (such as COCO_val2014_000000386164.jpg) which are no such pictures in the link you provided. How can I solve it?

**Comment by tbozhong** [comment]
Hi,

Thank you for your patience and for providing additional details on the issue. And we apologize for any inconvenience this has caused.

We have now updated the dataset to ensure all the referenced image indexes, including `COCO_val2014_000000386164.jpg`, are available. Please download the updated image dataset using the same link, which should now include the missing images.

If you encounter any more missing elements or have further questions, do not hesitate to reach out.

Thank you for your understanding and continued support of our work.

**Comment by zxlzr** [comment]
Hi buddy, have you solved your issue?

**Comment by JH-Yin** [comment]
Thank you very much for your reply, my problem has been solved.
