### ISSUE TITLE
MMEdit support LLaVA 

### ISSUE THREAD

**Issue by CiaoHe** [zjunlp/EasyEdit#78]
Interest in the paper " Can We Edit Multimodal Large Language Models?". It contains two implementations BLIP2 and miniGPT4. Just wondering is there any future plan involved implementation on LLaVA(https://github.com/haotian-liu/LLaVA/tree/main)

**Comment by cheng-siyuan** [comment]
Hi, in the future we will consider supporting more multimodal models. If you want to edit LLaVA easily, you can consider using some more general and simple editing methods like IKE.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zjunlp/EasyEdit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月3日(星期五) 晚上10:37
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zjunlp/EasyEdit] MMEdit support LLaVA  (Issue #78)





 
Interest in the paper " Can We Edit Multimodal Large Language Models?". It contains two implementations BLIP2 and miniGPT4. Just wondering is there any future plan involved implementation on LLaVA(https://github.com/haotian-liu/LLaVA/tree/main)
