### ISSUE TITLE
为何使用条件生成？

### ISSUE THREAD

**Issue by Vicky-Wil** [zjunlp/EasyEdit#81]
在colab中测试使用的是model.generate(), 为何在代码evalua.py中使用的是条件生成的方式呢？

**Comment by pengzju** [comment]
感谢您对EasyEdit的关注。采用条件生成，是为了更方便去测量指标。（防止LM生成一些不必要的token，例如说重复问题，阐述自己是个机器人等不必要的冗余信息）。目前的指标采用的是token level的accuracy，若直接generate，生成的字符串不好量化指标
