### ISSUE TITLE
Failed to reproduce your results for ROME

### ISSUE THREAD

**Issue by MohamedMaherMSFT** [zjunlp/EasyEdit#84]
I'm currently trying to replicate the evaluation you have done for all the available editing methods.

When I replicate ROME evaluation by running `examples/run_zsre_llama2.py` and using test data from `editing-data/data/portability/One Hop/zsre_mend_eval_portability_gpt4.json`. I got these results which is different from what's written in your README.md 
**Reliablilty**: 96.17731245503656
**Generalization**: 90.7274077042639
**locality**:  98.50082003691427
**portability:**  59.62330574515986

I ran the following code to compute the above results
Reliablilty: `sum([i["post"]["rewrite_acc"][0] for i in metrics])/len(metrics))`
Generalization: `sum([i["post"]["rephrase_acc"][0] for i in metrics])/len(metrics))`
locality: `sum([i["post"]["locality"]["neighborhood_acc"][0] for i in metrics])/len(metrics))`
portability: `sum([i["post"]["portability"]["one_hop_acc"][0] for i in metrics])/len(metrics))`

Can you please advise if I'm doing something wrong or the README needs to be updated? also if something is wrong how to replicate the correct evaluation.

**Comment by pengzju** [comment]
- In the paper, we use second-order momentum to adjust the model weights, `mom2_adjustment` is set to `True`. Perhaps the performance fluctuation comes from the setting of this hyperparameter
    - https://github.com/zjunlp/EasyEdit/blob/main/hparams/ROME/llama-7b.yaml#L13

**Comment by zxlzr** [comment]
Hi buddy, have you solved your issue?
