### ISSUE TITLE
How can I rebuild the results in the Paper "Editing Large Language Models: Problems, Methods, and Opportunities"

### ISSUE THREAD

**Issue by Junyiliu0** [zjunlp/EasyEdit#85]
1.As you mentioned, you introduced several tasks to evaluate the model metrics, but I couldn't find the relevant code on how to utilize these datasets, such as zsre_subject_replace.json. How should I use this data to reproduce the results mentioned in your paper?
<img width="528" alt="image" src="https://github.com/zjunlp/EasyEdit/assets/100564143/76bca838-f7f1-4684-933e-37f8c77fb70a">
<img width="516" alt="image" src="https://github.com/zjunlp/EasyEdit/assets/100564143/4b78fbdf-3304-4e6f-9a42-8d4032e4e6a7">
<img width="630" alt="image" src="https://github.com/zjunlp/EasyEdit/assets/100564143/6640c10a-5dc7-46ea-927b-a1af026095a9">
2.Another question is "In the paper, apart from Sequential Editing and other tasks that are sequential, are the results of all other tasks using the method which rolled back model after each edit?"

**Comment by pengzju** [comment]
- Specifically, `Subject-Replace`, `Reverse-Relation`, `One-hop` are in the category of `portability`, and you can set those dimensions as portability key to measure, `prompt` and `ground_truth` need to be given in each dimension. `Other-Attribution`, `Distracting` are in the category of `locality`, you can set those dimensions as locality key to measure
    - You can refer to `Step5` in ReadME
- Yes, the weights need to be rolled back in all other settings.

**Comment by Junyiliu0** [comment]
Thanks for your reply!
