### ISSUE TITLE
Multimodal Large Language Model Editing

### ISSUE THREAD

**Issue by JH-Yin** [zjunlp/EasyEdit#86]
Hello, I am very interested in the work you published on EMNLP2023(Can We Edit Multimodal Large Language Models?), but I encountered some problems when reading the paper and code. I hope to seek help from you:
Question 1: Five indicators are reported in Section 3.1 of the article, but M-Generality is not reported in Table 2. Did I overlook any important information?
Question 2: For Caption and VQA tasks, I would like to ask how these five evaluation indicators for the generation task are specifically calculated?
Question 3: In the code, I found that you did not directly use Blip2-OPT2.7b from Huggingface, but defined Blip2-OPT2.7b by yourself. I would like to ask what changes have been made between the model you defined and the model loaded directly on Huggingface?

I would be grateful if I could get your guidance.

**Comment by cheng-siyuan** [comment]
Thanks for your attention.
For Question 1: You can find the Generality results in Figure 5.
For Question 2: The code for the evaluation can be found [here](https://github.com/zjunlp/EasyEdit/blob/196a1b0d8746e04680c81c2eb6eddce1cb85b2d6/easyeditor/evaluate/evaluate.py#L467)
For Question 3: The huggingface model has the same weight as ours. But MiniGPT-4 is not uploaded to hf, so we all use LAVIS source code for consistency.

**Comment by zxlzr** [comment]
Hi, have you solved your issue?
