### ISSUE TITLE
Question about the evaluation metric

### ISSUE THREAD

**Issue by YJiangcm** [zjunlp/EasyEdit#92]
Thank you for your valuable work. I have a question about the returned metric. 

When I replicate FT evaluation by running `examples/run_zsre_llama2.py` and using test data from `editing-data/data/portability/One Hop/zsre_mend_eval_portability_gpt4.json`, I found that the returned result of each edit is a float number from 0.0 to 1.0, for example:

```
{
        "pre": {
            "rewrite_acc": 0.6000000238418579,
            "portability": {
                "one_hop_acc": 0.0
            },
            "rephrase_acc": 0.800000011920929
        },
        "case_id": 0,
        "requested_rewrite": {
            "prompt": "When was the inception of IAAF Combined Events Challenge?",
            "target_new": "2006",
            "ground_truth": "<|endoftext|>",
            "portability": {
                "one_hop": {
                    "prompt": "What type of sports event is the IAAF Combined Events Challenge, which was established in 2006?",
                    "ground_truth": "Athletics"
                }
            },
            "locality": {
                "neighborhood": {
                    "prompt": "nq question: what is the name of the last episode of spongebob",
                    "ground_truth": "The String"
                }
            },
            "subject": "IAAF Combined Events Challenge",
            "rephrase_prompt": "When was the IAAF Combined Events Challenge launched?"
        },
        "time": 0.7832095623016357,
        "post": {
            "rewrite_acc": 1.0,
            "locality": {
                "neighborhood_acc": 0.5
            },
            "portability": {
                "one_hop_acc": 0.0
            },
            "rephrase_acc": 1.0
        }
 },
```

However, if my understanding is correct, the returned accuracy **for each edit** should be either 0 or 1. Could you please explain why the rewrite_acc, rephrase_acc, neighborhood_acc, and one_hop_acc of a single edit is a number between 0 and 1? Thanks.

**Comment by wending0417** [comment]
The acc here is the acc that matches the predicted tokens and the standard tokens one by one.

**Comment by pengzju** [comment]
> The acc here is the acc that matches the predicted tokens and the standard tokens one by one.

yes😊, It is the accuracy of token level. (so range from 0.0 to 1.0)

**Comment by YJiangcm** [comment]
Thanks for your answering😊
