### ISSUE TITLE
OOM issue with "edit_IKE_MiniGPT4_VQA".

### ISSUE THREAD

**Issue by baixiaolu0802** [zjunlp/EasyEdit#97]
Thank you for this great work! I would like to know how much GPU memory is required for multimodal knowledge editing using "edit_IKE_MiniGPT4_VQA"? Does it support the use of multiple GPUs during multimodal knowledge editing, and if so, how should I do it?

**Comment by baixiaolu0802** [comment]
In addition, where can I get the file {hparams.task_name}_embeddings.pkl from ike_main?

**Comment by tbozhong** [comment]
Thanks for your attention to our work!

1) For IKE's GPU memory using MiniGPT4, it should take 21.48G as tested, while SERAC and MEND take 56.79G and 27.62G, respectively. We apologize that our framework does not support multi-GPU execution. However, we will consider adding this feature in future updates.

2) Apologies for not including specific examples earlier. We have now updated the repository. Please pull the latest code, and you'll find an example in `multimodal_edit.py` `edit_IKE_MiniGPT4_VQA()` for generating the necessary embedding files.

**Comment by zxlzr** [comment]
Hi, have you solved your issue?

**Comment by baixiaolu0802** [comment]
> Hi, have you solved your issue?
Thank you very much for your reply, my problem has been solved.
